-- Forge_APIRef-FrameAPICharacterModelBase: per-namespace API data for FrameAPICharacterModelBase.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/FrameAPICharacterModelBaseDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("FrameAPICharacterModelBase", {
    ApplySpellVisualKit = {
        params = {
            {
                name = "spellVisualKitID",
                nilable = false,
                type = "number",
            },
            {
                default = false,
                name = "oneShot",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.ApplySpellVisualKit(spellVisualKitID, oneShot)",
        type = "function",
    },
    CanSetUnit = {
        params = {
            {
                name = "unit",
                nilable = false,
                type = "UnitToken",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.CanSetUnit(unit)",
        type = "function",
    },
    FreezeAnimation = {
        params = {
            {
                name = "anim",
                nilable = false,
                type = "AnimationDataEnum",
            },
            {
                name = "variation",
                nilable = false,
                type = "number",
            },
            {
                name = "frame",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.FreezeAnimation(anim, variation, frame)",
        type = "function",
    },
    GetDisplayInfo = {
        params = {},
        returns = {
            {
                name = "displayID",
                nilable = false,
                type = "number",
            },
        },
        signature = "displayID = FrameAPICharacterModelBase.GetDisplayInfo()",
        type = "function",
    },
    GetDoBlend = {
        params = {},
        returns = {
            {
                name = "doBlend",
                nilable = false,
                type = "bool",
            },
        },
        signature = "doBlend = FrameAPICharacterModelBase.GetDoBlend()",
        type = "function",
    },
    GetKeepModelOnHide = {
        params = {},
        returns = {
            {
                name = "keepModelOnHide",
                nilable = false,
                type = "bool",
            },
        },
        signature = "keepModelOnHide = FrameAPICharacterModelBase.GetKeepModelOnHide()",
        type = "function",
    },
    HasAnimation = {
        params = {
            {
                name = "anim",
                nilable = false,
                type = "AnimationDataEnum",
            },
        },
        returns = {
            {
                name = "hasAnimation",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "hasAnimation = FrameAPICharacterModelBase.HasAnimation(anim)",
        type = "function",
    },
    PlayAnimKit = {
        params = {
            {
                name = "animKit",
                nilable = false,
                type = "number",
            },
            {
                default = false,
                name = "loop",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.PlayAnimKit(animKit, loop)",
        type = "function",
    },
    RefreshCamera = {
        params = {},
        returns = {},
        signature = "FrameAPICharacterModelBase.RefreshCamera()",
        type = "function",
    },
    RefreshUnit = {
        params = {},
        returns = {},
        signature = "FrameAPICharacterModelBase.RefreshUnit()",
        type = "function",
    },
    SetAnimation = {
        params = {
            {
                name = "anim",
                nilable = false,
                type = "AnimationDataEnum",
            },
            {
                name = "variation",
                nilable = true,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetAnimation(anim, variation)",
        type = "function",
    },
    SetBarberShopAlternateForm = {
        params = {},
        returns = {},
        signature = "FrameAPICharacterModelBase.SetBarberShopAlternateForm()",
        type = "function",
    },
    SetCamDistanceScale = {
        params = {
            {
                name = "scale",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetCamDistanceScale(scale)",
        type = "function",
    },
    SetCreature = {
        params = {
            {
                name = "creatureID",
                nilable = false,
                type = "number",
            },
            {
                default = 0,
                name = "displayID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetCreature(creatureID, displayID)",
        type = "function",
    },
    SetDisplayInfo = {
        params = {
            {
                name = "displayID",
                nilable = false,
                type = "number",
            },
            {
                name = "mountDisplayID",
                nilable = true,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetDisplayInfo(displayID, mountDisplayID)",
        type = "function",
    },
    SetDoBlend = {
        params = {
            {
                default = false,
                name = "doBlend",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetDoBlend(doBlend)",
        type = "function",
    },
    SetItem = {
        params = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "appearanceModID",
                nilable = true,
                type = "number",
            },
            {
                name = "itemVisualID",
                nilable = true,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetItem(itemID, appearanceModID, itemVisualID)",
        type = "function",
    },
    SetItemAppearance = {
        params = {
            {
                name = "itemAppearanceID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemVisualID",
                nilable = true,
                type = "number",
            },
            {
                name = "itemSubclass",
                nilable = true,
                type = "ItemWeaponSubclass",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetItemAppearance(itemAppearanceID, itemVisualID, itemSubclass)",
        type = "function",
    },
    SetKeepModelOnHide = {
        params = {
            {
                name = "keepModelOnHide",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetKeepModelOnHide(keepModelOnHide)",
        type = "function",
    },
    SetPortraitZoom = {
        params = {
            {
                name = "zoom",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetPortraitZoom(zoom)",
        type = "function",
    },
    SetRotation = {
        params = {
            {
                name = "radians",
                nilable = false,
                type = "number",
            },
            {
                default = true,
                name = "animate",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPICharacterModelBase.SetRotation(radians, animate)",
        type = "function",
    },
    SetUnit = {
        params = {
            {
                name = "unit",
                nilable = false,
                type = "UnitToken",
            },
            {
                default = true,
                name = "blend",
                nilable = false,
                type = "bool",
            },
            {
                name = "useNativeForm",
                nilable = true,
                type = "bool",
            },
        },
        returns = {
            {
                name = "success",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "success = FrameAPICharacterModelBase.SetUnit(unit, blend, useNativeForm)",
        type = "function",
    },
    StopAnimKit = {
        params = {},
        returns = {},
        signature = "FrameAPICharacterModelBase.StopAnimKit()",
        type = "function",
    },
    ZeroCachedCenterXY = {
        params = {},
        returns = {},
        signature = "FrameAPICharacterModelBase.ZeroCachedCenterXY()",
        type = "function",
    },
})
