-- Forge_APIRef-C_TransmogOutfitInfo: per-namespace API data for C_TransmogOutfitInfo.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/TransmogOutfitInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:31Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_TransmogOutfitInfo", {
    AddNewOutfit = {
        hasRestrictions = true,
        params = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "icon",
                nilable = false,
                type = "fileID",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.AddNewOutfit(name, icon)",
        type = "function",
    },
    ChangeDisplayedOutfit = {
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
            {
                name = "trigger",
                nilable = false,
                type = "TransmogSituationTrigger",
            },
            {
                name = "toggleLock",
                nilable = false,
                type = "bool",
            },
            {
                name = "allowRemoveOutfit",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.ChangeDisplayedOutfit(outfitID, trigger, toggleLock, allowRemoveOutfit)",
        type = "function",
    },
    ChangeToOutfit = {
        params = {
            {
                name = "playerFacingOutfitIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "allowRemoveOutfit",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.ChangeToOutfit(playerFacingOutfitIndex, allowRemoveOutfit)",
        type = "function",
    },
    ChangeViewedOutfit = {
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.ChangeViewedOutfit(outfitID)",
        type = "function",
    },
    ClearAllPendingSituations = {
        params = {},
        returns = {},
        signature = "C_TransmogOutfitInfo.ClearAllPendingSituations()",
        type = "function",
    },
    ClearAllPendingTransmogs = {
        params = {},
        returns = {},
        signature = "C_TransmogOutfitInfo.ClearAllPendingTransmogs()",
        type = "function",
    },
    ClearDisplayedOutfit = {
        params = {
            {
                name = "trigger",
                nilable = false,
                type = "TransmogSituationTrigger",
            },
            {
                name = "toggleLock",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.ClearDisplayedOutfit(trigger, toggleLock)",
        type = "function",
    },
    ClearOutfit = {
        params = {},
        returns = {},
        signature = "C_TransmogOutfitInfo.ClearOutfit()",
        type = "function",
    },
    CommitAndApplyAllPending = {
        params = {
            {
                name = "useAvailableDiscount",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.CommitAndApplyAllPending(useAvailableDiscount)",
        type = "function",
    },
    CommitOutfitInfo = {
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "icon",
                nilable = false,
                type = "fileID",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.CommitOutfitInfo(outfitID, name, icon)",
        type = "function",
    },
    CommitPendingSituations = {
        params = {},
        returns = {},
        signature = "C_TransmogOutfitInfo.CommitPendingSituations()",
        type = "function",
    },
    GetActiveOutfitID = {
        params = {},
        returns = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        signature = "outfitID = C_TransmogOutfitInfo.GetActiveOutfitID()",
        type = "function",
    },
    GetAllSlotLocationInfo = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                innerType = "TransmogOutfitSlotInfo",
                name = "appearanceSlotInfo",
                nilable = false,
                type = "table",
            },
            {
                innerType = "TransmogOutfitSlotInfo",
                name = "illusionSlotInfo",
                nilable = false,
                type = "table",
            },
        },
        signature = "appearanceSlotInfo, illusionSlotInfo = C_TransmogOutfitInfo.GetAllSlotLocationInfo()",
        type = "function",
    },
    GetAllTransmogOutfitOptionSheatheCategoryInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "imaID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "TransmogOutfitOptionSheatheCategoryInfo",
                name = "categoryInfo",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "categoryInfo = C_TransmogOutfitInfo.GetAllTransmogOutfitOptionSheatheCategoryInfo(imaID)",
        type = "function",
    },
    GetCollectionInfoForSlotAndOption = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "weaponOption",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
            {
                name = "collectionType",
                nilable = false,
                type = "TransmogCollectionType",
            },
        },
        returns = {
            {
                name = "collectionInfo",
                nilable = false,
                type = "TransmogOutfitWeaponCollectionInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "collectionInfo = C_TransmogOutfitInfo.GetCollectionInfoForSlotAndOption(slot, weaponOption, collectionType)",
        type = "function",
    },
    GetCurrentlyViewedOutfitID = {
        params = {},
        returns = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        signature = "outfitID = C_TransmogOutfitInfo.GetCurrentlyViewedOutfitID()",
        type = "function",
    },
    GetEquippedSlotOptionFromTransmogSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "weaponOption",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "weaponOption = C_TransmogOutfitInfo.GetEquippedSlotOptionFromTransmogSlot(slot)",
        type = "function",
    },
    GetIllusionDefaultIMAIDForCollectionType = {
        mayReturnNothing = true,
        params = {
            {
                name = "collectionType",
                nilable = false,
                type = "TransmogCollectionType",
            },
        },
        returns = {
            {
                name = "imaID",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "imaID = C_TransmogOutfitInfo.GetIllusionDefaultIMAIDForCollectionType(collectionType)",
        type = "function",
    },
    GetItemModifiedAppearanceEffectiveCategory = {
        params = {
            {
                name = "imaID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "categoryID",
                nilable = false,
                type = "TransmogCollectionType",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "categoryID = C_TransmogOutfitInfo.GetItemModifiedAppearanceEffectiveCategory(imaID)",
        type = "function",
    },
    GetLinkedSlotInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "linkedSlotInfo",
                nilable = false,
                type = "TransmogOutfitLinkedSlotInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "linkedSlotInfo = C_TransmogOutfitInfo.GetLinkedSlotInfo(slot)",
        type = "function",
    },
    GetMaxNumberOfTotalOutfitsForSource = {
        params = {
            {
                name = "source",
                nilable = false,
                type = "TransmogOutfitEntrySource",
            },
        },
        returns = {
            {
                name = "maxOutfitCount",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "maxOutfitCount = C_TransmogOutfitInfo.GetMaxNumberOfTotalOutfitsForSource(source)",
        type = "function",
    },
    GetMaxNumberOfUsableOutfits = {
        params = {},
        returns = {
            {
                name = "maxOutfitCount",
                nilable = false,
                type = "number",
            },
        },
        signature = "maxOutfitCount = C_TransmogOutfitInfo.GetMaxNumberOfUsableOutfits()",
        type = "function",
    },
    GetNextOutfitCost = {
        params = {},
        returns = {
            {
                name = "outfitCost",
                nilable = false,
                type = "BigUInteger",
            },
        },
        signature = "outfitCost = C_TransmogOutfitInfo.GetNextOutfitCost()",
        type = "function",
    },
    GetNumberOfOutfitsUnlockedForSource = {
        params = {
            {
                name = "source",
                nilable = false,
                type = "TransmogOutfitEntrySource",
            },
        },
        returns = {
            {
                name = "unlockedOutfitCount",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "unlockedOutfitCount = C_TransmogOutfitInfo.GetNumberOfOutfitsUnlockedForSource(source)",
        type = "function",
    },
    GetOutfitInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "outfitInfo",
                nilable = false,
                type = "TransmogOutfitEntryInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "outfitInfo = C_TransmogOutfitInfo.GetOutfitInfo(outfitID)",
        type = "function",
    },
    GetOutfitInfoByName = {
        mayReturnNothing = true,
        params = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "outfitInfo",
                nilable = false,
                type = "TransmogOutfitEntryInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "outfitInfo = C_TransmogOutfitInfo.GetOutfitInfoByName(name)",
        type = "function",
    },
    GetOutfitInfoByPlayerFacingIndex = {
        mayReturnNothing = true,
        params = {
            {
                name = "playerFacingOutfitIndex",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "outfitInfo",
                nilable = false,
                type = "TransmogOutfitEntryInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "outfitInfo = C_TransmogOutfitInfo.GetOutfitInfoByPlayerFacingIndex(playerFacingOutfitIndex)",
        type = "function",
    },
    GetOutfitSituation = {
        params = {
            {
                name = "option",
                nilable = false,
                type = "TransmogSituationOption",
            },
        },
        returns = {
            {
                name = "value",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "value = C_TransmogOutfitInfo.GetOutfitSituation(option)",
        type = "function",
    },
    GetOutfitSituationsEnabled = {
        params = {},
        returns = {
            {
                name = "enabled",
                nilable = false,
                type = "bool",
            },
        },
        signature = "enabled = C_TransmogOutfitInfo.GetOutfitSituationsEnabled()",
        type = "function",
    },
    GetOutfitsInfo = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                innerType = "TransmogOutfitEntryInfo",
                name = "outfitsInfo",
                nilable = false,
                type = "table",
            },
        },
        signature = "outfitsInfo = C_TransmogOutfitInfo.GetOutfitsInfo()",
        type = "function",
    },
    GetPendingTransmogCost = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "cost",
                nilable = false,
                type = "BigUInteger",
            },
            {
                name = "modifierFlags",
                nilable = false,
                type = "number",
            },
        },
        signature = "cost, modifierFlags = C_TransmogOutfitInfo.GetPendingTransmogCost()",
        type = "function",
    },
    GetSecondarySlotState = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "state",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "state = C_TransmogOutfitInfo.GetSecondarySlotState(slot)",
        type = "function",
    },
    GetSetSourcesForSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "transmogSetID",
                nilable = false,
                type = "number",
            },
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                innerType = "AppearanceSourceInfo",
                name = "sources",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "sources = C_TransmogOutfitInfo.GetSetSourcesForSlot(transmogSetID, slot)",
        type = "function",
    },
    GetSlotGroupInfo = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                innerType = "TransmogOutfitSlotGroup",
                name = "slotGroups",
                nilable = false,
                type = "table",
            },
        },
        signature = "slotGroups = C_TransmogOutfitInfo.GetSlotGroupInfo()",
        type = "function",
    },
    GetSourceIDsForSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "transmogSetID",
                nilable = false,
                type = "number",
            },
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "sources",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "sources = C_TransmogOutfitInfo.GetSourceIDsForSlot(transmogSetID, slot)",
        type = "function",
    },
    GetTransmogOutfitSlotForInventoryType = {
        mayReturnNothing = true,
        params = {
            {
                name = "inventoryType",
                nilable = false,
                type = "luaIndex",
            },
        },
        returns = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "slot = C_TransmogOutfitInfo.GetTransmogOutfitSlotForInventoryType(inventoryType)",
        type = "function",
    },
    GetTransmogOutfitSlotFromInventorySlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "inventorySlot",
                nilable = false,
                type = "InventorySlots",
            },
        },
        returns = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "slot = C_TransmogOutfitInfo.GetTransmogOutfitSlotFromInventorySlot(inventorySlot)",
        type = "function",
    },
    GetUISituationCategoriesAndOptions = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                innerType = "TransmogSituationCategory",
                name = "categoryData",
                nilable = false,
                type = "table",
            },
        },
        signature = "categoryData = C_TransmogOutfitInfo.GetUISituationCategoriesAndOptions()",
        type = "function",
    },
    GetUnassignedAtlasForSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "atlas",
                nilable = false,
                type = "textureAtlas",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "atlas = C_TransmogOutfitInfo.GetUnassignedAtlasForSlot(slot)",
        type = "function",
    },
    GetUnassignedDisplayAtlasForSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "atlas",
                nilable = false,
                type = "textureAtlas",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "atlas = C_TransmogOutfitInfo.GetUnassignedDisplayAtlasForSlot(slot)",
        type = "function",
    },
    GetViewedOutfitSlotInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "type",
                nilable = false,
                type = "TransmogType",
            },
            {
                name = "option",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
        },
        returns = {
            {
                name = "slotInfo",
                nilable = false,
                type = "ViewedTransmogOutfitSlotInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "slotInfo = C_TransmogOutfitInfo.GetViewedOutfitSlotInfo(slot, type, option)",
        type = "function",
    },
    GetWeaponOptionsForSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                innerType = "TransmogOutfitWeaponOptionInfo",
                name = "weaponOptions",
                nilable = false,
                type = "table",
            },
            {
                innerType = "TransmogOutfitWeaponOptionInfo",
                name = "artifactOptions",
                nilable = true,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "weaponOptions, artifactOptions = C_TransmogOutfitInfo.GetWeaponOptionsForSlot(slot)",
        type = "function",
    },
    HasPendingOutfitSituations = {
        params = {},
        returns = {
            {
                name = "hasPending",
                nilable = false,
                type = "bool",
            },
        },
        signature = "hasPending = C_TransmogOutfitInfo.HasPendingOutfitSituations()",
        type = "function",
    },
    HasPendingOutfitTransmogs = {
        params = {},
        returns = {
            {
                name = "hasPending",
                nilable = false,
                type = "bool",
            },
        },
        signature = "hasPending = C_TransmogOutfitInfo.HasPendingOutfitTransmogs()",
        type = "function",
    },
    InTransmogEvent = {
        params = {},
        returns = {
            {
                name = "inTransmogEvent",
                nilable = false,
                type = "bool",
            },
        },
        signature = "inTransmogEvent = C_TransmogOutfitInfo.InTransmogEvent()",
        type = "function",
    },
    IsEquippedGearOutfitDisplayed = {
        params = {},
        returns = {
            {
                name = "isDisplayed",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isDisplayed = C_TransmogOutfitInfo.IsEquippedGearOutfitDisplayed()",
        type = "function",
    },
    IsEquippedGearOutfitLocked = {
        params = {},
        returns = {
            {
                name = "isLocked",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isLocked = C_TransmogOutfitInfo.IsEquippedGearOutfitLocked()",
        type = "function",
    },
    IsLockedOutfit = {
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "isLocked",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isLocked = C_TransmogOutfitInfo.IsLockedOutfit(outfitID)",
        type = "function",
    },
    IsSlotWeaponSlot = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "isWeaponSlot",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isWeaponSlot = C_TransmogOutfitInfo.IsSlotWeaponSlot(slot)",
        type = "function",
    },
    IsUsableDiscountAvailable = {
        params = {},
        returns = {
            {
                name = "isAvailable",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isAvailable = C_TransmogOutfitInfo.IsUsableDiscountAvailable()",
        type = "function",
    },
    IsValidTransmogOutfitName = {
        params = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "isApproved",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isApproved = C_TransmogOutfitInfo.IsValidTransmogOutfitName(name)",
        type = "function",
    },
    PickupOutfit = {
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.PickupOutfit(outfitID)",
        type = "function",
    },
    ResetOutfitSituations = {
        params = {},
        returns = {},
        signature = "C_TransmogOutfitInfo.ResetOutfitSituations()",
        type = "function",
    },
    RevertPendingTransmog = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "type",
                nilable = false,
                type = "TransmogType",
            },
            {
                name = "option",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.RevertPendingTransmog(slot, type, option)",
        type = "function",
    },
    SetOutfitSituationsEnabled = {
        params = {
            {
                name = "enabled",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetOutfitSituationsEnabled(enabled)",
        type = "function",
    },
    SetOutfitToCustomSet = {
        params = {
            {
                name = "transmogCustomSetID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetOutfitToCustomSet(transmogCustomSetID)",
        type = "function",
    },
    SetOutfitToOutfit = {
        params = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetOutfitToOutfit(outfitID)",
        type = "function",
    },
    SetOutfitToSet = {
        params = {
            {
                name = "transmogSetID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetOutfitToSet(transmogSetID)",
        type = "function",
    },
    SetPendingTransmog = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "type",
                nilable = false,
                type = "TransmogType",
            },
            {
                name = "option",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
            {
                name = "transmogID",
                nilable = false,
                type = "number",
            },
            {
                name = "displayType",
                nilable = false,
                type = "TransmogOutfitDisplayType",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetPendingTransmog(slot, type, option, transmogID, displayType)",
        type = "function",
    },
    SetPendingTransmogSheatheCategory = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "option",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
            {
                name = "category",
                nilable = false,
                type = "TransmogOutfitSlotOptionSheatheCategory",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetPendingTransmogSheatheCategory(slot, option, category)",
        type = "function",
    },
    SetSecondarySlotState = {
        mayReturnNothing = true,
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "state",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetSecondarySlotState(slot, state)",
        type = "function",
    },
    SetViewedWeaponOptionForSlot = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "weaponOption",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.SetViewedWeaponOptionForSlot(slot, weaponOption)",
        type = "function",
    },
    SlotHasSecondary = {
        params = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
        },
        returns = {
            {
                name = "hasSecondary",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "hasSecondary = C_TransmogOutfitInfo.SlotHasSecondary(slot)",
        type = "function",
    },
    TRANSMOG_DISPLAYED_OUTFIT_CHANGED = {
        cppName = "TransmogDisplayedOutfitChanged",
        literalName = "TRANSMOG_DISPLAYED_OUTFIT_CHANGED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    TRANSMOG_OUTFITS_CHANGED = {
        cppName = "TransmogOutfitsChanged",
        literalName = "TRANSMOG_OUTFITS_CHANGED",
        payload = {
            {
                name = "newOutfitID",
                nilable = true,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    TransmogEventActive = {
        params = {},
        returns = {
            {
                name = "transmogEventActive",
                nilable = false,
                type = "bool",
            },
        },
        signature = "transmogEventActive = C_TransmogOutfitInfo.TransmogEventActive()",
        type = "function",
    },
    TransmogOutfitEntryInfo = {
        fields = {
            {
                name = "outfitID",
                nilable = false,
                type = "number",
            },
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                innerType = "cstring",
                name = "situationCategories",
                nilable = false,
                type = "table",
            },
            {
                name = "icon",
                nilable = false,
                type = "fileID",
            },
            {
                name = "isEventOutfit",
                nilable = false,
                type = "bool",
            },
            {
                name = "isDisabled",
                nilable = false,
                type = "bool",
            },
            {
                name = "playerFacingOutfitIndex",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    TransmogOutfitLinkedSlotInfo = {
        fields = {
            {
                name = "primarySlotInfo",
                nilable = false,
                type = "TransmogOutfitSlotInfo",
            },
            {
                name = "secondarySlotInfo",
                nilable = false,
                type = "TransmogOutfitSlotInfo",
            },
        },
        type = "structure",
    },
    TransmogOutfitOptionSheatheCategoryInfo = {
        fields = {
            {
                name = "sheatheCategory",
                nilable = false,
                type = "TransmogOutfitSlotOptionSheatheCategory",
            },
            {
                name = "categoryName",
                nilable = false,
                type = "cstring",
            },
        },
        type = "structure",
    },
    TransmogOutfitSlotGroup = {
        fields = {
            {
                name = "position",
                nilable = false,
                type = "TransmogOutfitSlotPosition",
            },
            {
                innerType = "TransmogOutfitSlotInfo",
                name = "appearanceSlotInfo",
                nilable = false,
                type = "table",
            },
            {
                innerType = "TransmogOutfitSlotInfo",
                name = "illusionSlotInfo",
                nilable = false,
                type = "table",
            },
        },
        type = "structure",
    },
    TransmogOutfitSlotInfo = {
        fields = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "type",
                nilable = false,
                type = "TransmogType",
            },
            {
                name = "collectionType",
                nilable = false,
                type = "TransmogCollectionType",
            },
            {
                name = "slotName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "isSecondary",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    TransmogOutfitWeaponCollectionInfo = {
        fields = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "isWeapon",
                nilable = false,
                type = "bool",
            },
            {
                name = "canHaveIllusions",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    TransmogOutfitWeaponOptionInfo = {
        fields = {
            {
                name = "weaponOption",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "enabled",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    TransmogSituationCategory = {
        fields = {
            {
                name = "triggerID",
                nilable = false,
                type = "number",
            },
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "description",
                nilable = false,
                type = "cstring",
            },
            {
                name = "isRadioButton",
                nilable = false,
                type = "bool",
            },
            {
                innerType = "TransmogSituationGroup",
                name = "groupData",
                nilable = false,
                type = "table",
            },
        },
        type = "structure",
    },
    TransmogSituationGroup = {
        fields = {
            {
                name = "groupID",
                nilable = false,
                type = "number",
            },
            {
                name = "secondaryID",
                nilable = false,
                type = "number",
            },
            {
                innerType = "TransmogSituationOptionData",
                name = "optionData",
                nilable = false,
                type = "table",
            },
        },
        type = "structure",
    },
    TransmogSituationOption = {
        fields = {
            {
                name = "situationID",
                nilable = false,
                type = "number",
            },
            {
                name = "specID",
                nilable = false,
                type = "number",
            },
            {
                name = "loadoutID",
                nilable = false,
                type = "number",
            },
            {
                name = "equipmentSetID",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    TransmogSituationOptionData = {
        fields = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "value",
                nilable = false,
                type = "bool",
            },
            {
                name = "option",
                nilable = false,
                type = "TransmogSituationOption",
            },
        },
        type = "structure",
    },
    UpdatePendingSituation = {
        mayReturnNothing = true,
        params = {
            {
                name = "option",
                nilable = false,
                type = "TransmogSituationOption",
            },
            {
                name = "value",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_TransmogOutfitInfo.UpdatePendingSituation(option, value)",
        type = "function",
    },
    VIEWED_TRANSMOG_OUTFIT_CHANGED = {
        cppName = "ViewedTransmogOutfitChanged",
        literalName = "VIEWED_TRANSMOG_OUTFIT_CHANGED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    VIEWED_TRANSMOG_OUTFIT_SECONDARY_SLOTS_CHANGED = {
        cppName = "ViewedTransmogOutfitSecondarySlotsChanged",
        literalName = "VIEWED_TRANSMOG_OUTFIT_SECONDARY_SLOTS_CHANGED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    VIEWED_TRANSMOG_OUTFIT_SITUATIONS_CHANGED = {
        cppName = "ViewedTransmogOutfitSituationsChanged",
        literalName = "VIEWED_TRANSMOG_OUTFIT_SITUATIONS_CHANGED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    VIEWED_TRANSMOG_OUTFIT_SLOT_REFRESH = {
        cppName = "ViewedTransmogOutfitSlotRefresh",
        literalName = "VIEWED_TRANSMOG_OUTFIT_SLOT_REFRESH",
        payload = {},
        synchronous = false,
        type = "event",
    },
    VIEWED_TRANSMOG_OUTFIT_SLOT_SAVE_SUCCESS = {
        cppName = "ViewedTransmogOutfitSlotSaveSuccess",
        literalName = "VIEWED_TRANSMOG_OUTFIT_SLOT_SAVE_SUCCESS",
        payload = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "type",
                nilable = false,
                type = "TransmogType",
            },
            {
                name = "option",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
        },
        synchronous = true,
        type = "event",
    },
    VIEWED_TRANSMOG_OUTFIT_SLOT_WEAPON_OPTION_CHANGED = {
        cppName = "ViewedTransmogOutfitSlotWeaponOptionChanged",
        literalName = "VIEWED_TRANSMOG_OUTFIT_SLOT_WEAPON_OPTION_CHANGED",
        payload = {
            {
                name = "slot",
                nilable = false,
                type = "TransmogOutfitSlot",
            },
            {
                name = "weaponOption",
                nilable = false,
                type = "TransmogOutfitSlotOption",
            },
        },
        synchronous = true,
        type = "event",
    },
    ViewedTransmogOutfitSlotInfo = {
        fields = {
            {
                name = "transmogID",
                nilable = false,
                type = "number",
            },
            {
                name = "displayType",
                nilable = false,
                type = "TransmogOutfitDisplayType",
            },
            {
                name = "isTransmogrified",
                nilable = false,
                type = "bool",
            },
            {
                name = "hasPending",
                nilable = false,
                type = "bool",
            },
            {
                name = "isPendingCollected",
                nilable = false,
                type = "bool",
            },
            {
                name = "canTransmogrify",
                nilable = false,
                type = "bool",
            },
            {
                name = "warning",
                nilable = false,
                type = "TransmogOutfitSlotWarning",
            },
            {
                name = "warningText",
                nilable = false,
                type = "cstring",
            },
            {
                name = "error",
                nilable = false,
                type = "TransmogOutfitSlotError",
            },
            {
                name = "errorText",
                nilable = false,
                type = "cstring",
            },
            {
                name = "texture",
                nilable = true,
                type = "fileID",
            },
            {
                name = "sheatheCategory",
                nilable = false,
                type = "TransmogOutfitSlotOptionSheatheCategory",
            },
        },
        type = "structure",
    },
})
