-- Forge_APIRef-MatrixShared: per-namespace API data for MatrixShared.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/MatrixSharedDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("MatrixShared", {})
