-- Forge_APIRef-C_BattlePet: per-namespace API data for C_BattlePet.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/BattlePetDocumentation.lua.
-- Generated 2026-05-06 13:02:25Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_BattlePet", {
    PET_BATTLE_ABILITY_CHANGED = {
        cppName = "PetBattleAbilityChanged",
        literalName = "PET_BATTLE_ABILITY_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "abilityID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_ACTION_SELECTED = {
        cppName = "PetBattleActionSelected",
        literalName = "PET_BATTLE_ACTION_SELECTED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_AURA_APPLIED = {
        cppName = "PetBattleAuraApplied",
        literalName = "PET_BATTLE_AURA_APPLIED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "auraInstanceID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_AURA_CANCELED = {
        cppName = "PetBattleAuraCanceled",
        literalName = "PET_BATTLE_AURA_CANCELED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "auraInstanceID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_AURA_CHANGED = {
        cppName = "PetBattleAuraChanged",
        literalName = "PET_BATTLE_AURA_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "auraInstanceID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_CAPTURED = {
        cppName = "PetBattleCaptured",
        literalName = "PET_BATTLE_CAPTURED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_CLOSE = {
        cppName = "PetBattleClose",
        literalName = "PET_BATTLE_CLOSE",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_FINAL_ROUND = {
        cppName = "PetBattleFinalRound",
        literalName = "PET_BATTLE_FINAL_ROUND",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_HEALTH_CHANGED = {
        cppName = "PetBattleHealthChanged",
        literalName = "PET_BATTLE_HEALTH_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "healthChange",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_LEVEL_CHANGED = {
        cppName = "PetBattleLevelChanged",
        literalName = "PET_BATTLE_LEVEL_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "newLevel",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_MAX_HEALTH_CHANGED = {
        cppName = "PetBattleMaxHealthChanged",
        literalName = "PET_BATTLE_MAX_HEALTH_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "healthChange",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_OPENING_DONE = {
        cppName = "PetBattleOpeningDone",
        literalName = "PET_BATTLE_OPENING_DONE",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_OPENING_START = {
        cppName = "PetBattleOpeningStart",
        literalName = "PET_BATTLE_OPENING_START",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_OVER = {
        cppName = "PetBattleOver",
        literalName = "PET_BATTLE_OVER",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_OVERRIDE_ABILITY = {
        cppName = "PetBattleOverrideAbility",
        literalName = "PET_BATTLE_OVERRIDE_ABILITY",
        payload = {
            {
                name = "abilityIndex",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_PET_CHANGED = {
        cppName = "PetBattlePetChanged",
        literalName = "PET_BATTLE_PET_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_PET_ROUND_PLAYBACK_COMPLETE = {
        cppName = "PetBattlePetRoundPlaybackComplete",
        literalName = "PET_BATTLE_PET_ROUND_PLAYBACK_COMPLETE",
        payload = {
            {
                name = "roundNumber",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_PET_ROUND_RESULTS = {
        cppName = "PetBattlePetRoundResults",
        literalName = "PET_BATTLE_PET_ROUND_RESULTS",
        payload = {
            {
                name = "roundNumber",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_PET_TYPE_CHANGED = {
        cppName = "PetBattlePetTypeChanged",
        literalName = "PET_BATTLE_PET_TYPE_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "stateValue",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_PVP_DUEL_REQUESTED = {
        cppName = "PetBattlePvpDuelRequested",
        literalName = "PET_BATTLE_PVP_DUEL_REQUESTED",
        payload = {
            {
                name = "fullName",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_PVP_DUEL_REQUEST_CANCEL = {
        cppName = "PetBattlePvpDuelRequestCancel",
        literalName = "PET_BATTLE_PVP_DUEL_REQUEST_CANCEL",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_QUEUE_PROPOSAL_ACCEPTED = {
        cppName = "PetBattleQueueProposalAccepted",
        literalName = "PET_BATTLE_QUEUE_PROPOSAL_ACCEPTED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_QUEUE_PROPOSAL_DECLINED = {
        cppName = "PetBattleQueueProposalDeclined",
        literalName = "PET_BATTLE_QUEUE_PROPOSAL_DECLINED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_QUEUE_PROPOSE_MATCH = {
        cppName = "PetBattleQueueProposeMatch",
        literalName = "PET_BATTLE_QUEUE_PROPOSE_MATCH",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_QUEUE_STATUS = {
        cppName = "PetBattleQueueStatus",
        literalName = "PET_BATTLE_QUEUE_STATUS",
        payload = {},
        synchronous = true,
        type = "event",
    },
    PET_BATTLE_XP_CHANGED = {
        cppName = "PetBattleXpChanged",
        literalName = "PET_BATTLE_XP_CHANGED",
        payload = {
            {
                name = "owner",
                nilable = false,
                type = "number",
            },
            {
                name = "petIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "xpChange",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
})
