-- Forge_APIRef-GuildConstants: per-namespace API data for GuildConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/GuildConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("GuildConstants", {
    GuildErrorType = {
        maxValue = 52,
        minValue = 0,
        numValues = 53,
        type = "enum",
        values = {
            {
                name = "Success",
                value = 0,
            },
            {
                name = "UnknownError",
                value = 1,
            },
            {
                name = "AlreadyInGuild",
                value = 2,
            },
            {
                name = "TargetAlreadyInGuild",
                value = 3,
            },
            {
                name = "InvitedToGuild",
                value = 4,
            },
            {
                name = "TargetInvitedToGuild",
                value = 5,
            },
            {
                name = "NameInvalid",
                value = 6,
            },
            {
                name = "NameAlreadyExists",
                value = 7,
            },
            {
                name = "NoPermisson",
                value = 8,
            },
            {
                name = "NotInGuild",
                value = 9,
            },
            {
                name = "TargetNotInGuild",
                value = 10,
            },
            {
                name = "PlayerNotFound",
                value = 11,
            },
            {
                name = "WrongFaction",
                value = 12,
            },
            {
                name = "TargetTooHigh",
                value = 13,
            },
            {
                name = "TargetTooLow",
                value = 14,
            },
            {
                name = "TooManyRanks",
                value = 15,
            },
            {
                name = "TooFewRanks",
                value = 16,
            },
            {
                name = "RanksLocked",
                value = 17,
            },
            {
                name = "RankInUse",
                value = 18,
            },
            {
                name = "Ignored",
                value = 19,
            },
            {
                name = "Busy",
                value = 20,
            },
            {
                name = "TargetLevelTooLow",
                value = 21,
            },
            {
                name = "TargetLevelTooHigh",
                value = 22,
            },
            {
                name = "TooManyMembers",
                value = 23,
            },
            {
                name = "InvalidBankTab",
                value = 24,
            },
            {
                name = "WithdrawLimit",
                value = 25,
            },
            {
                name = "NotEnoughMoney",
                value = 26,
            },
            {
                name = "TeamNotFound",
                value = 27,
            },
            {
                name = "BankTabFull",
                value = 28,
            },
            {
                name = "BadItem",
                value = 29,
            },
            {
                name = "TeamsLocked",
                value = 30,
            },
            {
                name = "TooMuchMoney",
                value = 31,
            },
            {
                name = "WrongBankTab",
                value = 32,
            },
            {
                name = "TooManyCreate",
                value = 33,
            },
            {
                name = "RankRequiresAuthenticator",
                value = 34,
            },
            {
                name = "BankTabLocked",
                value = 35,
            },
            {
                name = "TrialAccount",
                value = 36,
            },
            {
                name = "VeteranAccount",
                value = 37,
            },
            {
                name = "UndeletableDueToLevel",
                value = 38,
            },
            {
                name = "LockedForMove",
                value = 39,
            },
            {
                name = "GuildRepTooLow",
                value = 40,
            },
            {
                name = "CantInviteSelf",
                value = 41,
            },
            {
                name = "HasRestriction",
                value = 42,
            },
            {
                name = "BankNotFound",
                value = 43,
            },
            {
                name = "NewLeaderWrongFaction",
                value = 44,
            },
            {
                name = "GuildBankNotAvailable",
                value = 45,
            },
            {
                name = "NewLeaderWrongRealm",
                value = 46,
            },
            {
                name = "DeleteNoAppropriateLeader",
                value = 47,
            },
            {
                name = "RealmMismatch",
                value = 48,
            },
            {
                name = "InCooldown",
                value = 49,
            },
            {
                name = "ReservationExpired",
                value = 50,
            },
            {
                name = "HousingEvictError",
                value = 51,
            },
            {
                name = "Throttled",
                value = 52,
            },
        },
    },
})
