-- Forge_APIRef-C_LegendaryCrafting: per-namespace API data for C_LegendaryCrafting.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/LegendaryCraftingDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_LegendaryCrafting", {
    CloseRuneforgeInteraction = {
        params = {},
        returns = {},
        signature = "C_LegendaryCrafting.CloseRuneforgeInteraction()",
        type = "function",
    },
    CraftRuneforgeLegendary = {
        params = {
            {
                name = "description",
                nilable = false,
                type = "RuneforgeLegendaryCraftDescription",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_LegendaryCrafting.CraftRuneforgeLegendary(description)",
        type = "function",
    },
    GetRuneforgeItemPreviewInfo = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = false,
                type = "ItemLocation",
            },
            {
                name = "runeforgePowerID",
                nilable = true,
                type = "number",
            },
            {
                innerType = "number",
                name = "modifiers",
                nilable = true,
                type = "table",
            },
        },
        returns = {
            {
                name = "info",
                nilable = true,
                type = "RuneforgeItemPreviewInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "info = C_LegendaryCrafting.GetRuneforgeItemPreviewInfo(baseItem, runeforgePowerID, modifiers)",
        type = "function",
    },
    GetRuneforgeLegendaryComponentInfo = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "runeforgeLegendary",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "componentInfo",
                nilable = false,
                type = "RuneforgeLegendaryComponentInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "componentInfo = C_LegendaryCrafting.GetRuneforgeLegendaryComponentInfo(runeforgeLegendary)",
        type = "function",
    },
    GetRuneforgeLegendaryCost = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                innerType = "CurrencyCost",
                name = "cost",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "cost = C_LegendaryCrafting.GetRuneforgeLegendaryCost(baseItem)",
        type = "function",
    },
    GetRuneforgeLegendaryCraftSpellID = {
        params = {},
        returns = {
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
        },
        signature = "spellID = C_LegendaryCrafting.GetRuneforgeLegendaryCraftSpellID()",
        type = "function",
    },
    GetRuneforgeLegendaryCurrencies = {
        params = {},
        returns = {
            {
                innerType = "number",
                name = "currencies",
                nilable = false,
                type = "table",
            },
        },
        signature = "currencies = C_LegendaryCrafting.GetRuneforgeLegendaryCurrencies()",
        type = "function",
    },
    GetRuneforgeLegendaryUpgradeCost = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "runeforgeLegendary",
                nilable = false,
                type = "ItemLocation",
            },
            {
                mixin = "ItemLocationMixin",
                name = "upgradeItem",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                innerType = "CurrencyCost",
                name = "cost",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "cost = C_LegendaryCrafting.GetRuneforgeLegendaryUpgradeCost(runeforgeLegendary, upgradeItem)",
        type = "function",
    },
    GetRuneforgeModifierInfo = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = false,
                type = "ItemLocation",
            },
            {
                name = "powerID",
                nilable = true,
                type = "number",
            },
            {
                name = "addedModifierIndex",
                nilable = false,
                type = "luaIndex",
            },
            {
                innerType = "number",
                name = "modifiers",
                nilable = false,
                type = "table",
            },
        },
        returns = {
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                innerType = "string",
                name = "description",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "name, description = C_LegendaryCrafting.GetRuneforgeModifierInfo(baseItem, powerID, addedModifierIndex, modifiers)",
        type = "function",
    },
    GetRuneforgeModifiers = {
        params = {},
        returns = {
            {
                innerType = "number",
                name = "modifiedReagentItemIDs",
                nilable = false,
                type = "table",
            },
        },
        signature = "modifiedReagentItemIDs = C_LegendaryCrafting.GetRuneforgeModifiers()",
        type = "function",
    },
    GetRuneforgePowerInfo = {
        params = {
            {
                name = "runeforgePowerID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "power",
                nilable = false,
                type = "RuneforgePower",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "power = C_LegendaryCrafting.GetRuneforgePowerInfo(runeforgePowerID)",
        type = "function",
    },
    GetRuneforgePowerSlots = {
        params = {
            {
                name = "runeforgePowerID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "cstring",
                name = "slotNames",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "slotNames = C_LegendaryCrafting.GetRuneforgePowerSlots(runeforgePowerID)",
        type = "function",
    },
    GetRuneforgePowers = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = true,
                type = "ItemLocation",
            },
            {
                name = "filter",
                nilable = true,
                type = "RuneforgePowerFilter",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "primaryRuneforgePowerIDs",
                nilable = false,
                type = "table",
            },
            {
                innerType = "number",
                name = "otherRuneforgePowerIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "primaryRuneforgePowerIDs, otherRuneforgePowerIDs = C_LegendaryCrafting.GetRuneforgePowers(baseItem, filter)",
        type = "function",
    },
    GetRuneforgePowersByClassSpecAndCovenant = {
        params = {
            {
                name = "classID",
                nilable = true,
                type = "number",
            },
            {
                name = "specID",
                nilable = true,
                type = "number",
            },
            {
                name = "covenantID",
                nilable = true,
                type = "number",
            },
            {
                name = "filter",
                nilable = true,
                type = "RuneforgePowerFilter",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "runeforgePowerIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "runeforgePowerIDs = C_LegendaryCrafting.GetRuneforgePowersByClassSpecAndCovenant(classID, specID, covenantID, filter)",
        type = "function",
    },
    IsRuneforgeLegendary = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "item",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isRuneforgeLegendary",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isRuneforgeLegendary = C_LegendaryCrafting.IsRuneforgeLegendary(item)",
        type = "function",
    },
    IsRuneforgeLegendaryMaxLevel = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "runeforgeLegendary",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isMaxLevel",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isMaxLevel = C_LegendaryCrafting.IsRuneforgeLegendaryMaxLevel(runeforgeLegendary)",
        type = "function",
    },
    IsUpgradeItemValidForRuneforgeLegendary = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "runeforgeLegendary",
                nilable = false,
                type = "ItemLocation",
            },
            {
                mixin = "ItemLocationMixin",
                name = "upgradeItem",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isValid",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isValid = C_LegendaryCrafting.IsUpgradeItemValidForRuneforgeLegendary(runeforgeLegendary, upgradeItem)",
        type = "function",
    },
    IsValidRuneforgeBaseItem = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isValid",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isValid = C_LegendaryCrafting.IsValidRuneforgeBaseItem(baseItem)",
        type = "function",
    },
    MakeRuneforgeCraftDescription = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = false,
                type = "ItemLocation",
            },
            {
                name = "runeforgePowerID",
                nilable = false,
                type = "number",
            },
            {
                innerType = "number",
                name = "modifiers",
                nilable = false,
                type = "table",
            },
        },
        returns = {
            {
                name = "description",
                nilable = false,
                type = "RuneforgeLegendaryCraftDescription",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "description = C_LegendaryCrafting.MakeRuneforgeCraftDescription(baseItem, runeforgePowerID, modifiers)",
        type = "function",
    },
    NEW_RUNEFORGE_POWER_ADDED = {
        cppName = "NewRuneforgePowerAdded",
        literalName = "NEW_RUNEFORGE_POWER_ADDED",
        payload = {
            {
                name = "powerID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    RUNEFORGE_LEGENDARY_CRAFTING_CLOSED = {
        cppName = "RuneforgeLegendaryCraftingClosed",
        literalName = "RUNEFORGE_LEGENDARY_CRAFTING_CLOSED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    RUNEFORGE_LEGENDARY_CRAFTING_OPENED = {
        cppName = "RuneforgeLegendaryCraftingOpened",
        literalName = "RUNEFORGE_LEGENDARY_CRAFTING_OPENED",
        payload = {
            {
                name = "isUpgrade",
                nilable = false,
                type = "bool",
            },
        },
        synchronous = true,
        type = "event",
    },
    RUNEFORGE_POWER_INFO_UPDATED = {
        cppName = "RuneforgePowerInfoUpdated",
        literalName = "RUNEFORGE_POWER_INFO_UPDATED",
        payload = {
            {
                name = "powerID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    UpgradeRuneforgeLegendary = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "runeforgeLegendary",
                nilable = false,
                type = "ItemLocation",
            },
            {
                mixin = "ItemLocationMixin",
                name = "upgradeItem",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_LegendaryCrafting.UpgradeRuneforgeLegendary(runeforgeLegendary, upgradeItem)",
        type = "function",
    },
})
