-- Forge_APIRef-FrameAPIScenarioPOI: per-namespace API data for FrameAPIScenarioPOI.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/FrameAPIScenarioPOIDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("FrameAPIScenarioPOI", {
    GetScenarioTooltipText = {
        params = {},
        returns = {
            {
                name = "tooltipText",
                nilable = true,
                type = "cstring",
            },
        },
        signature = "tooltipText = FrameAPIScenarioPOI.GetScenarioTooltipText()",
        type = "function",
    },
    UpdateMouseOverTooltip = {
        params = {
            {
                name = "x",
                nilable = false,
                type = "number",
            },
            {
                name = "y",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "hasTooltip",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "hasTooltip = FrameAPIScenarioPOI.UpdateMouseOverTooltip(x, y)",
        type = "function",
    },
})
