-- Forge_APIRef-UIMapPinShared: per-namespace API data for UIMapPinShared.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/UIMapPinSharedDocumentation.lua.
-- Generated 2026-05-06 13:02:31Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("UIMapPinShared", {
    UIMapPinInfo = {
        fields = {
            {
                name = "button",
                nilable = false,
                type = "UIButtonInfo",
            },
            {
                name = "buttonSelected",
                nilable = false,
                type = "UIButtonInfo",
            },
            {
                name = "underlay",
                nilable = false,
                type = "textureAtlas",
            },
            {
                name = "outerGlow",
                nilable = false,
                type = "textureAtlas",
            },
        },
        type = "structure",
    },
})
