-- Forge_APIRef-C_InvasionInfo: per-namespace API data for C_InvasionInfo.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/InvasionInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_InvasionInfo", {
    AreInvasionsAvailable = {
        desc = "Returns true if invasions are active in the same physical area as the player.",
        params = {},
        returns = {
            {
                name = "areInvasionsAvailable",
                nilable = false,
                type = "bool",
            },
        },
        signature = "areInvasionsAvailable = C_InvasionInfo.AreInvasionsAvailable()",
        type = "function",
    },
    GetInvasionForUiMapID = {
        params = {
            {
                name = "uiMapID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "invasionID",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "invasionID = C_InvasionInfo.GetInvasionForUiMapID(uiMapID)",
        type = "function",
    },
    GetInvasionInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "invasionID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "invasionInfo",
                nilable = false,
                type = "InvasionMapInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "invasionInfo = C_InvasionInfo.GetInvasionInfo(invasionID)",
        type = "function",
    },
    GetInvasionTimeLeft = {
        params = {
            {
                name = "invasionID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "timeLeftMinutes",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "timeLeftMinutes = C_InvasionInfo.GetInvasionTimeLeft(invasionID)",
        type = "function",
    },
    InvasionMapInfo = {
        fields = {
            {
                name = "invasionID",
                nilable = false,
                type = "number",
            },
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                mixin = "Vector2DMixin",
                name = "position",
                nilable = false,
                type = "vector2",
            },
            {
                name = "atlasName",
                nilable = false,
                type = "textureAtlas",
            },
            {
                name = "rewardQuestID",
                nilable = true,
                type = "number",
            },
        },
        type = "structure",
    },
})
