-- Forge_APIRef-CinematicConstants: per-namespace API data for CinematicConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/CinematicConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:26Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("CinematicConstants", {
    CinematicType = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "GlueMovie",
                value = 0,
            },
            {
                name = "GameMovie",
                value = 1,
            },
            {
                name = "GameClientScene",
                value = 2,
            },
            {
                name = "GameCinematicSequence",
                value = 3,
            },
        },
    },
})
