-- Forge_APIRef-C_Bank: per-namespace API data for C_Bank.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/BankDocumentation.lua.
-- Generated 2026-05-06 13:02:25Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_Bank", {
    AreAnyBankTypesViewable = {
        params = {},
        returns = {
            {
                name = "areAnyBankTypesViewable",
                nilable = false,
                type = "bool",
            },
        },
        signature = "areAnyBankTypesViewable = C_Bank.AreAnyBankTypesViewable()",
        type = "function",
    },
    AutoDepositItemsIntoBank = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Bank.AutoDepositItemsIntoBank(bankType)",
        type = "function",
    },
    BANKFRAME_CLOSED = {
        cppName = "BankframeClosed",
        literalName = "BANKFRAME_CLOSED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    BANKFRAME_OPENED = {
        cppName = "BankframeOpened",
        literalName = "BANKFRAME_OPENED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    BANK_BAG_SLOT_FLAGS_UPDATED = {
        cppName = "BankBagSlotFlagsUpdated",
        literalName = "BANK_BAG_SLOT_FLAGS_UPDATED",
        payload = {
            {
                name = "slot",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    BANK_TABS_CHANGED = {
        cppName = "BankTabsChanged",
        literalName = "BANK_TABS_CHANGED",
        payload = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        synchronous = true,
        type = "event",
    },
    BANK_TAB_SETTINGS_UPDATED = {
        cppName = "BankTabSettingsUpdated",
        literalName = "BANK_TAB_SETTINGS_UPDATED",
        payload = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        synchronous = true,
        type = "event",
    },
    BankLockedReason = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "NoAccountInventoryLock",
                value = 1,
            },
            {
                name = "BankDisabled",
                value = 2,
            },
            {
                name = "BankConversionFailed",
                value = 3,
            },
        },
    },
    BankTabData = {
        fields = {
            {
                name = "ID",
                nilable = false,
                type = "number",
            },
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "icon",
                nilable = false,
                type = "fileID",
            },
            {
                name = "depositFlags",
                nilable = false,
                type = "BagSlotFlags",
            },
            {
                name = "tabCleanupConfirmation",
                nilable = false,
                type = "cstring",
            },
            {
                name = "tabNameEditBoxHeader",
                nilable = false,
                type = "cstring",
            },
        },
        type = "structure",
    },
    CanDepositMoney = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "canDepositMoney",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canDepositMoney = C_Bank.CanDepositMoney(bankType)",
        type = "function",
    },
    CanPurchaseBankTab = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "canPurchaseBankTab",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canPurchaseBankTab = C_Bank.CanPurchaseBankTab(bankType)",
        type = "function",
    },
    CanUseBank = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "canUseBank",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canUseBank = C_Bank.CanUseBank(bankType)",
        type = "function",
    },
    CanViewBank = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "canViewBank",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canViewBank = C_Bank.CanViewBank(bankType)",
        type = "function",
    },
    CanWithdrawMoney = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "canWithdrawMoney",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canWithdrawMoney = C_Bank.CanWithdrawMoney(bankType)",
        type = "function",
    },
    CloseBankFrame = {
        params = {},
        returns = {},
        signature = "C_Bank.CloseBankFrame()",
        type = "function",
    },
    DepositMoney = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
            {
                name = "amount",
                nilable = false,
                type = "WOWMONEY",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Bank.DepositMoney(bankType, amount)",
        type = "function",
    },
    DoesBankTypeSupportAutoDeposit = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "doesBankTypeSupportAutoDeposit",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "doesBankTypeSupportAutoDeposit = C_Bank.DoesBankTypeSupportAutoDeposit(bankType)",
        type = "function",
    },
    DoesBankTypeSupportMoneyTransfer = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "doesBankTypeSupportMoneyTransfer",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "doesBankTypeSupportMoneyTransfer = C_Bank.DoesBankTypeSupportMoneyTransfer(bankType)",
        type = "function",
    },
    FetchBankLockedReason = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "reason",
                nilable = true,
                type = "BankLockedReason",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "reason = C_Bank.FetchBankLockedReason(bankType)",
        type = "function",
    },
    FetchDepositedMoney = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "amount",
                nilable = false,
                type = "WOWMONEY",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "amount = C_Bank.FetchDepositedMoney(bankType)",
        type = "function",
    },
    FetchNextPurchasableBankTabData = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "nextPurchasableTabData",
                nilable = true,
                type = "PurchasableBankTabData",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "nextPurchasableTabData = C_Bank.FetchNextPurchasableBankTabData(bankType)",
        type = "function",
    },
    FetchNumPurchasedBankTabs = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "numPurchasedBankTabs",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "numPurchasedBankTabs = C_Bank.FetchNumPurchasedBankTabs(bankType)",
        type = "function",
    },
    FetchPurchasedBankTabData = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                innerType = "BankTabData",
                name = "purchasedBankTabData",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "purchasedBankTabData = C_Bank.FetchPurchasedBankTabData(bankType)",
        type = "function",
    },
    FetchPurchasedBankTabIDs = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                innerType = "BagIndex",
                name = "purchasedBankTabIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "purchasedBankTabIDs = C_Bank.FetchPurchasedBankTabIDs(bankType)",
        type = "function",
    },
    FetchViewableBankTypes = {
        params = {},
        returns = {
            {
                innerType = "BankType",
                name = "viewableBankTypes",
                nilable = false,
                type = "table",
            },
        },
        signature = "viewableBankTypes = C_Bank.FetchViewableBankTypes()",
        type = "function",
    },
    HasMaxBankTabs = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {
            {
                name = "hasMaxBankTabs",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "hasMaxBankTabs = C_Bank.HasMaxBankTabs(bankType)",
        type = "function",
    },
    IsItemAllowedInBankType = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isItemAllowedInBankType",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isItemAllowedInBankType = C_Bank.IsItemAllowedInBankType(bankType, itemLocation)",
        type = "function",
    },
    PLAYERBANKSLOTS_CHANGED = {
        cppName = "PlayerbankslotsChanged",
        literalName = "PLAYERBANKSLOTS_CHANGED",
        payload = {
            {
                name = "slot",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED = {
        cppName = "PlayerAccountBankTabSlotsChanged",
        literalName = "PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED",
        payload = {
            {
                name = "slot",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    PurchasableBankTabData = {
        fields = {
            {
                name = "tabCost",
                nilable = false,
                type = "BigUInteger",
            },
            {
                name = "canAfford",
                nilable = false,
                type = "bool",
            },
            {
                name = "purchasePromptTitle",
                nilable = false,
                type = "cstring",
            },
            {
                name = "purchasePromptBody",
                nilable = false,
                type = "cstring",
            },
            {
                name = "purchasePromptConfirmation",
                nilable = false,
                type = "cstring",
            },
        },
        type = "structure",
    },
    PurchaseBankTab = {
        hasRestrictions = true,
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Bank.PurchaseBankTab(bankType)",
        type = "function",
    },
    UpdateBankTabSettings = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
            {
                name = "tabID",
                nilable = false,
                type = "BagIndex",
            },
            {
                name = "tabName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "tabIcon",
                nilable = false,
                type = "cstring",
            },
            {
                name = "depositFlags",
                nilable = false,
                type = "BagSlotFlags",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Bank.UpdateBankTabSettings(bankType, tabID, tabName, tabIcon, depositFlags)",
        type = "function",
    },
    WithdrawMoney = {
        params = {
            {
                name = "bankType",
                nilable = false,
                type = "BankType",
            },
            {
                name = "amount",
                nilable = false,
                type = "WOWMONEY",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Bank.WithdrawMoney(bankType, amount)",
        type = "function",
    },
})
