-- Forge_APIRef-C_SuperTrack: per-namespace API data for C_SuperTrack.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/SuperTrackManagerDocumentation.lua.
-- Generated 2026-05-06 13:02:31Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_SuperTrack", {
    ClearAllSuperTracked = {
        params = {},
        returns = {},
        signature = "C_SuperTrack.ClearAllSuperTracked()",
        type = "function",
    },
    ClearSuperTrackedContent = {
        params = {},
        returns = {},
        signature = "C_SuperTrack.ClearSuperTrackedContent()",
        type = "function",
    },
    ClearSuperTrackedMapPin = {
        params = {},
        returns = {},
        signature = "C_SuperTrack.ClearSuperTrackedMapPin()",
        type = "function",
    },
    GetHighestPrioritySuperTrackingType = {
        params = {},
        returns = {
            {
                name = "type",
                nilable = true,
                type = "SuperTrackingType",
            },
        },
        signature = "type = C_SuperTrack.GetHighestPrioritySuperTrackingType()",
        type = "function",
    },
    GetNextWaypointForMap = {
        mayReturnNothing = true,
        params = {
            {
                name = "uiMapID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "x",
                nilable = false,
                type = "number",
            },
            {
                name = "y",
                nilable = false,
                type = "number",
            },
            {
                name = "waypointDescription",
                nilable = false,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "x, y, waypointDescription = C_SuperTrack.GetNextWaypointForMap(uiMapID)",
        type = "function",
    },
    GetSuperTrackedContent = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "trackableType",
                nilable = false,
                type = "ContentTrackingType",
            },
            {
                name = "trackableID",
                nilable = false,
                type = "number",
            },
        },
        signature = "trackableType, trackableID = C_SuperTrack.GetSuperTrackedContent()",
        type = "function",
    },
    GetSuperTrackedItemName = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                name = "description",
                nilable = false,
                type = "string",
            },
        },
        signature = "name, description = C_SuperTrack.GetSuperTrackedItemName()",
        type = "function",
    },
    GetSuperTrackedMapPin = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "type",
                nilable = false,
                type = "SuperTrackingMapPinType",
            },
            {
                name = "typeID",
                nilable = false,
                type = "number",
            },
        },
        signature = "type, typeID = C_SuperTrack.GetSuperTrackedMapPin()",
        type = "function",
    },
    GetSuperTrackedQuestID = {
        params = {},
        returns = {
            {
                name = "questID",
                nilable = true,
                type = "number",
            },
        },
        signature = "questID = C_SuperTrack.GetSuperTrackedQuestID()",
        type = "function",
    },
    GetSuperTrackedVignette = {
        params = {},
        returns = {
            {
                name = "vignetteGUID",
                nilable = true,
                type = "WOWGUID",
            },
        },
        signature = "vignetteGUID = C_SuperTrack.GetSuperTrackedVignette()",
        type = "function",
    },
    IsSuperTrackingAnything = {
        params = {},
        returns = {
            {
                name = "isSuperTracking",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSuperTracking = C_SuperTrack.IsSuperTrackingAnything()",
        type = "function",
    },
    IsSuperTrackingContent = {
        params = {},
        returns = {
            {
                name = "isSuperTracking",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSuperTracking = C_SuperTrack.IsSuperTrackingContent()",
        type = "function",
    },
    IsSuperTrackingCorpse = {
        params = {},
        returns = {
            {
                name = "isSuperTracking",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSuperTracking = C_SuperTrack.IsSuperTrackingCorpse()",
        type = "function",
    },
    IsSuperTrackingMapPin = {
        params = {},
        returns = {
            {
                name = "isSuperTracking",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSuperTracking = C_SuperTrack.IsSuperTrackingMapPin()",
        type = "function",
    },
    IsSuperTrackingQuest = {
        params = {},
        returns = {
            {
                name = "isSuperTracking",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSuperTracking = C_SuperTrack.IsSuperTrackingQuest()",
        type = "function",
    },
    IsSuperTrackingUserWaypoint = {
        params = {},
        returns = {
            {
                name = "isSuperTracking",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSuperTracking = C_SuperTrack.IsSuperTrackingUserWaypoint()",
        type = "function",
    },
    SUPER_TRACKING_CHANGED = {
        cppName = "SuperTrackingChanged",
        literalName = "SUPER_TRACKING_CHANGED",
        payload = {},
        synchronous = false,
        type = "event",
    },
    SUPER_TRACKING_PATH_UPDATED = {
        cppName = "SuperTrackingPathUpdated",
        literalName = "SUPER_TRACKING_PATH_UPDATED",
        payload = {},
        synchronous = false,
        type = "event",
    },
    SetSuperTrackedContent = {
        params = {
            {
                name = "trackableType",
                nilable = false,
                type = "ContentTrackingType",
            },
            {
                name = "trackableID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_SuperTrack.SetSuperTrackedContent(trackableType, trackableID)",
        type = "function",
    },
    SetSuperTrackedMapPin = {
        params = {
            {
                name = "type",
                nilable = false,
                type = "SuperTrackingMapPinType",
            },
            {
                name = "typeID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_SuperTrack.SetSuperTrackedMapPin(type, typeID)",
        type = "function",
    },
    SetSuperTrackedQuestID = {
        params = {
            {
                name = "questID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_SuperTrack.SetSuperTrackedQuestID(questID)",
        type = "function",
    },
    SetSuperTrackedUserWaypoint = {
        params = {
            {
                name = "superTracked",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_SuperTrack.SetSuperTrackedUserWaypoint(superTracked)",
        type = "function",
    },
    SetSuperTrackedVignette = {
        params = {
            {
                name = "vignetteGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_SuperTrack.SetSuperTrackedVignette(vignetteGUID)",
        type = "function",
    },
})
