-- Forge_APIRef-C_LoadingScreen: per-namespace API data for C_LoadingScreen.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/LoadingScreenDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_LoadingScreen", {
    LOADING_SCREEN_DISABLED = {
        cppName = "LoadingScreenDisabled",
        literalName = "LOADING_SCREEN_DISABLED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    LOADING_SCREEN_ENABLED = {
        cppName = "LoadingScreenEnabled",
        literalName = "LOADING_SCREEN_ENABLED",
        payload = {},
        synchronous = true,
        type = "event",
    },
})
