-- Forge_APIRef-FrameAPITabardModelBase: per-namespace API data for FrameAPITabardModelBase.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/FrameAPITabardModelBaseDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("FrameAPITabardModelBase", {
    CanSaveTabardNow = {
        params = {},
        returns = {
            {
                name = "canSave",
                nilable = false,
                type = "bool",
            },
        },
        signature = "canSave = FrameAPITabardModelBase.CanSaveTabardNow()",
        type = "function",
    },
    CycleVariation = {
        params = {
            {
                name = "variationIndex",
                nilable = false,
                type = "luaIndex",
            },
            {
                name = "delta",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPITabardModelBase.CycleVariation(variationIndex, delta)",
        type = "function",
    },
    GetLowerEmblemTexture = {
        params = {
            {
                name = "texture",
                nilable = false,
                type = "SimpleTexture",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPITabardModelBase.GetLowerEmblemTexture(texture)",
        type = "function",
    },
    GetUpperEmblemTexture = {
        params = {
            {
                name = "texture",
                nilable = false,
                type = "SimpleTexture",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPITabardModelBase.GetUpperEmblemTexture(texture)",
        type = "function",
    },
    InitializeTabardColors = {
        params = {},
        returns = {},
        signature = "FrameAPITabardModelBase.InitializeTabardColors()",
        type = "function",
    },
    IsGuildTabard = {
        params = {},
        returns = {
            {
                name = "isGuildTabard",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isGuildTabard = FrameAPITabardModelBase.IsGuildTabard()",
        type = "function",
    },
    Save = {
        params = {},
        returns = {},
        signature = "FrameAPITabardModelBase.Save()",
        type = "function",
    },
})
