-- Forge_APIRef-C_Glue: per-namespace API data for C_Glue.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/GlueDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_Glue", {
    ACCOUNT_CVARS_LOADED = {
        cppName = "AccountCvarsLoaded",
        literalName = "ACCOUNT_CVARS_LOADED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    IsFirstLoadThisSession = {
        params = {},
        returns = {
            {
                name = "IsFirstLoadThisSession",
                nilable = false,
                type = "bool",
            },
        },
        signature = "IsFirstLoadThisSession = C_Glue.IsFirstLoadThisSession()",
        type = "function",
    },
    IsOnGlueScreen = {
        params = {},
        returns = {
            {
                name = "isOnGlueScreen",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isOnGlueScreen = C_Glue.IsOnGlueScreen()",
        type = "function",
    },
})
