-- Forge_APIRef-C_Navigation: per-namespace API data for C_Navigation.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/InGameNavigationDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_Navigation", {
    GetDistance = {
        params = {},
        returns = {
            {
                name = "distance",
                nilable = false,
                type = "number",
            },
        },
        signature = "distance = C_Navigation.GetDistance()",
        type = "function",
    },
    GetFrame = {
        params = {},
        returns = {
            {
                name = "frame",
                nilable = true,
                type = "ScriptRegion",
            },
        },
        signature = "frame = C_Navigation.GetFrame()",
        type = "function",
    },
    GetNearestPartyMemberToken = {
        hasRestrictions = true,
        params = {},
        returns = {
            {
                name = "unitToken",
                nilable = false,
                type = "cstring",
            },
        },
        signature = "unitToken = C_Navigation.GetNearestPartyMemberToken()",
        type = "function",
    },
    GetTargetState = {
        params = {},
        returns = {
            {
                name = "state",
                nilable = false,
                type = "NavigationState",
            },
        },
        signature = "state = C_Navigation.GetTargetState()",
        type = "function",
    },
    HasValidScreenPosition = {
        params = {},
        returns = {
            {
                name = "hasValidScreenPosition",
                nilable = false,
                type = "bool",
            },
        },
        signature = "hasValidScreenPosition = C_Navigation.HasValidScreenPosition()",
        type = "function",
    },
    NAVIGATION_DESTINATION_REACHED = {
        cppName = "NavigationDestinationReached",
        literalName = "NAVIGATION_DESTINATION_REACHED",
        payload = {
            {
                name = "isWaypoint",
                nilable = false,
                type = "bool",
            },
        },
        synchronous = true,
        type = "event",
    },
    NAVIGATION_FRAME_CREATED = {
        cppName = "NavigationFrameCreated",
        literalName = "NAVIGATION_FRAME_CREATED",
        payload = {
            {
                name = "region",
                nilable = false,
                type = "ScriptRegion",
            },
        },
        synchronous = true,
        type = "event",
    },
    NAVIGATION_FRAME_DESTROYED = {
        cppName = "NavigationFrameDestroyed",
        literalName = "NAVIGATION_FRAME_DESTROYED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    NavigationState = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Invalid",
                value = 0,
            },
            {
                name = "Occluded",
                value = 1,
            },
            {
                name = "InRange",
                value = 2,
            },
            {
                name = "Disabled",
                value = 3,
            },
        },
    },
    WasClampedToScreen = {
        params = {},
        returns = {
            {
                name = "wasClamped",
                nilable = false,
                type = "bool",
            },
        },
        signature = "wasClamped = C_Navigation.WasClampedToScreen()",
        type = "function",
    },
})
