-- Forge_APIRef-C_DuelInfo: per-namespace API data for C_DuelInfo.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/DuelInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_DuelInfo", {
    DUEL_FINISHED = {
        cppName = "DuelFinished",
        literalName = "DUEL_FINISHED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    DUEL_INBOUNDS = {
        cppName = "DuelInbounds",
        literalName = "DUEL_INBOUNDS",
        payload = {},
        synchronous = true,
        type = "event",
    },
    DUEL_OUTOFBOUNDS = {
        cppName = "DuelOutofbounds",
        literalName = "DUEL_OUTOFBOUNDS",
        payload = {},
        synchronous = true,
        type = "event",
    },
    DUEL_REQUESTED = {
        cppName = "DuelRequested",
        literalName = "DUEL_REQUESTED",
        payload = {
            {
                name = "playerName",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    DUEL_TO_THE_DEATH_REQUESTED = {
        cppName = "DuelToTheDeathRequested",
        literalName = "DUEL_TO_THE_DEATH_REQUESTED",
        payload = {
            {
                name = "playerName",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
})
