-- Forge_APIRef-TimerunningConstants: per-namespace API data for TimerunningConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/TimerunningConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:31Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("TimerunningConstants", {
    TimerunningConsts = {
        fields = {},
        type = "structure",
    },
})
