-- Forge_APIRef-FrameAPITabardModel: per-namespace API data for FrameAPITabardModel.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/FrameAPITabardModelDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("FrameAPITabardModel", {
    GetLowerBackgroundFileName = {
        params = {},
        returns = {
            {
                name = "file",
                nilable = false,
                type = "fileID",
            },
        },
        signature = "file = FrameAPITabardModel.GetLowerBackgroundFileName()",
        type = "function",
    },
    GetLowerBorderFile = {
        params = {},
        returns = {
            {
                name = "file",
                nilable = false,
                type = "fileID",
            },
        },
        signature = "file = FrameAPITabardModel.GetLowerBorderFile()",
        type = "function",
    },
    GetLowerEmblemFile = {
        params = {},
        returns = {
            {
                name = "file",
                nilable = false,
                type = "fileID",
            },
        },
        signature = "file = FrameAPITabardModel.GetLowerEmblemFile()",
        type = "function",
    },
    GetUpperBackgroundFileName = {
        params = {},
        returns = {
            {
                name = "file",
                nilable = false,
                type = "fileID",
            },
        },
        signature = "file = FrameAPITabardModel.GetUpperBackgroundFileName()",
        type = "function",
    },
    GetUpperBorderFile = {
        params = {},
        returns = {
            {
                name = "file",
                nilable = false,
                type = "fileID",
            },
        },
        signature = "file = FrameAPITabardModel.GetUpperBorderFile()",
        type = "function",
    },
    GetUpperEmblemFile = {
        params = {},
        returns = {
            {
                name = "file",
                nilable = false,
                type = "fileID",
            },
        },
        signature = "file = FrameAPITabardModel.GetUpperEmblemFile()",
        type = "function",
    },
})
