-- Forge_APIRef-AbbreviateConfigAPI: per-namespace API data for AbbreviateConfigAPI.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/AbbreviateConfigAPIDocumentation.lua.
-- Generated 2026-05-06 13:02:25Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("AbbreviateConfigAPI", {
    GetAbbreviateNumberData = {
        params = {},
        returns = {
            {
                innerType = "NumberAbbreviationBreakpoint",
                name = "data",
                nilable = false,
                type = "table",
            },
        },
        signature = "data = AbbreviateConfigAPI.GetAbbreviateNumberData()",
        type = "function",
    },
    SetAbbreviateNumberData = {
        params = {
            {
                innerType = "NumberAbbreviationBreakpoint",
                name = "data",
                nilable = false,
                type = "table",
            },
        },
        returns = {},
        secretArguments = "NotAllowed",
        signature = "AbbreviateConfigAPI.SetAbbreviateNumberData(data)",
        type = "function",
    },
})
