-- Forge_APIRef-C_RecentAllies: per-namespace API data for C_RecentAllies.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/RecentAlliesDocumentation.lua.
-- Generated 2026-05-06 13:02:30Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_RecentAllies", {
    CanSetRecentAllyNote = {
        params = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "canSetNote",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canSetNote = C_RecentAllies.CanSetRecentAllyNote(characterGUID)",
        type = "function",
    },
    GetRecentAllies = {
        params = {},
        returns = {
            {
                innerType = "RecentAllyData",
                name = "recentAlliesData",
                nilable = false,
                type = "table",
            },
        },
        signature = "recentAlliesData = C_RecentAllies.GetRecentAllies()",
        type = "function",
    },
    GetRecentAllyByFullName = {
        params = {
            {
                name = "fullCharacterName",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "recentAllyData",
                nilable = true,
                type = "RecentAllyData",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "recentAllyData = C_RecentAllies.GetRecentAllyByFullName(fullCharacterName)",
        type = "function",
    },
    GetRecentAllyByGUID = {
        params = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "recentAllyData",
                nilable = true,
                type = "RecentAllyData",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "recentAllyData = C_RecentAllies.GetRecentAllyByGUID(characterGUID)",
        type = "function",
    },
    IsRecentAllyByFullName = {
        params = {
            {
                name = "fullCharacterName",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "isRecentAlly",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isRecentAlly = C_RecentAllies.IsRecentAllyByFullName(fullCharacterName)",
        type = "function",
    },
    IsRecentAllyByGUID = {
        params = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "isRecentAlly",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isRecentAlly = C_RecentAllies.IsRecentAllyByGUID(characterGUID)",
        type = "function",
    },
    IsRecentAllyDataReady = {
        params = {},
        returns = {
            {
                name = "isReady",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isReady = C_RecentAllies.IsRecentAllyDataReady()",
        type = "function",
    },
    IsRecentAllyPinned = {
        params = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "isPinned",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isPinned = C_RecentAllies.IsRecentAllyPinned(characterGUID)",
        type = "function",
    },
    IsSystemEnabled = {
        params = {},
        returns = {
            {
                name = "isRecentAllySystemEnabled",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isRecentAllySystemEnabled = C_RecentAllies.IsSystemEnabled()",
        type = "function",
    },
    IsSystemSupported = {
        params = {},
        returns = {
            {
                name = "isRecentAllySystemSupported",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isRecentAllySystemSupported = C_RecentAllies.IsSystemSupported()",
        type = "function",
    },
    LET_RECENT_ALLIES_SEE_LOCATION_SETTING_UPDATED = {
        cppName = "LetRecentAlliesSeeLocationSettingUpdated",
        literalName = "LET_RECENT_ALLIES_SEE_LOCATION_SETTING_UPDATED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    RECENT_ALLIES_CACHE_UPDATE = {
        cppName = "RecentAlliesCacheUpdate",
        literalName = "RECENT_ALLIES_CACHE_UPDATE",
        payload = {},
        synchronous = false,
        type = "event",
    },
    RECENT_ALLIES_DATA_READY = {
        cppName = "RecentAlliesDataReady",
        literalName = "RECENT_ALLIES_DATA_READY",
        payload = {},
        synchronous = true,
        type = "event",
    },
    RECENT_ALLIES_SYSTEM_STATUS_UPDATED = {
        cppName = "RecentAlliesSystemStatusUpdated",
        literalName = "RECENT_ALLIES_SYSTEM_STATUS_UPDATED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    RECENT_ALLY_DATA_UPDATED = {
        cppName = "RecentAllyDataUpdated",
        literalName = "RECENT_ALLY_DATA_UPDATED",
        payload = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        synchronous = true,
        type = "event",
    },
    RecentAllyCharacterData = {
        fields = {
            {
                name = "guid",
                nilable = false,
                type = "WOWGUID",
            },
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                name = "fullName",
                nilable = false,
                type = "string",
            },
            {
                name = "realmName",
                nilable = false,
                type = "string",
            },
            {
                name = "level",
                nilable = false,
                type = "number",
            },
            {
                name = "classID",
                nilable = false,
                type = "number",
            },
            {
                name = "raceID",
                nilable = false,
                type = "number",
            },
            {
                name = "sex",
                nilable = false,
                type = "UnitSex",
            },
        },
        type = "structure",
    },
    RecentAllyData = {
        fields = {
            {
                name = "stateData",
                nilable = false,
                type = "RecentAllyStateData",
            },
            {
                name = "characterData",
                nilable = false,
                type = "RecentAllyCharacterData",
            },
            {
                name = "interactionData",
                nilable = false,
                type = "RecentAllyInteractionData",
            },
        },
        type = "structure",
    },
    RecentAllyInteraction = {
        fields = {
            {
                name = "type",
                nilable = false,
                type = "RolodexType",
            },
            {
                name = "description",
                nilable = false,
                type = "cstring",
            },
            {
                name = "timestamp",
                nilable = false,
                type = "time_t",
            },
            {
                name = "contextData",
                nilable = false,
                type = "RecentAllyInteractionContextData",
            },
        },
        type = "structure",
    },
    RecentAllyInteractionContextData = {
        fields = {
            {
                name = "itemID",
                nilable = true,
                type = "number",
            },
            {
                name = "locationName",
                nilable = true,
                type = "cstring",
            },
            {
                name = "activityDifficultyID",
                nilable = true,
                type = "number",
            },
            {
                name = "activityDifficultyLevel",
                nilable = true,
                type = "number",
            },
        },
        type = "structure",
    },
    RecentAllyInteractionData = {
        fields = {
            {
                innerType = "RecentAllyInteraction",
                name = "interactions",
                nilable = false,
                type = "table",
            },
            {
                name = "note",
                nilable = true,
                type = "string",
            },
        },
        type = "structure",
    },
    RecentAllyStateData = {
        fields = {
            {
                name = "isOnline",
                nilable = false,
                type = "bool",
            },
            {
                name = "isDND",
                nilable = false,
                type = "bool",
            },
            {
                name = "isAFK",
                nilable = false,
                type = "bool",
            },
            {
                name = "pinExpirationDate",
                nilable = true,
                type = "time_t",
            },
            {
                name = "friendRequestSentThisSession",
                nilable = false,
                type = "bool",
            },
            {
                name = "currentLocation",
                nilable = true,
                type = "string",
            },
        },
        type = "structure",
    },
    SetRecentAllyNote = {
        params = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
            {
                name = "note",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_RecentAllies.SetRecentAllyNote(characterGUID, note)",
        type = "function",
    },
    SetRecentAllyPinned = {
        params = {
            {
                name = "characterGUID",
                nilable = false,
                type = "WOWGUID",
            },
            {
                name = "isPinned",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_RecentAllies.SetRecentAllyPinned(characterGUID, isPinned)",
        type = "function",
    },
    TryRequestRecentAlliesData = {
        hasRestrictions = true,
        params = {},
        returns = {},
        signature = "C_RecentAllies.TryRequestRecentAlliesData()",
        type = "function",
    },
})
