-- Forge_APIRef-C_WarbandScene: per-namespace API data for C_WarbandScene.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/WarbandSceneInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:32Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_WarbandScene", {
    GetRandomEntryID = {
        params = {},
        returns = {
            {
                name = "warbandSceneID",
                nilable = false,
                type = "number",
            },
        },
        signature = "warbandSceneID = C_WarbandScene.GetRandomEntryID()",
        type = "function",
    },
    GetWarbandSceneEntry = {
        mayReturnNothing = true,
        params = {
            {
                name = "warbandSceneID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "warbandSceneEntry",
                nilable = false,
                type = "WarbandSceneEntry",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "warbandSceneEntry = C_WarbandScene.GetWarbandSceneEntry(warbandSceneID)",
        type = "function",
    },
    HasWarbandScene = {
        params = {
            {
                name = "warbandSceneID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "owned",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "owned = C_WarbandScene.HasWarbandScene(warbandSceneID)",
        type = "function",
    },
    IsFavorite = {
        params = {
            {
                name = "warbandSceneID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "favorite",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "favorite = C_WarbandScene.IsFavorite(warbandSceneID)",
        type = "function",
    },
    NEW_WARBAND_SCENE_ADDED = {
        cppName = "NewWarbandSceneAdded",
        literalName = "NEW_WARBAND_SCENE_ADDED",
        payload = {
            {
                name = "warbandScenID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    SearchWarbandSceneEntries = {
        params = {
            {
                name = "searchParams",
                nilable = false,
                type = "WarbandSceneSearchInfo",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "matchingEntryIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "matchingEntryIDs = C_WarbandScene.SearchWarbandSceneEntries(searchParams)",
        type = "function",
    },
    SetFavorite = {
        params = {
            {
                name = "warbandSceneID",
                nilable = false,
                type = "number",
            },
            {
                name = "favorite",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_WarbandScene.SetFavorite(warbandSceneID, favorite)",
        type = "function",
    },
    WARBAND_SCENE_FAVORITES_UPDATED = {
        cppName = "WarbandSceneFavoritesUpdated",
        literalName = "WARBAND_SCENE_FAVORITES_UPDATED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    WarbandSceneEntry = {
        fields = {
            {
                default = 0,
                name = "warbandSceneID",
                nilable = false,
                type = "number",
            },
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "description",
                nilable = false,
                type = "cstring",
            },
            {
                name = "source",
                nilable = false,
                type = "cstring",
            },
            {
                name = "quality",
                nilable = false,
                type = "number",
            },
            {
                name = "textureKit",
                nilable = false,
                type = "textureKit",
            },
            {
                default = false,
                name = "isFavorite",
                nilable = false,
                type = "bool",
            },
            {
                default = false,
                name = "hasFanfare",
                nilable = false,
                type = "bool",
            },
            {
                default = 0,
                name = "sourceType",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    WarbandSceneSearchInfo = {
        fields = {
            {
                default = false,
                name = "ownedOnly",
                nilable = false,
                type = "bool",
            },
            {
                default = false,
                name = "favoritesOnly",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
})
