-- Forge_APIRef-ClubShared: per-namespace API data for ClubShared.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/ClubSharedDocumentation.lua.
-- Generated 2026-05-06 13:02:26Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("ClubShared", {
    ClubRoleIdentifier = {
        maxValue = 4,
        minValue = 1,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Owner",
                value = 1,
            },
            {
                name = "Leader",
                value = 2,
            },
            {
                name = "Moderator",
                value = 3,
            },
            {
                name = "Member",
                value = 4,
            },
        },
    },
})
