-- Forge_APIRef-SplashScreenConstants: per-namespace API data for SplashScreenConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/SplashScreenConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:31Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("SplashScreenConstants", {
    SplashScreenType = {
        maxValue = 1,
        minValue = 0,
        numValues = 2,
        type = "enum",
        values = {
            {
                name = "WhatsNew",
                value = 0,
            },
            {
                name = "SeasonRollOver",
                value = 1,
            },
        },
    },
})
