-- Forge_APIRef-GarrisonConstants: per-namespace API data for GarrisonConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/GarrisonConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("GarrisonConstants", {
    ContributionAppearanceFlags = {
        maxValue = 0,
        minValue = 0,
        numValues = 1,
        type = "enum",
        values = {
            {
                name = "TooltipUseTimeRemaining",
                value = 0,
            },
        },
    },
    ContributionState = {
        maxValue = 4,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Building",
                value = 1,
            },
            {
                name = "Active",
                value = 2,
            },
            {
                name = "UnderAttack",
                value = 3,
            },
            {
                name = "Destroyed",
                value = 4,
            },
        },
    },
    CovenantSkill = {
        maxValue = 2733,
        minValue = 2730,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Kyrian",
                value = 2730,
            },
            {
                name = "Venthyr",
                value = 2731,
            },
            {
                name = "NightFae",
                value = 2732,
            },
            {
                name = "Necrolord",
                value = 2733,
            },
        },
    },
    CovenantType = {
        maxValue = 4,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Kyrian",
                value = 1,
            },
            {
                name = "Venthyr",
                value = 2,
            },
            {
                name = "NightFae",
                value = 3,
            },
            {
                name = "Necrolord",
                value = 4,
            },
        },
    },
    FollowerAbilityCastResult = {
        maxValue = 14,
        minValue = 0,
        numValues = 15,
        type = "enum",
        values = {
            {
                name = "Success",
                value = 0,
            },
            {
                name = "Failure",
                value = 1,
            },
            {
                name = "NoPendingCast",
                value = 2,
            },
            {
                name = "InvalidTarget",
                value = 3,
            },
            {
                name = "InvalidFollowerSpell",
                value = 4,
            },
            {
                name = "RerollNotAllowed",
                value = 5,
            },
            {
                name = "SingleMissionDuration",
                value = 6,
            },
            {
                name = "MustTargetFollower",
                value = 7,
            },
            {
                name = "MustTargetTrait",
                value = 8,
            },
            {
                name = "InvalidFollowerType",
                value = 9,
            },
            {
                name = "MustBeUnique",
                value = 10,
            },
            {
                name = "CannotTargetLimitedUseFollower",
                value = 11,
            },
            {
                name = "MustTargetLimitedUseFollower",
                value = 12,
            },
            {
                name = "AlreadyAtMaxDurability",
                value = 13,
            },
            {
                name = "CannotTargetNonAutoMissionFollower",
                value = 14,
            },
        },
    },
    GarrAutoBoardIndex = {
        maxValue = 12,
        minValue = -1,
        numValues = 14,
        type = "enum",
        values = {
            {
                name = "None",
                value = -1,
            },
            {
                name = "AllyLeftBack",
                value = 0,
            },
            {
                name = "AllyRightBack",
                value = 1,
            },
            {
                name = "AllyLeftFront",
                value = 2,
            },
            {
                name = "AllyCenterFront",
                value = 3,
            },
            {
                name = "AllyRightFront",
                value = 4,
            },
            {
                name = "EnemyLeftFront",
                value = 5,
            },
            {
                name = "EnemyCenterLeftFront",
                value = 6,
            },
            {
                name = "EnemyCenterRightFront",
                value = 7,
            },
            {
                name = "EnemyRightFront",
                value = 8,
            },
            {
                name = "EnemyLeftBack",
                value = 9,
            },
            {
                name = "EnemyCenterLeftBack",
                value = 10,
            },
            {
                name = "EnemyCenterRightBack",
                value = 11,
            },
            {
                name = "EnemyRightBack",
                value = 12,
            },
        },
    },
    GarrAutoCombatSpellTutorialFlag = {
        maxValue = 4,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Single",
                value = 1,
            },
            {
                name = "Column",
                value = 2,
            },
            {
                name = "Row",
                value = 3,
            },
            {
                name = "All",
                value = 4,
            },
        },
    },
    GarrAutoCombatTutorial = {
        maxValue = 1024,
        minValue = 1,
        numValues = 11,
        type = "enum",
        values = {
            {
                name = "SelectMission",
                value = 1,
            },
            {
                name = "PlaceCompanion",
                value = 2,
            },
            {
                name = "HealCompanion",
                value = 4,
            },
            {
                name = "LevelHeal",
                value = 8,
            },
            {
                name = "BeneficialEffect",
                value = 16,
            },
            {
                name = "AttackSingle",
                value = 32,
            },
            {
                name = "AttackColumn",
                value = 64,
            },
            {
                name = "AttackRow",
                value = 128,
            },
            {
                name = "AttackAll",
                value = 256,
            },
            {
                name = "TroopTutorial",
                value = 512,
            },
            {
                name = "EnvironmentalEffect",
                value = 1024,
            },
        },
    },
    GarrAutoCombatantRole = {
        maxValue = 5,
        minValue = 0,
        numValues = 6,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Melee",
                value = 1,
            },
            {
                name = "RangedPhysical",
                value = 2,
            },
            {
                name = "RangedMagic",
                value = 3,
            },
            {
                name = "HealSupport",
                value = 4,
            },
            {
                name = "Tank",
                value = 5,
            },
        },
    },
    GarrAutoEventFlags = {
        maxValue = 4,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "AutoAttack",
                value = 1,
            },
            {
                name = "Passive",
                value = 2,
            },
            {
                name = "Environment",
                value = 4,
            },
        },
    },
    GarrAutoMissionEventType = {
        maxValue = 9,
        minValue = 0,
        numValues = 10,
        type = "enum",
        values = {
            {
                name = "MeleeDamage",
                value = 0,
            },
            {
                name = "RangeDamage",
                value = 1,
            },
            {
                name = "SpellMeleeDamage",
                value = 2,
            },
            {
                name = "SpellRangeDamage",
                value = 3,
            },
            {
                name = "Heal",
                value = 4,
            },
            {
                name = "PeriodicDamage",
                value = 5,
            },
            {
                name = "PeriodicHeal",
                value = 6,
            },
            {
                name = "ApplyAura",
                value = 7,
            },
            {
                name = "RemoveAura",
                value = 8,
            },
            {
                name = "Died",
                value = 9,
            },
        },
    },
    GarrAutoPreviewTargetType = {
        maxValue = 8,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Damage",
                value = 1,
            },
            {
                name = "Heal",
                value = 2,
            },
            {
                name = "Buff",
                value = 4,
            },
            {
                name = "Debuff",
                value = 8,
            },
        },
    },
    GarrFollowerMissionCompleteState = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Alive",
                value = 0,
            },
            {
                name = "KilledByMissionFailure",
                value = 1,
            },
            {
                name = "SavedByPreventDeath",
                value = 2,
            },
            {
                name = "OutOfDurability",
                value = 3,
            },
        },
    },
    GarrFollowerQuality = {
        maxValue = 6,
        minValue = 0,
        numValues = 7,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Common",
                value = 1,
            },
            {
                name = "Uncommon",
                value = 2,
            },
            {
                name = "Rare",
                value = 3,
            },
            {
                name = "Epic",
                value = 4,
            },
            {
                name = "Legendary",
                value = 5,
            },
            {
                name = "Title",
                value = 6,
            },
        },
    },
    GarrTalentCostType = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Initial",
                value = 0,
            },
            {
                name = "Respec",
                value = 1,
            },
            {
                name = "MakePermanent",
                value = 2,
            },
            {
                name = "TreeReset",
                value = 3,
            },
        },
    },
    GarrTalentFeatureSubtype = {
        maxValue = 4,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "Generic",
                value = 0,
            },
            {
                name = "Bastion",
                value = 1,
            },
            {
                name = "Revendreth",
                value = 2,
            },
            {
                name = "Ardenweald",
                value = 3,
            },
            {
                name = "Maldraxxus",
                value = 4,
            },
        },
    },
    GarrTalentFeatureType = {
        maxValue = 8,
        minValue = 0,
        numValues = 9,
        type = "enum",
        values = {
            {
                name = "Generic",
                value = 0,
            },
            {
                name = "AnimaDiversion",
                value = 1,
            },
            {
                name = "TravelPortals",
                value = 2,
            },
            {
                name = "Adventures",
                value = 3,
            },
            {
                name = "ReservoirUpgrades",
                value = 4,
            },
            {
                name = "SanctumUnique",
                value = 5,
            },
            {
                name = "SoulBinds",
                value = 6,
            },
            {
                name = "AnimaDiversionMap",
                value = 7,
            },
            {
                name = "Cyphers",
                value = 8,
            },
        },
    },
    GarrTalentResearchCostSource = {
        maxValue = 1,
        minValue = 0,
        numValues = 2,
        type = "enum",
        values = {
            {
                name = "Talent",
                value = 0,
            },
            {
                name = "Tree",
                value = 1,
            },
        },
    },
    GarrTalentSocketType = {
        maxValue = 2,
        minValue = 0,
        numValues = 3,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Spell",
                value = 1,
            },
            {
                name = "Conduit",
                value = 2,
            },
        },
    },
    GarrTalentTreeType = {
        maxValue = 1,
        minValue = 0,
        numValues = 2,
        type = "enum",
        values = {
            {
                name = "Tiers",
                value = 0,
            },
            {
                name = "Classic",
                value = 1,
            },
        },
    },
    GarrTalentType = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Standard",
                value = 0,
            },
            {
                name = "Minor",
                value = 1,
            },
            {
                name = "Major",
                value = 2,
            },
            {
                name = "Socket",
                value = 3,
            },
        },
    },
    GarrTalentUI = {
        maxValue = 3,
        minValue = 0,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Generic",
                value = 0,
            },
            {
                name = "CovenantSanctum",
                value = 1,
            },
            {
                name = "SoulBinds",
                value = 2,
            },
            {
                name = "AnimaDiversionMap",
                value = 3,
            },
        },
    },
    GarrisonTalentAvailability = {
        maxValue = 8,
        minValue = 0,
        numValues = 9,
        type = "enum",
        values = {
            {
                name = "Available",
                value = 0,
            },
            {
                name = "Unavailable",
                value = 1,
            },
            {
                name = "UnavailableAnotherIsResearching",
                value = 2,
            },
            {
                name = "UnavailableNotEnoughResources",
                value = 3,
            },
            {
                name = "UnavailableNotEnoughGold",
                value = 4,
            },
            {
                name = "UnavailableTierUnavailable",
                value = 5,
            },
            {
                name = "UnavailablePlayerCondition",
                value = 6,
            },
            {
                name = "UnavailableAlreadyHave",
                value = 7,
            },
            {
                name = "UnavailableRequiresPrerequisiteTalent",
                value = 8,
            },
        },
    },
})
