-- Forge_APIRef-C_Mail: per-namespace API data for C_Mail.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/MailInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_Mail", {
    CLOSE_INBOX_ITEM = {
        cppName = "CloseInboxItem",
        literalName = "CLOSE_INBOX_ITEM",
        payload = {
            {
                name = "mailIndex",
                nilable = false,
                type = "luaIndex",
            },
        },
        synchronous = true,
        type = "event",
    },
    CanCheckInbox = {
        params = {},
        returns = {
            {
                name = "canCheckInbox",
                nilable = false,
                type = "bool",
            },
            {
                name = "secondsUntilAllowed",
                nilable = false,
                type = "number",
            },
        },
        signature = "canCheckInbox, secondsUntilAllowed = C_Mail.CanCheckInbox()",
        type = "function",
    },
    GetCraftingOrderMailInfo = {
        params = {
            {
                name = "inboxIndex",
                nilable = false,
                type = "luaIndex",
            },
        },
        returns = {
            {
                name = "info",
                nilable = true,
                type = "CraftingOrderMailInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "info = C_Mail.GetCraftingOrderMailInfo(inboxIndex)",
        type = "function",
    },
    HasInboxMoney = {
        params = {
            {
                name = "inboxIndex",
                nilable = false,
                type = "luaIndex",
            },
        },
        returns = {
            {
                name = "inboxItemHasMoneyAttached",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "inboxItemHasMoneyAttached = C_Mail.HasInboxMoney(inboxIndex)",
        type = "function",
    },
    IsCommandPending = {
        params = {},
        returns = {
            {
                name = "isCommandPending",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isCommandPending = C_Mail.IsCommandPending()",
        type = "function",
    },
    MAIL_CLOSED = {
        cppName = "MailClosed",
        literalName = "MAIL_CLOSED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    MAIL_FAILED = {
        cppName = "MailFailed",
        literalName = "MAIL_FAILED",
        payload = {
            {
                name = "itemID",
                nilable = true,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    MAIL_INBOX_UPDATE = {
        cppName = "MailInboxUpdate",
        literalName = "MAIL_INBOX_UPDATE",
        payload = {},
        synchronous = true,
        type = "event",
    },
    MAIL_LOCK_SEND_ITEMS = {
        cppName = "MailLockSendItems",
        literalName = "MAIL_LOCK_SEND_ITEMS",
        payload = {
            {
                name = "attachSlot",
                nilable = false,
                type = "luaIndex",
            },
            {
                name = "itemLink",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    MAIL_SEND_INFO_UPDATE = {
        cppName = "MailSendInfoUpdate",
        literalName = "MAIL_SEND_INFO_UPDATE",
        payload = {},
        synchronous = true,
        type = "event",
    },
    MAIL_SEND_SUCCESS = {
        cppName = "MailSendSuccess",
        literalName = "MAIL_SEND_SUCCESS",
        payload = {},
        synchronous = true,
        type = "event",
    },
    MAIL_SHOW = {
        cppName = "MailShow",
        literalName = "MAIL_SHOW",
        payload = {},
        synchronous = true,
        type = "event",
    },
    MAIL_SUCCESS = {
        cppName = "MailSuccess",
        literalName = "MAIL_SUCCESS",
        payload = {
            {
                name = "itemID",
                nilable = true,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    MAIL_UNLOCK_SEND_ITEMS = {
        cppName = "MailUnlockSendItems",
        literalName = "MAIL_UNLOCK_SEND_ITEMS",
        payload = {},
        synchronous = true,
        type = "event",
    },
    SEND_MAIL_COD_CHANGED = {
        cppName = "SendMailCodChanged",
        literalName = "SEND_MAIL_COD_CHANGED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    SEND_MAIL_MONEY_CHANGED = {
        cppName = "SendMailMoneyChanged",
        literalName = "SEND_MAIL_MONEY_CHANGED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    SetOpeningAll = {
        params = {
            {
                name = "openingAll",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Mail.SetOpeningAll(openingAll)",
        type = "function",
    },
    UPDATE_PENDING_MAIL = {
        cppName = "UpdatePendingMail",
        literalName = "UPDATE_PENDING_MAIL",
        payload = {},
        synchronous = true,
        type = "event",
    },
})
