-- Forge_APIRef-TargetScript: per-namespace API data for TargetScript.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/TargetScriptDocumentation.lua.
-- Generated 2026-05-06 13:02:31Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("TargetScript", {
    AssistUnit = {
        hasRestrictions = true,
        params = {
            {
                default = "",
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                default = false,
                name = "exactMatch",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.AssistUnit(name, exactMatch)",
        type = "function",
    },
    AttackTarget = {
        params = {},
        returns = {},
        signature = "TargetScript.AttackTarget()",
        type = "function",
    },
    ClearFocus = {
        params = {},
        returns = {},
        signature = "TargetScript.ClearFocus()",
        type = "function",
    },
    ClearTarget = {
        params = {},
        returns = {
            {
                name = "willMakeChange",
                nilable = false,
                type = "bool",
            },
        },
        signature = "willMakeChange = TargetScript.ClearTarget()",
        type = "function",
    },
    FocusUnit = {
        hasRestrictions = true,
        params = {
            {
                default = "",
                name = "name",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.FocusUnit(name)",
        type = "function",
    },
    IsTargetLoose = {
        params = {},
        returns = {
            {
                name = "isTargetLoose",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isTargetLoose = TargetScript.IsTargetLoose()",
        type = "function",
    },
    TargetDirectionEnemy = {
        params = {
            {
                name = "facing",
                nilable = false,
                type = "number",
            },
            {
                name = "coneAngle",
                nilable = true,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetDirectionEnemy(facing, coneAngle)",
        type = "function",
    },
    TargetDirectionFinished = {
        params = {},
        returns = {},
        signature = "TargetScript.TargetDirectionFinished()",
        type = "function",
    },
    TargetDirectionFriend = {
        params = {
            {
                name = "facing",
                nilable = false,
                type = "number",
            },
            {
                name = "coneAngle",
                nilable = true,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetDirectionFriend(facing, coneAngle)",
        type = "function",
    },
    TargetLastEnemy = {
        params = {},
        returns = {},
        signature = "TargetScript.TargetLastEnemy()",
        type = "function",
    },
    TargetLastFriend = {
        params = {},
        returns = {},
        signature = "TargetScript.TargetLastFriend()",
        type = "function",
    },
    TargetLastTarget = {
        params = {},
        returns = {},
        signature = "TargetScript.TargetLastTarget()",
        type = "function",
    },
    TargetNearest = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearest(reverse)",
        type = "function",
    },
    TargetNearestEnemy = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearestEnemy(reverse)",
        type = "function",
    },
    TargetNearestEnemyPlayer = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearestEnemyPlayer(reverse)",
        type = "function",
    },
    TargetNearestFriend = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearestFriend(reverse)",
        type = "function",
    },
    TargetNearestFriendPlayer = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearestFriendPlayer(reverse)",
        type = "function",
    },
    TargetNearestPartyMember = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearestPartyMember(reverse)",
        type = "function",
    },
    TargetNearestRaidMember = {
        params = {
            {
                default = false,
                name = "reverse",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetNearestRaidMember(reverse)",
        type = "function",
    },
    TargetPriorityHighlightEnd = {
        params = {},
        returns = {},
        signature = "TargetScript.TargetPriorityHighlightEnd()",
        type = "function",
    },
    TargetPriorityHighlightStart = {
        params = {
            {
                default = false,
                name = "useStartDelay",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetPriorityHighlightStart(useStartDelay)",
        type = "function",
    },
    TargetToggle = {
        hasRestrictions = true,
        params = {},
        returns = {},
        signature = "TargetScript.TargetToggle()",
        type = "function",
    },
    TargetUnit = {
        hasRestrictions = true,
        params = {
            {
                default = "",
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                default = false,
                name = "exactMatch",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "TargetScript.TargetUnit(name, exactMatch)",
        type = "function",
    },
})
