-- Forge_APIRef-CommentatorShared: per-namespace API data for CommentatorShared.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/CommentatorSharedDocumentation.lua.
-- Generated 2026-05-06 13:02:26Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("CommentatorShared", {
    TrackedSpellCategory = {
        maxValue = 4,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Offensive",
                value = 1,
            },
            {
                name = "Defensive",
                value = 2,
            },
            {
                name = "Debuff",
                value = 3,
            },
            {
                name = "RacialAbility",
                value = 4,
            },
        },
    },
})
