-- Forge_APIRef-C_HousingCleanupMode: per-namespace API data for C_HousingCleanupMode.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/HousingCleanupModeUIDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_HousingCleanupMode", {
    GetHoveredDecorInfo = {
        params = {},
        returns = {
            {
                name = "info",
                nilable = true,
                type = "HousingDecorInstanceInfo",
            },
        },
        signature = "info = C_HousingCleanupMode.GetHoveredDecorInfo()",
        type = "function",
    },
    HOUSING_CLEANUP_MODE_HOVERED_TARGET_CHANGED = {
        cppName = "HousingCleanupModeHoveredTargetChanged",
        literalName = "HOUSING_CLEANUP_MODE_HOVERED_TARGET_CHANGED",
        payload = {
            {
                name = "hasHoveredTarget",
                nilable = false,
                type = "bool",
            },
            {
                name = "targetType",
                nilable = false,
                type = "HousingCleanupModeTargetType",
            },
        },
        synchronous = true,
        type = "event",
    },
    HOUSING_CLEANUP_MODE_TARGET_SELECTED = {
        cppName = "HousingCleanupModeTargetSelected",
        literalName = "HOUSING_CLEANUP_MODE_TARGET_SELECTED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    HousingCleanupModeTargetType = {
        maxValue = 2,
        minValue = 0,
        numValues = 3,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Decor",
                value = 1,
            },
            {
                name = "HouseExterior",
                value = 2,
            },
        },
    },
    IsHoveringDecor = {
        params = {},
        returns = {
            {
                name = "isHoveringDecor",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isHoveringDecor = C_HousingCleanupMode.IsHoveringDecor()",
        type = "function",
    },
    RemoveSelectedDecor = {
        params = {},
        returns = {},
        signature = "C_HousingCleanupMode.RemoveSelectedDecor()",
        type = "function",
    },
})
