-- Forge_APIRef-C_ItemUpgrade: per-namespace API data for C_ItemUpgrade.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/ItemUpgradeDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_ItemUpgrade", {
    CanUpgradeItem = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "baseItem",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isValid",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isValid = C_ItemUpgrade.CanUpgradeItem(baseItem)",
        type = "function",
    },
    ClearItemUpgrade = {
        params = {},
        returns = {},
        signature = "C_ItemUpgrade.ClearItemUpgrade()",
        type = "function",
    },
    CloseItemUpgrade = {
        params = {},
        returns = {},
        signature = "C_ItemUpgrade.CloseItemUpgrade()",
        type = "function",
    },
    GetHighWatermarkForItem = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "characterHighWatermark",
                nilable = false,
                type = "number",
            },
            {
                name = "accountHighWatermark",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "characterHighWatermark, accountHighWatermark = C_ItemUpgrade.GetHighWatermarkForItem(itemInfo)",
        type = "function",
    },
    GetHighWatermarkForSlot = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemRedundancySlot",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "characterHighWatermark",
                nilable = false,
                type = "number",
            },
            {
                name = "accountHighWatermark",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "characterHighWatermark, accountHighWatermark = C_ItemUpgrade.GetHighWatermarkForSlot(itemRedundancySlot)",
        type = "function",
    },
    GetHighWatermarkSlotForItem = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemRedundancySlot",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemRedundancySlot = C_ItemUpgrade.GetHighWatermarkSlotForItem(itemInfo)",
        type = "function",
    },
    GetItemHyperlink = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "link",
                nilable = false,
                type = "cstring",
            },
        },
        signature = "link = C_ItemUpgrade.GetItemHyperlink()",
        type = "function",
    },
    GetItemUpgradeCurrentLevel = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "itemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "isPvpItemLevel",
                nilable = false,
                type = "bool",
            },
        },
        signature = "itemLevel, isPvpItemLevel = C_ItemUpgrade.GetItemUpgradeCurrentLevel()",
        type = "function",
    },
    GetItemUpgradeEffect = {
        mayReturnNothing = true,
        params = {
            {
                name = "effectIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "numUpgradeLevels",
                nilable = true,
                type = "number",
            },
        },
        returns = {
            {
                name = "outBaseEffect",
                nilable = false,
                type = "string",
            },
            {
                name = "outUpgradedEffect",
                nilable = false,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "outBaseEffect, outUpgradedEffect = C_ItemUpgrade.GetItemUpgradeEffect(effectIndex, numUpgradeLevels)",
        type = "function",
    },
    GetItemUpgradeItemInfo = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemUpgradeItemInfo",
            },
        },
        signature = "itemInfo = C_ItemUpgrade.GetItemUpgradeItemInfo()",
        type = "function",
    },
    GetItemUpgradePvpItemLevelDeltaValues = {
        mayReturnNothing = true,
        params = {
            {
                name = "numUpgradeLevels",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "currentPvPItemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "upgradedPvPItemLevel",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "currentPvPItemLevel, upgradedPvPItemLevel = C_ItemUpgrade.GetItemUpgradePvpItemLevelDeltaValues(numUpgradeLevels)",
        type = "function",
    },
    GetNumItemUpgradeEffects = {
        params = {},
        returns = {
            {
                name = "numItemUpgradeEffects",
                nilable = false,
                type = "number",
            },
        },
        signature = "numItemUpgradeEffects = C_ItemUpgrade.GetNumItemUpgradeEffects()",
        type = "function",
    },
    ITEM_UPGRADE_FAILED = {
        cppName = "ItemUpgradeFailed",
        literalName = "ITEM_UPGRADE_FAILED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    ITEM_UPGRADE_MASTER_SET_ITEM = {
        cppName = "ItemUpgradeMasterSetItem",
        literalName = "ITEM_UPGRADE_MASTER_SET_ITEM",
        payload = {},
        synchronous = true,
        type = "event",
    },
    ITEM_UPGRADE_MASTER_UPDATE = {
        cppName = "ItemUpgradeMasterUpdate",
        literalName = "ITEM_UPGRADE_MASTER_UPDATE",
        payload = {},
        synchronous = true,
        type = "event",
    },
    IsItemBound = {
        params = {},
        returns = {
            {
                name = "isBound",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isBound = C_ItemUpgrade.IsItemBound()",
        type = "function",
    },
    ItemUpgradeCostDiscountInfo = {
        fields = {
            {
                name = "isDiscounted",
                nilable = false,
                type = "bool",
            },
            {
                name = "discountHighWatermark",
                nilable = false,
                type = "number",
            },
            {
                name = "isPartialTwoHandDiscount",
                nilable = false,
                type = "bool",
            },
            {
                name = "isAccountWideDiscount",
                nilable = false,
                type = "bool",
            },
            {
                name = "doesCurrentCharacterMeetHighWatermark",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    ItemUpgradeCurrencyCost = {
        fields = {
            {
                name = "cost",
                nilable = false,
                type = "number",
            },
            {
                name = "currencyID",
                nilable = false,
                type = "number",
            },
            {
                name = "discountInfo",
                nilable = false,
                type = "ItemUpgradeCostDiscountInfo",
            },
        },
        type = "structure",
    },
    ItemUpgradeItemCost = {
        fields = {
            {
                name = "cost",
                nilable = false,
                type = "number",
            },
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "discountInfo",
                nilable = false,
                type = "ItemUpgradeCostDiscountInfo",
            },
        },
        type = "structure",
    },
    ItemUpgradeItemInfo = {
        fields = {
            {
                name = "iconID",
                nilable = false,
                type = "number",
            },
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                name = "itemUpgradeable",
                nilable = false,
                type = "bool",
            },
            {
                name = "displayQuality",
                nilable = false,
                type = "number",
            },
            {
                name = "highWatermarkSlot",
                nilable = false,
                type = "number",
            },
            {
                name = "currUpgrade",
                nilable = false,
                type = "number",
            },
            {
                name = "maxUpgrade",
                nilable = false,
                type = "number",
            },
            {
                name = "minItemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "maxItemLevel",
                nilable = false,
                type = "number",
            },
            {
                innerType = "ItemUpgradeLevelInfo",
                name = "upgradeLevelInfos",
                nilable = false,
                type = "table",
            },
            {
                name = "customUpgradeString",
                nilable = true,
                type = "string",
            },
            {
                innerType = "ItemUpgradeSeasonalCostType",
                name = "upgradeCostTypesForSeason",
                nilable = false,
                type = "table",
            },
        },
        type = "structure",
    },
    ItemUpgradeLevelInfo = {
        fields = {
            {
                name = "upgradeLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "displayQuality",
                nilable = false,
                type = "number",
            },
            {
                name = "itemLevelIncrement",
                nilable = false,
                type = "number",
            },
            {
                innerType = "ItemUpgradeStat",
                name = "levelStats",
                nilable = false,
                type = "table",
            },
            {
                innerType = "ItemUpgradeCurrencyCost",
                name = "currencyCostsToUpgrade",
                nilable = false,
                type = "table",
            },
            {
                innerType = "ItemUpgradeItemCost",
                name = "itemCostsToUpgrade",
                nilable = false,
                type = "table",
            },
            {
                name = "moneyCost",
                nilable = true,
                type = "WOWMONEY",
            },
            {
                name = "failureMessage",
                nilable = true,
                type = "string",
            },
        },
        type = "structure",
    },
    ItemUpgradeSeasonalCostType = {
        desc = "Costs are made up of either an Item OR a Currency, so either itemID or currencyID will be nil",
        fields = {
            {
                name = "itemID",
                nilable = true,
                type = "number",
            },
            {
                name = "currencyID",
                nilable = true,
                type = "number",
            },
            {
                name = "orderIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "sourceString",
                nilable = true,
                type = "string",
            },
        },
        type = "structure",
    },
    ItemUpgradeStat = {
        fields = {
            {
                name = "displayString",
                nilable = false,
                type = "string",
            },
            {
                name = "statValue",
                nilable = false,
                type = "number",
            },
            {
                name = "active",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    SetItemUpgradeFromCursorItem = {
        params = {},
        returns = {},
        signature = "C_ItemUpgrade.SetItemUpgradeFromCursorItem()",
        type = "function",
    },
    SetItemUpgradeFromLocation = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemToSet",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_ItemUpgrade.SetItemUpgradeFromLocation(itemToSet)",
        type = "function",
    },
    UpgradeItem = {
        params = {
            {
                default = 1,
                name = "numUpgrades",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_ItemUpgrade.UpgradeItem(numUpgrades)",
        type = "function",
    },
})
