-- Forge_APIRef-UIWidgetManagerShared: per-namespace API data for UIWidgetManagerShared.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/UIWidgetManagerSharedDocumentation.lua.
-- Generated 2026-05-06 13:02:32Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("UIWidgetManagerShared", {
    MapIconUIWidgetSetType = {
        maxValue = 2,
        minValue = 0,
        numValues = 3,
        type = "enum",
        values = {
            {
                name = "Tooltip",
                value = 0,
            },
            {
                name = "BehindIcon",
                value = 1,
            },
            {
                name = "AdventureMapDetails",
                value = 2,
            },
        },
    },
    SpellDisplayBorderColor = {
        maxValue = 8,
        minValue = 0,
        numValues = 9,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Black",
                value = 1,
            },
            {
                name = "White",
                value = 2,
            },
            {
                name = "Red",
                value = 3,
            },
            {
                name = "Yellow",
                value = 4,
            },
            {
                name = "Orange",
                value = 5,
            },
            {
                name = "Purple",
                value = 6,
            },
            {
                name = "Green",
                value = 7,
            },
            {
                name = "Blue",
                value = 8,
            },
        },
    },
    UIWidgetFlag = {
        maxValue = 1,
        minValue = 1,
        numValues = 1,
        type = "enum",
        values = {
            {
                name = "UniversalWidget",
                value = 1,
            },
        },
    },
    UIWidgetHorizontalDirection = {
        maxValue = 1,
        minValue = 0,
        numValues = 2,
        type = "enum",
        values = {
            {
                name = "LeftToRight",
                value = 0,
            },
            {
                name = "RightToLeft",
                value = 1,
            },
        },
    },
    UIWidgetLayoutDirection = {
        maxValue = 4,
        minValue = 0,
        numValues = 5,
        type = "enum",
        values = {
            {
                name = "Default",
                value = 0,
            },
            {
                name = "Vertical",
                value = 1,
            },
            {
                name = "Horizontal",
                value = 2,
            },
            {
                name = "Overlap",
                value = 3,
            },
            {
                name = "HorizontalForceNewRow",
                value = 4,
            },
        },
    },
    UIWidgetModelSceneLayer = {
        maxValue = 2,
        minValue = 0,
        numValues = 3,
        type = "enum",
        values = {
            {
                name = "None",
                value = 0,
            },
            {
                name = "Front",
                value = 1,
            },
            {
                name = "Back",
                value = 2,
            },
        },
    },
    UIWidgetScale = {
        maxValue = 15,
        minValue = 0,
        numValues = 16,
        type = "enum",
        values = {
            {
                name = "OneHundred",
                value = 0,
            },
            {
                name = "Ninty",
                value = 1,
            },
            {
                name = "Eighty",
                value = 2,
            },
            {
                name = "Seventy",
                value = 3,
            },
            {
                name = "Sixty",
                value = 4,
            },
            {
                name = "Fifty",
                value = 5,
            },
            {
                name = "OneHundredTen",
                value = 6,
            },
            {
                name = "OneHundredTwenty",
                value = 7,
            },
            {
                name = "OneHundredThirty",
                value = 8,
            },
            {
                name = "OneHundredForty",
                value = 9,
            },
            {
                name = "OneHundredFifty",
                value = 10,
            },
            {
                name = "OneHundredSixty",
                value = 11,
            },
            {
                name = "OneHundredSeventy",
                value = 12,
            },
            {
                name = "OneHundredEighty",
                value = 13,
            },
            {
                name = "OneHundredNinety",
                value = 14,
            },
            {
                name = "TwoHundred",
                value = 15,
            },
        },
    },
    UIWidgetSetLayoutDirection = {
        maxValue = 2,
        minValue = 0,
        numValues = 3,
        type = "enum",
        values = {
            {
                name = "Vertical",
                value = 0,
            },
            {
                name = "Horizontal",
                value = 1,
            },
            {
                name = "Overlap",
                value = 2,
            },
        },
    },
    UIWidgetVisualizationType = {
        maxValue = 31,
        minValue = 0,
        numValues = 32,
        type = "enum",
        values = {
            {
                name = "IconAndText",
                value = 0,
            },
            {
                name = "CaptureBar",
                value = 1,
            },
            {
                name = "StatusBar",
                value = 2,
            },
            {
                name = "DoubleStatusBar",
                value = 3,
            },
            {
                name = "IconTextAndBackground",
                value = 4,
            },
            {
                name = "DoubleIconAndText",
                value = 5,
            },
            {
                name = "StackedResourceTracker",
                value = 6,
            },
            {
                name = "IconTextAndCurrencies",
                value = 7,
            },
            {
                name = "TextWithState",
                value = 8,
            },
            {
                name = "HorizontalCurrencies",
                value = 9,
            },
            {
                name = "BulletTextList",
                value = 10,
            },
            {
                name = "ScenarioHeaderCurrenciesAndBackground",
                value = 11,
            },
            {
                name = "TextureAndText",
                value = 12,
            },
            {
                name = "SpellDisplay",
                value = 13,
            },
            {
                name = "DoubleStateIconRow",
                value = 14,
            },
            {
                name = "TextureAndTextRow",
                value = 15,
            },
            {
                name = "ZoneControl",
                value = 16,
            },
            {
                name = "CaptureZone",
                value = 17,
            },
            {
                name = "TextureWithAnimation",
                value = 18,
            },
            {
                name = "DiscreteProgressSteps",
                value = 19,
            },
            {
                name = "ScenarioHeaderTimer",
                value = 20,
            },
            {
                name = "TextColumnRow",
                value = 21,
            },
            {
                name = "Spacer",
                value = 22,
            },
            {
                name = "UnitPowerBar",
                value = 23,
            },
            {
                name = "FillUpFrames",
                value = 24,
            },
            {
                name = "TextWithSubtext",
                value = 25,
            },
            {
                name = "MapPinAnimation",
                value = 26,
            },
            {
                name = "ItemDisplay",
                value = 27,
            },
            {
                name = "TugOfWar",
                value = 28,
            },
            {
                name = "ScenarioHeaderDelves",
                value = 29,
            },
            {
                name = "ButtonHeader",
                value = 30,
            },
            {
                name = "PreyHuntProgress",
                value = 31,
            },
        },
    },
})
