-- Forge_APIRef-C_PlayerInteractionManager: per-namespace API data for C_PlayerInteractionManager.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/PlayerInteractionManagerDocumentation.lua.
-- Generated 2026-05-06 13:02:29Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_PlayerInteractionManager", {
    ClearInteraction = {
        params = {
            {
                name = "type",
                nilable = true,
                type = "PlayerInteractionType",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_PlayerInteractionManager.ClearInteraction(type)",
        type = "function",
    },
    ConfirmationInteraction = {
        params = {
            {
                name = "type",
                nilable = true,
                type = "PlayerInteractionType",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_PlayerInteractionManager.ConfirmationInteraction(type)",
        type = "function",
    },
    InteractUnit = {
        hasRestrictions = true,
        params = {
            {
                name = "unit",
                nilable = false,
                type = "string",
            },
            {
                default = false,
                name = "exactMatch",
                nilable = false,
                type = "bool",
            },
            {
                default = true,
                name = "looseTargeting",
                nilable = false,
                type = "bool",
            },
        },
        returns = {
            {
                name = "success",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "success = C_PlayerInteractionManager.InteractUnit(unit, exactMatch, looseTargeting)",
        type = "function",
    },
    IsInteractingWithNpcOfType = {
        params = {
            {
                name = "type",
                nilable = false,
                type = "PlayerInteractionType",
            },
        },
        returns = {
            {
                name = "interacting",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "interacting = C_PlayerInteractionManager.IsInteractingWithNpcOfType(type)",
        type = "function",
    },
    IsReplacingUnit = {
        params = {},
        returns = {
            {
                name = "replacing",
                nilable = false,
                type = "bool",
            },
        },
        signature = "replacing = C_PlayerInteractionManager.IsReplacingUnit()",
        type = "function",
    },
    IsValidNPCInteraction = {
        params = {
            {
                name = "type",
                nilable = false,
                type = "PlayerInteractionType",
            },
        },
        returns = {
            {
                name = "isValidInteraction",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isValidInteraction = C_PlayerInteractionManager.IsValidNPCInteraction(type)",
        type = "function",
    },
    PLAYER_INTERACTION_MANAGER_FRAME_HIDE = {
        cppName = "PlayerInteractionManagerFrameHide",
        literalName = "PLAYER_INTERACTION_MANAGER_FRAME_HIDE",
        payload = {
            {
                name = "type",
                nilable = false,
                type = "PlayerInteractionType",
            },
        },
        synchronous = true,
        type = "event",
    },
    PLAYER_INTERACTION_MANAGER_FRAME_SHOW = {
        cppName = "PlayerInteractionManagerFrameShow",
        literalName = "PLAYER_INTERACTION_MANAGER_FRAME_SHOW",
        payload = {
            {
                name = "type",
                nilable = false,
                type = "PlayerInteractionType",
            },
        },
        synchronous = true,
        type = "event",
    },
    ReopenInteraction = {
        hasRestrictions = true,
        params = {},
        returns = {},
        signature = "C_PlayerInteractionManager.ReopenInteraction()",
        type = "function",
    },
})
