-- Forge_APIRef-C_GlyphInfo: per-namespace API data for C_GlyphInfo.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/GlyphInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_GlyphInfo", {
    ACTIVATE_GLYPH = {
        cppName = "ActivateGlyph",
        literalName = "ACTIVATE_GLYPH",
        payload = {
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    CANCEL_GLYPH_CAST = {
        cppName = "CancelGlyphCast",
        literalName = "CANCEL_GLYPH_CAST",
        payload = {},
        synchronous = true,
        type = "event",
    },
    USE_GLYPH = {
        cppName = "UseGlyph",
        literalName = "USE_GLYPH",
        payload = {
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
})
