-- Forge_APIRef-C_LiveEvent: per-namespace API data for C_LiveEvent.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/LiveEventDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_LiveEvent", {
    OnLiveEventBannerClicked = {
        hasRestrictions = true,
        params = {
            {
                name = "timerunningSeasonID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_LiveEvent.OnLiveEventBannerClicked(timerunningSeasonID)",
        type = "function",
    },
    OnLiveEventPopupClicked = {
        hasRestrictions = true,
        params = {
            {
                name = "timerunningSeasonID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_LiveEvent.OnLiveEventPopupClicked(timerunningSeasonID)",
        type = "function",
    },
})
