-- Forge_APIRef-SimpleEditBoxAPI: per-namespace API data for SimpleEditBoxAPI.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/SimpleEditBoxAPIDocumentation.lua.
-- Generated 2026-05-06 13:02:30Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("SimpleEditBoxAPI", {
    AddHistoryLine = {
        params = {
            {
                name = "text",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.AddHistoryLine(text)",
        type = "function",
    },
    ClearFocus = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.ClearFocus()",
        type = "function",
    },
    ClearHighlightText = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.ClearHighlightText()",
        type = "function",
    },
    ClearHistory = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.ClearHistory()",
        type = "function",
    },
    Disable = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.Disable()",
        type = "function",
    },
    Enable = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.Enable()",
        type = "function",
    },
    GetAltArrowKeyMode = {
        params = {},
        returns = {
            {
                name = "altMode",
                nilable = false,
                type = "bool",
            },
        },
        signature = "altMode = SimpleEditBoxAPI.GetAltArrowKeyMode()",
        type = "function",
    },
    GetBlinkSpeed = {
        params = {},
        returns = {
            {
                name = "cursorBlinkSpeedSec",
                nilable = false,
                type = "number",
            },
        },
        signature = "cursorBlinkSpeedSec = SimpleEditBoxAPI.GetBlinkSpeed()",
        type = "function",
    },
    GetCursorPosition = {
        params = {},
        returns = {
            {
                name = "cursorPosition",
                nilable = false,
                type = "number",
            },
        },
        signature = "cursorPosition = SimpleEditBoxAPI.GetCursorPosition()",
        type = "function",
    },
    GetDisplayText = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "displayText",
                nilable = false,
                type = "string",
            },
        },
        signature = "displayText = SimpleEditBoxAPI.GetDisplayText()",
        type = "function",
    },
    GetFont = {
        params = {},
        returns = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "fontHeight",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "flags",
                nilable = false,
                type = "TBFFlags",
            },
        },
        signature = "name, fontHeight, flags = SimpleEditBoxAPI.GetFont()",
        type = "function",
    },
    GetFontObject = {
        params = {},
        returns = {
            {
                name = "font",
                nilable = false,
                type = "SimpleFont",
            },
        },
        signature = "font = SimpleEditBoxAPI.GetFontObject()",
        type = "function",
    },
    GetHighlightColor = {
        params = {},
        returns = {
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "colorA",
                nilable = false,
                type = "number",
            },
        },
        signature = "colorR, colorG, colorB, colorA = SimpleEditBoxAPI.GetHighlightColor()",
        type = "function",
    },
    GetHistoryLines = {
        params = {},
        returns = {
            {
                name = "numHistoryLines",
                nilable = false,
                type = "number",
            },
        },
        signature = "numHistoryLines = SimpleEditBoxAPI.GetHistoryLines()",
        type = "function",
    },
    GetIndentedWordWrap = {
        params = {},
        returns = {
            {
                name = "isIndented",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isIndented = SimpleEditBoxAPI.GetIndentedWordWrap()",
        type = "function",
    },
    GetInputLanguage = {
        params = {},
        returns = {
            {
                name = "language",
                nilable = false,
                type = "cstring",
            },
        },
        signature = "language = SimpleEditBoxAPI.GetInputLanguage()",
        type = "function",
    },
    GetJustifyH = {
        params = {},
        returns = {
            {
                name = "justifyH",
                nilable = false,
                type = "JustifyHorizontal",
            },
        },
        signature = "justifyH = SimpleEditBoxAPI.GetJustifyH()",
        type = "function",
    },
    GetJustifyV = {
        params = {},
        returns = {
            {
                name = "justifyV",
                nilable = false,
                type = "JustifyVertical",
            },
        },
        signature = "justifyV = SimpleEditBoxAPI.GetJustifyV()",
        type = "function",
    },
    GetMaxBytes = {
        params = {},
        returns = {
            {
                name = "maxBytes",
                nilable = false,
                type = "number",
            },
        },
        signature = "maxBytes = SimpleEditBoxAPI.GetMaxBytes()",
        type = "function",
    },
    GetMaxLetters = {
        params = {},
        returns = {
            {
                name = "maxLetters",
                nilable = false,
                type = "number",
            },
        },
        signature = "maxLetters = SimpleEditBoxAPI.GetMaxLetters()",
        type = "function",
    },
    GetNumLetters = {
        mayReturnNothing = true,
        params = {},
        returns = {
            {
                name = "numLetters",
                nilable = false,
                type = "number",
            },
        },
        signature = "numLetters = SimpleEditBoxAPI.GetNumLetters()",
        type = "function",
    },
    GetNumLines = {
        params = {},
        returns = {
            {
                name = "lines",
                nilable = false,
                type = "number",
            },
        },
        signature = "lines = SimpleEditBoxAPI.GetNumLines()",
        type = "function",
    },
    GetNumber = {
        params = {},
        returns = {
            {
                name = "number",
                nilable = true,
                type = "number",
            },
        },
        signature = "number = SimpleEditBoxAPI.GetNumber()",
        type = "function",
    },
    GetShadowColor = {
        params = {},
        returns = {
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "colorA",
                nilable = false,
                type = "number",
            },
        },
        signature = "colorR, colorG, colorB, colorA = SimpleEditBoxAPI.GetShadowColor()",
        type = "function",
    },
    GetShadowOffset = {
        params = {},
        returns = {
            {
                name = "offsetX",
                nilable = false,
                type = "number",
            },
            {
                name = "offsetY",
                nilable = false,
                type = "number",
            },
        },
        signature = "offsetX, offsetY = SimpleEditBoxAPI.GetShadowOffset()",
        type = "function",
    },
    GetSpacing = {
        params = {},
        returns = {
            {
                name = "fontHeight",
                nilable = false,
                type = "uiUnit",
            },
        },
        signature = "fontHeight = SimpleEditBoxAPI.GetSpacing()",
        type = "function",
    },
    GetText = {
        params = {},
        returns = {
            {
                name = "text",
                nilable = false,
                type = "cstring",
            },
        },
        signature = "text = SimpleEditBoxAPI.GetText()",
        type = "function",
    },
    GetTextColor = {
        params = {},
        returns = {
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "colorA",
                nilable = false,
                type = "number",
            },
        },
        signature = "colorR, colorG, colorB, colorA = SimpleEditBoxAPI.GetTextColor()",
        type = "function",
    },
    GetTextInsets = {
        params = {},
        returns = {
            {
                name = "left",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "right",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "top",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "bottom",
                nilable = false,
                type = "uiUnit",
            },
        },
        signature = "left, right, top, bottom = SimpleEditBoxAPI.GetTextInsets()",
        type = "function",
    },
    GetUTF8CursorPosition = {
        params = {},
        returns = {
            {
                name = "cursorPosition",
                nilable = false,
                type = "number",
            },
        },
        signature = "cursorPosition = SimpleEditBoxAPI.GetUTF8CursorPosition()",
        type = "function",
    },
    GetVisibleTextByteLimit = {
        params = {},
        returns = {
            {
                name = "maxVisibleBytes",
                nilable = false,
                type = "number",
            },
        },
        signature = "maxVisibleBytes = SimpleEditBoxAPI.GetVisibleTextByteLimit()",
        type = "function",
    },
    HasFocus = {
        params = {},
        returns = {
            {
                name = "hasFocus",
                nilable = false,
                type = "bool",
            },
        },
        signature = "hasFocus = SimpleEditBoxAPI.HasFocus()",
        type = "function",
    },
    HasText = {
        params = {},
        returns = {
            {
                name = "hasText",
                nilable = false,
                type = "bool",
            },
        },
        signature = "hasText = SimpleEditBoxAPI.HasText()",
        type = "function",
    },
    HighlightText = {
        params = {
            {
                default = 0,
                name = "start",
                nilable = false,
                type = "number",
            },
            {
                default = -1,
                name = "stop",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.HighlightText(start, stop)",
        type = "function",
    },
    Insert = {
        params = {
            {
                name = "text",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.Insert(text)",
        type = "function",
    },
    IsAlphabeticOnly = {
        params = {},
        returns = {
            {
                name = "enabled",
                nilable = false,
                type = "bool",
            },
        },
        signature = "enabled = SimpleEditBoxAPI.IsAlphabeticOnly()",
        type = "function",
    },
    IsAutoFocus = {
        params = {},
        returns = {
            {
                name = "autoFocus",
                nilable = false,
                type = "bool",
            },
        },
        signature = "autoFocus = SimpleEditBoxAPI.IsAutoFocus()",
        type = "function",
    },
    IsCountInvisibleLetters = {
        params = {},
        returns = {
            {
                name = "countInvisibleLetters",
                nilable = false,
                type = "bool",
            },
        },
        signature = "countInvisibleLetters = SimpleEditBoxAPI.IsCountInvisibleLetters()",
        type = "function",
    },
    IsEnabled = {
        params = {},
        returns = {
            {
                name = "isEnabled",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isEnabled = SimpleEditBoxAPI.IsEnabled()",
        type = "function",
    },
    IsInIMECompositionMode = {
        params = {},
        returns = {
            {
                name = "isInIMECompositionMode",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isInIMECompositionMode = SimpleEditBoxAPI.IsInIMECompositionMode()",
        type = "function",
    },
    IsMultiLine = {
        params = {},
        returns = {
            {
                name = "multiline",
                nilable = false,
                type = "bool",
            },
        },
        signature = "multiline = SimpleEditBoxAPI.IsMultiLine()",
        type = "function",
    },
    IsNumeric = {
        params = {},
        returns = {
            {
                name = "isNumeric",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isNumeric = SimpleEditBoxAPI.IsNumeric()",
        type = "function",
    },
    IsNumericFullRange = {
        params = {},
        returns = {
            {
                name = "isNumeric",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isNumeric = SimpleEditBoxAPI.IsNumericFullRange()",
        type = "function",
    },
    IsPassword = {
        params = {},
        returns = {
            {
                name = "isPassword",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isPassword = SimpleEditBoxAPI.IsPassword()",
        type = "function",
    },
    IsSecureText = {
        params = {},
        returns = {
            {
                name = "isSecure",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isSecure = SimpleEditBoxAPI.IsSecureText()",
        type = "function",
    },
    ResetInputMode = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.ResetInputMode()",
        type = "function",
    },
    SetAlphabeticOnly = {
        params = {
            {
                default = false,
                name = "enabled",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetAlphabeticOnly(enabled)",
        type = "function",
    },
    SetAltArrowKeyMode = {
        params = {
            {
                default = false,
                name = "altMode",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetAltArrowKeyMode(altMode)",
        type = "function",
    },
    SetAutoFocus = {
        params = {
            {
                default = false,
                name = "autoFocus",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetAutoFocus(autoFocus)",
        type = "function",
    },
    SetBlinkSpeed = {
        params = {
            {
                name = "cursorBlinkSpeedSec",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetBlinkSpeed(cursorBlinkSpeedSec)",
        type = "function",
    },
    SetCountInvisibleLetters = {
        params = {
            {
                default = false,
                name = "countInvisibleLetters",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetCountInvisibleLetters(countInvisibleLetters)",
        type = "function",
    },
    SetCursorPosition = {
        params = {
            {
                name = "cursorPosition",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetCursorPosition(cursorPosition)",
        type = "function",
    },
    SetEnabled = {
        params = {
            {
                default = false,
                name = "enabled",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetEnabled(enabled)",
        type = "function",
    },
    SetFocus = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.SetFocus()",
        type = "function",
    },
    SetFont = {
        params = {
            {
                name = "fontFile",
                nilable = false,
                type = "cstring",
            },
            {
                name = "height",
                nilable = false,
                type = "uiFontHeight",
            },
            {
                name = "flags",
                nilable = false,
                type = "TBFFlags",
            },
        },
        returns = {
            {
                name = "success",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "success = SimpleEditBoxAPI.SetFont(fontFile, height, flags)",
        type = "function",
    },
    SetFontObject = {
        params = {
            {
                name = "font",
                nilable = false,
                type = "SimpleFont",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetFontObject(font)",
        type = "function",
    },
    SetHighlightColor = {
        params = {
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "a",
                nilable = true,
                type = "SingleColorValue",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetHighlightColor(colorR, colorG, colorB, a)",
        type = "function",
    },
    SetHistoryLines = {
        params = {
            {
                name = "numHistoryLines",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetHistoryLines(numHistoryLines)",
        type = "function",
    },
    SetIndentedWordWrap = {
        params = {
            {
                default = false,
                name = "isIndented",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetIndentedWordWrap(isIndented)",
        type = "function",
    },
    SetJustifyH = {
        params = {
            {
                name = "justifyH",
                nilable = false,
                type = "JustifyHorizontal",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetJustifyH(justifyH)",
        type = "function",
    },
    SetJustifyV = {
        params = {
            {
                name = "justifyV",
                nilable = false,
                type = "JustifyVertical",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetJustifyV(justifyV)",
        type = "function",
    },
    SetMaxBytes = {
        params = {
            {
                name = "maxBytes",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetMaxBytes(maxBytes)",
        type = "function",
    },
    SetMaxLetters = {
        params = {
            {
                name = "maxLetters",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetMaxLetters(maxLetters)",
        type = "function",
    },
    SetMultiLine = {
        params = {
            {
                default = false,
                name = "multiline",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetMultiLine(multiline)",
        type = "function",
    },
    SetNumber = {
        params = {
            {
                name = "number",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetNumber(number)",
        type = "function",
    },
    SetNumeric = {
        params = {
            {
                default = false,
                name = "isNumeric",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetNumeric(isNumeric)",
        type = "function",
    },
    SetNumericFullRange = {
        params = {
            {
                default = false,
                name = "isNumeric",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetNumericFullRange(isNumeric)",
        type = "function",
    },
    SetPassword = {
        params = {
            {
                default = false,
                name = "isPassword",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetPassword(isPassword)",
        type = "function",
    },
    SetSecureText = {
        params = {
            {
                default = false,
                name = "isSecure",
                nilable = false,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetSecureText(isSecure)",
        type = "function",
    },
    SetSecurityDisablePaste = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.SetSecurityDisablePaste()",
        type = "function",
    },
    SetSecurityDisableSetText = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.SetSecurityDisableSetText()",
        type = "function",
    },
    SetShadowColor = {
        params = {
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "a",
                nilable = true,
                type = "SingleColorValue",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetShadowColor(colorR, colorG, colorB, a)",
        type = "function",
    },
    SetShadowOffset = {
        params = {
            {
                name = "offsetX",
                nilable = false,
                type = "number",
            },
            {
                name = "offsetY",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetShadowOffset(offsetX, offsetY)",
        type = "function",
    },
    SetSpacing = {
        params = {
            {
                name = "fontHeight",
                nilable = false,
                type = "uiUnit",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetSpacing(fontHeight)",
        type = "function",
    },
    SetText = {
        params = {
            {
                name = "text",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetText(text)",
        type = "function",
    },
    SetTextColor = {
        params = {
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "a",
                nilable = true,
                type = "SingleColorValue",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetTextColor(colorR, colorG, colorB, a)",
        type = "function",
    },
    SetTextInsets = {
        params = {
            {
                name = "left",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "right",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "top",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "bottom",
                nilable = false,
                type = "uiUnit",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetTextInsets(left, right, top, bottom)",
        type = "function",
    },
    SetVisibleTextByteLimit = {
        params = {
            {
                name = "maxVisibleBytes",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleEditBoxAPI.SetVisibleTextByteLimit(maxVisibleBytes)",
        type = "function",
    },
    ToggleInputLanguage = {
        params = {},
        returns = {},
        signature = "SimpleEditBoxAPI.ToggleInputLanguage()",
        type = "function",
    },
})
