-- Forge_APIRef-SimpleAnimPathAPI: per-namespace API data for SimpleAnimPathAPI.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/SimpleAnimPathAPIDocumentation.lua.
-- Generated 2026-05-06 13:02:30Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("SimpleAnimPathAPI", {
    CreateControlPoint = {
        params = {
            {
                name = "name",
                nilable = true,
                type = "cstring",
            },
            {
                name = "templateName",
                nilable = true,
                type = "cstring",
            },
            {
                name = "order",
                nilable = true,
                type = "number",
            },
        },
        returns = {
            {
                name = "point",
                nilable = false,
                type = "SimpleControlPoint",
            },
        },
        secretArguments = "NotAllowed",
        signature = "point = SimpleAnimPathAPI.CreateControlPoint(name, templateName, order)",
        type = "function",
    },
    GetControlPoints = {
        params = {},
        returns = {
            {
                name = "points",
                nilable = false,
                type = "SimpleControlPoint",
            },
        },
        signature = "points = SimpleAnimPathAPI.GetControlPoints()",
        type = "function",
    },
    GetCurveType = {
        params = {},
        returns = {
            {
                name = "curveType",
                nilable = false,
                type = "CurveType",
            },
        },
        signature = "curveType = SimpleAnimPathAPI.GetCurveType()",
        type = "function",
    },
    GetMaxControlPointOrder = {
        params = {},
        returns = {
            {
                name = "maxOrder",
                nilable = false,
                type = "number",
            },
        },
        signature = "maxOrder = SimpleAnimPathAPI.GetMaxControlPointOrder()",
        type = "function",
    },
    SetCurveType = {
        params = {
            {
                name = "curveType",
                nilable = false,
                type = "CurveType",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "SimpleAnimPathAPI.SetCurveType(curveType)",
        type = "function",
    },
})
