-- Forge_APIRef-CraftingOrderUIShared: per-namespace API data for CraftingOrderUIShared.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/CraftingOrderUISharedDocumentation.lua.
-- Generated 2026-05-06 13:02:26Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("CraftingOrderUIShared", {
    CraftingOrderBucketInfo = {
        fields = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
            {
                name = "skillLineAbilityID",
                nilable = false,
                type = "number",
            },
            {
                name = "tipAmountAvg",
                nilable = false,
                type = "WOWMONEY",
            },
            {
                name = "tipAmountMax",
                nilable = false,
                type = "WOWMONEY",
            },
            {
                name = "numAvailable",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    CraftingOrderClaimsRemainingInfo = {
        fields = {
            {
                default = 0,
                name = "claimsRemaining",
                nilable = false,
                type = "number",
            },
            {
                name = "secondsToRecharge",
                nilable = true,
                type = "number",
            },
        },
        type = "structure",
    },
    CraftingOrderCustomerCategory = {
        fields = {
            {
                name = "categoryName",
                nilable = false,
                type = "string",
            },
            {
                name = "categoryID",
                nilable = false,
                type = "number",
            },
            {
                name = "uiSortOrder",
                nilable = false,
                type = "number",
            },
            {
                name = "primaryCategorySortOrder",
                nilable = true,
                type = "number",
            },
            {
                name = "secondaryCategorySortOrder",
                nilable = true,
                type = "number",
            },
            {
                name = "type",
                nilable = false,
                type = "CraftingOrderCustomerCategoryType",
            },
        },
        type = "structure",
    },
    CraftingOrderCustomerCategoryFilters = {
        fields = {
            {
                name = "primaryCategoryID",
                nilable = true,
                type = "number",
            },
            {
                name = "secondaryCategoryID",
                nilable = true,
                type = "number",
            },
            {
                name = "tertiaryCategoryID",
                nilable = true,
                type = "number",
            },
        },
        type = "structure",
    },
    CraftingOrderCustomerOptionInfo = {
        fields = {
            {
                name = "skillLineAbilityID",
                nilable = false,
                type = "number",
            },
            {
                name = "professionID",
                nilable = false,
                type = "number",
            },
            {
                name = "skillUpSkillLineID",
                nilable = false,
                type = "number",
            },
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemName",
                nilable = false,
                type = "string",
            },
            {
                name = "primaryCategoryID",
                nilable = false,
                type = "number",
            },
            {
                name = "iLvlMin",
                nilable = false,
                type = "number",
            },
            {
                name = "iLvlMax",
                nilable = true,
                type = "number",
            },
            {
                name = "canUse",
                nilable = false,
                type = "bool",
            },
            {
                name = "bindOnPickup",
                nilable = false,
                type = "bool",
            },
            {
                innerType = "number",
                name = "qualityIlvlBonuses",
                nilable = true,
                type = "table",
            },
            {
                innerType = "number",
                name = "craftingQualityIDs",
                nilable = true,
                type = "table",
            },
            {
                name = "quality",
                nilable = true,
                type = "ItemQuality",
            },
            {
                name = "slots",
                nilable = true,
                type = "number",
            },
            {
                name = "level",
                nilable = true,
                type = "number",
            },
            {
                name = "skill",
                nilable = true,
                type = "number",
            },
            {
                name = "secondaryCategoryID",
                nilable = true,
                type = "number",
            },
            {
                name = "tertiaryCategoryID",
                nilable = true,
                type = "number",
            },
            {
                name = "expansionID",
                nilable = true,
                type = "number",
            },
        },
        type = "structure",
    },
    CraftingOrderCustomerSearchParams = {
        fields = {
            {
                name = "categoryFilters",
                nilable = false,
                type = "CraftingOrderCustomerCategoryFilters",
            },
            {
                name = "searchText",
                nilable = true,
                type = "string",
            },
            {
                name = "minLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "maxLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "uncollectedOnly",
                nilable = false,
                type = "bool",
            },
            {
                name = "usableOnly",
                nilable = false,
                type = "bool",
            },
            {
                name = "upgradesOnly",
                nilable = false,
                type = "bool",
            },
            {
                name = "currentExpansionOnly",
                nilable = false,
                type = "bool",
            },
            {
                name = "includePoor",
                nilable = false,
                type = "bool",
            },
            {
                name = "includeCommon",
                nilable = false,
                type = "bool",
            },
            {
                name = "includeUncommon",
                nilable = false,
                type = "bool",
            },
            {
                name = "includeRare",
                nilable = false,
                type = "bool",
            },
            {
                name = "includeEpic",
                nilable = false,
                type = "bool",
            },
            {
                name = "includeLegendary",
                nilable = false,
                type = "bool",
            },
            {
                name = "includeArtifact",
                nilable = false,
                type = "bool",
            },
            {
                name = "isFavoritesSearch",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    CraftingOrderCustomerSearchResults = {
        fields = {
            {
                innerType = "CraftingOrderCustomerOptionInfo",
                name = "options",
                nilable = false,
                type = "table",
            },
            {
                name = "extraColumnType",
                nilable = true,
                type = "AuctionHouseExtraColumn",
            },
        },
        type = "structure",
    },
    CraftingOrderInfo = {
        fields = {
            {
                name = "orderID",
                nilable = false,
                type = "BigUInteger",
            },
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
            {
                name = "skillLineAbilityID",
                nilable = false,
                type = "number",
            },
            {
                name = "orderType",
                nilable = false,
                type = "CraftingOrderType",
            },
            {
                name = "orderState",
                nilable = false,
                type = "CraftingOrderState",
            },
            {
                name = "expirationTime",
                nilable = false,
                type = "time_t",
            },
            {
                name = "claimEndTime",
                nilable = false,
                type = "time_t",
            },
            {
                name = "minQuality",
                nilable = false,
                type = "number",
            },
            {
                name = "tipAmount",
                nilable = false,
                type = "WOWMONEY",
            },
            {
                name = "consortiumCut",
                nilable = false,
                type = "WOWMONEY",
            },
            {
                name = "isRecraft",
                nilable = false,
                type = "bool",
            },
            {
                name = "isFulfillable",
                nilable = false,
                type = "bool",
            },
            {
                name = "reagentState",
                nilable = false,
                type = "CraftingOrderReagentsType",
            },
            {
                name = "customerGuid",
                nilable = true,
                type = "WOWGUID",
            },
            {
                name = "customerName",
                nilable = true,
                type = "string",
            },
            {
                name = "crafterGuid",
                nilable = true,
                type = "WOWGUID",
            },
            {
                name = "crafterName",
                nilable = true,
                type = "string",
            },
            {
                name = "npcCustomerCreatureID",
                nilable = true,
                type = "number",
            },
            {
                name = "customerNotes",
                nilable = false,
                type = "string",
            },
            {
                innerType = "CraftingOrderReagentInfo",
                name = "reagents",
                nilable = false,
                type = "table",
            },
            {
                name = "outputItemHyperlink",
                nilable = true,
                type = "string",
            },
            {
                name = "outputItemGUID",
                nilable = true,
                type = "WOWGUID",
            },
            {
                name = "recraftItemHyperlink",
                nilable = true,
                type = "string",
            },
            {
                innerType = "CraftingOrderRewardInfo",
                name = "npcOrderRewards",
                nilable = false,
                type = "table",
            },
            {
                name = "npcCraftingOrderSetID",
                nilable = false,
                type = "number",
            },
            {
                name = "npcTreasureID",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    CraftingOrderMailInfo = {
        fields = {
            {
                name = "reason",
                nilable = false,
                type = "RcoCloseReason",
            },
            {
                name = "recipeName",
                nilable = false,
                type = "string",
            },
            {
                name = "commissionPaid",
                nilable = true,
                type = "WOWMONEY",
            },
            {
                name = "crafterNote",
                nilable = true,
                type = "string",
            },
            {
                name = "crafterGUID",
                nilable = true,
                type = "WOWGUID",
            },
            {
                name = "crafterName",
                nilable = true,
                type = "string",
            },
            {
                name = "customerGUID",
                nilable = true,
                type = "WOWGUID",
            },
            {
                name = "customerName",
                nilable = true,
                type = "string",
            },
        },
        type = "structure",
    },
    CraftingOrderPersonalOrdersInfo = {
        fields = {
            {
                name = "profession",
                nilable = false,
                type = "Profession",
            },
            {
                name = "numPersonalOrders",
                nilable = false,
                type = "number",
            },
            {
                name = "professionName",
                nilable = false,
                type = "cstring",
            },
        },
        type = "structure",
    },
    CraftingOrderReagentInfo = {
        fields = {
            {
                name = "reagentInfo",
                nilable = false,
                type = "CraftingReagentInfo",
            },
            {
                name = "slotIndex",
                nilable = false,
                type = "luaIndex",
            },
            {
                name = "source",
                nilable = false,
                type = "CraftingOrderReagentSource",
            },
            {
                name = "isBasicReagent",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    CraftingOrderRequestCallback = {
        fields = {},
        type = "structure",
    },
    CraftingOrderRequestMyOrdersCallback = {
        fields = {},
        type = "structure",
    },
    CraftingOrderRewardInfo = {
        fields = {
            {
                name = "itemLink",
                nilable = true,
                type = "string",
            },
            {
                name = "currencyType",
                nilable = true,
                type = "number",
            },
            {
                name = "count",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    CraftingOrderSortInfo = {
        fields = {
            {
                name = "sortType",
                nilable = false,
                type = "CraftingOrderSortType",
            },
            {
                name = "reversed",
                nilable = false,
                type = "bool",
            },
        },
        type = "structure",
    },
    NewCraftingOrderInfo = {
        fields = {
            {
                name = "skillLineAbilityID",
                nilable = false,
                type = "number",
            },
            {
                name = "orderType",
                nilable = false,
                type = "CraftingOrderType",
            },
            {
                name = "orderDuration",
                nilable = false,
                type = "CraftingOrderDuration",
            },
            {
                name = "tipAmount",
                nilable = false,
                type = "WOWMONEY",
            },
            {
                name = "customerNotes",
                nilable = false,
                type = "string",
            },
            {
                innerType = "RegularReagentInfo",
                name = "reagentInfos",
                nilable = false,
                type = "table",
            },
            {
                innerType = "CraftingReagentInfo",
                name = "craftingReagentItems",
                nilable = false,
                type = "table",
            },
            {
                name = "minCraftingQualityID",
                nilable = true,
                type = "number",
            },
            {
                name = "orderTarget",
                nilable = true,
                type = "string",
            },
            {
                name = "recraftItem",
                nilable = true,
                type = "WOWGUID",
            },
        },
        type = "structure",
    },
})
