-- Forge_APIRef-UnitConstants: per-namespace API data for UnitConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/UnitConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:32Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("UnitConstants", {
    AddPrivateAuraAnchorArgs = {
        fields = {
            {
                name = "unitToken",
                nilable = false,
                type = "cstring",
            },
            {
                name = "auraIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "parent",
                nilable = false,
                type = "SimpleFrame",
            },
            {
                name = "showCountdownFrame",
                nilable = false,
                type = "bool",
            },
            {
                name = "showCountdownNumbers",
                nilable = false,
                type = "bool",
            },
            {
                name = "isContainer",
                nilable = false,
                type = "bool",
            },
            {
                name = "iconInfo",
                nilable = true,
                type = "PrivateAuraIconInfo",
            },
            {
                name = "durationAnchor",
                nilable = true,
                type = "AnchorBinding",
            },
        },
        type = "structure",
    },
    PrivateAuraIconInfo = {
        fields = {
            {
                name = "iconAnchor",
                nilable = false,
                type = "AnchorBinding",
            },
            {
                name = "iconWidth",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "iconHeight",
                nilable = false,
                type = "uiUnit",
            },
            {
                name = "borderScale",
                nilable = true,
                type = "uiUnit",
            },
        },
        type = "structure",
    },
    UnitAuraUpdateInfo = {
        fields = {
            {
                default = false,
                name = "isFullUpdate",
                nilable = false,
                type = "bool",
            },
            {
                innerType = "number",
                name = "removedAuraInstanceIDs",
                nilable = true,
                type = "table",
            },
            {
                innerType = "AuraData",
                name = "addedAuras",
                nilable = true,
                type = "table",
            },
            {
                innerType = "number",
                name = "updatedAuraInstanceIDs",
                nilable = true,
                type = "table",
            },
        },
        type = "structure",
    },
    UnitPrivateAuraAnchorInfo = {
        fields = {
            {
                name = "anchorID",
                nilable = false,
                type = "number",
            },
            {
                name = "unitToken",
                nilable = false,
                type = "string",
            },
            {
                name = "auraIndex",
                nilable = false,
                type = "number",
            },
            {
                name = "showCountdownFrame",
                nilable = false,
                type = "bool",
            },
            {
                name = "showCountdownNumbers",
                nilable = false,
                type = "bool",
            },
            {
                name = "iconWidth",
                nilable = true,
                type = "uiUnit",
            },
            {
                name = "iconHeight",
                nilable = true,
                type = "uiUnit",
            },
            {
                name = "borderScale",
                nilable = true,
                type = "uiUnit",
            },
            {
                name = "isContainer",
                nilable = true,
                type = "bool",
            },
            {
                name = "parent",
                nilable = false,
                type = "SimpleFrame",
            },
        },
        type = "structure",
    },
    UnitPrivateAuraAppliedSoundInfo = {
        fields = {
            {
                name = "unitToken",
                nilable = false,
                type = "string",
            },
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
            {
                name = "soundFileName",
                nilable = true,
                type = "string",
            },
            {
                name = "soundFileID",
                nilable = true,
                type = "number",
            },
            {
                name = "outputChannel",
                nilable = true,
                type = "string",
            },
        },
        type = "structure",
    },
})
