-- Forge_APIRef-C_Item: per-namespace API data for C_Item.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/ItemDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_Item", {
    ACTION_WILL_BIND_ITEM = {
        cppName = "ActionWillBindItem",
        literalName = "ACTION_WILL_BIND_ITEM",
        payload = {},
        synchronous = true,
        type = "event",
    },
    ActionBindsItem = {
        params = {},
        returns = {},
        signature = "C_Item.ActionBindsItem()",
        type = "function",
    },
    BIND_ENCHANT = {
        cppName = "BindEnchant",
        literalName = "BIND_ENCHANT",
        payload = {},
        synchronous = true,
        type = "event",
    },
    BindEnchant = {
        params = {},
        returns = {},
        signature = "C_Item.BindEnchant()",
        type = "function",
    },
    CHARACTER_ITEM_FIXUP_NOTIFICATION = {
        cppName = "CharacterItemFixupNotification",
        literalName = "CHARACTER_ITEM_FIXUP_NOTIFICATION",
        payload = {
            {
                name = "fixupVersion",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    CONFIRM_BEFORE_USE = {
        cppName = "ConfirmBeforeUse",
        literalName = "CONFIRM_BEFORE_USE",
        payload = {},
        synchronous = true,
        type = "event",
    },
    CONVERT_TO_BIND_TO_ACCOUNT_CONFIRM = {
        cppName = "ConvertToBindToAccountConfirm",
        literalName = "CONVERT_TO_BIND_TO_ACCOUNT_CONFIRM",
        payload = {},
        synchronous = true,
        type = "event",
    },
    CanBeRefunded = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "canBeRefunded",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canBeRefunded = C_Item.CanBeRefunded(itemLocation)",
        type = "function",
    },
    CanItemTransmogAppearance = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "canTransmog",
                nilable = false,
                type = "bool",
            },
            {
                name = "errorCode",
                nilable = false,
                type = "TransmogOutfitSlotError",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canTransmog, errorCode = C_Item.CanItemTransmogAppearance(itemLoc)",
        type = "function",
    },
    CanScrapItem = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "canBeScrapped",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "canBeScrapped = C_Item.CanScrapItem(itemLoc)",
        type = "function",
    },
    CanViewItemPowers = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isItemViewable",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isItemViewable = C_Item.CanViewItemPowers(itemLoc)",
        type = "function",
    },
    ConfirmBindOnUse = {
        params = {},
        returns = {},
        signature = "C_Item.ConfirmBindOnUse()",
        type = "function",
    },
    ConfirmNoRefundOnUse = {
        params = {},
        returns = {},
        signature = "C_Item.ConfirmNoRefundOnUse()",
        type = "function",
    },
    ConfirmOnUse = {
        params = {},
        returns = {},
        signature = "C_Item.ConfirmOnUse()",
        type = "function",
    },
    DELETE_ITEM_CONFIRM = {
        cppName = "DeleteItemConfirm",
        literalName = "DELETE_ITEM_CONFIRM",
        payload = {
            {
                name = "itemName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "qualityID",
                nilable = false,
                type = "number",
            },
            {
                name = "bonding",
                nilable = false,
                type = "number",
            },
            {
                name = "questWarn",
                nilable = false,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    DoesItemContainSpec = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                name = "classID",
                nilable = false,
                type = "number",
            },
            {
                default = 0,
                name = "specID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.DoesItemContainSpec(itemInfo, classID, specID)",
        type = "function",
    },
    DoesItemExist = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "emptiableItemLocation",
                nilable = false,
                type = "EmptiableItemLocation",
            },
        },
        returns = {
            {
                name = "itemExists",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemExists = C_Item.DoesItemExist(emptiableItemLocation)",
        type = "function",
    },
    DoesItemExistByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemExists",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemExists = C_Item.DoesItemExistByID(itemInfo)",
        type = "function",
    },
    DoesItemMatchBonusTreeReplacement = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "matchesBonusTree",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "matchesBonusTree = C_Item.DoesItemMatchBonusTreeReplacement(itemLoc)",
        type = "function",
    },
    DoesItemMatchTargetEnchantingSpell = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "matchesTargetEnchantingSpell",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "matchesTargetEnchantingSpell = C_Item.DoesItemMatchTargetEnchantingSpell(itemLoc)",
        type = "function",
    },
    DoesItemMatchTrackJump = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "matchesTrackJump",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "matchesTrackJump = C_Item.DoesItemMatchTrackJump(itemLoc)",
        type = "function",
    },
    DropItemOnUnit = {
        params = {
            {
                name = "unitGUID",
                nilable = false,
                type = "UnitToken",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.DropItemOnUnit(unitGUID)",
        type = "function",
    },
    END_BOUND_TRADEABLE = {
        cppName = "EndBoundTradeable",
        literalName = "END_BOUND_TRADEABLE",
        payload = {
            {
                name = "reason",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    EndBoundTradeable = {
        params = {
            {
                name = "type",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.EndBoundTradeable(type)",
        type = "function",
    },
    EndRefund = {
        params = {
            {
                name = "type",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.EndRefund(type)",
        type = "function",
    },
    EquipItemByName = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                name = "dstSlot",
                nilable = true,
                type = "luaIndex",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.EquipItemByName(itemInfo, dstSlot)",
        type = "function",
    },
    GET_ITEM_INFO_RECEIVED = {
        cppName = "GetItemInfoReceived",
        literalName = "GET_ITEM_INFO_RECEIVED",
        payload = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "success",
                nilable = false,
                type = "bool",
            },
        },
        synchronous = true,
        type = "event",
    },
    GetAppliedItemTransmogInfo = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                mixin = "ItemTransmogInfoMixin",
                name = "info",
                nilable = true,
                type = "ItemTransmogInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "info = C_Item.GetAppliedItemTransmogInfo(itemLoc)",
        type = "function",
    },
    GetBaseItemTransmogInfo = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                mixin = "ItemTransmogInfoMixin",
                name = "info",
                nilable = true,
                type = "ItemTransmogInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "info = C_Item.GetBaseItemTransmogInfo(itemLoc)",
        type = "function",
    },
    GetCurrentItemLevel = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "currentItemLevel",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "currentItemLevel = C_Item.GetCurrentItemLevel(itemLocation)",
        type = "function",
    },
    GetCurrentItemTransmogInfo = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                mixin = "ItemTransmogInfoMixin",
                name = "info",
                nilable = true,
                type = "ItemTransmogInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "info = C_Item.GetCurrentItemTransmogInfo(itemLoc)",
        type = "function",
    },
    GetDelvePreviewItemLink = {
        params = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "context",
                nilable = false,
                type = "ItemCreationContext",
            },
        },
        returns = {
            {
                name = "itemLink",
                nilable = true,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemLink = C_Item.GetDelvePreviewItemLink(itemID, context)",
        type = "function",
    },
    GetDelvePreviewItemQuality = {
        params = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "context",
                nilable = false,
                type = "ItemCreationContext",
            },
        },
        returns = {
            {
                name = "itemQuality",
                nilable = false,
                type = "ItemQuality",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemQuality = C_Item.GetDelvePreviewItemQuality(itemID, context)",
        type = "function",
    },
    GetDetailedItemLevelInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "actualItemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "previewLevel",
                nilable = false,
                type = "bool",
            },
            {
                name = "sparseItemLevel",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "actualItemLevel, previewLevel, sparseItemLevel = C_Item.GetDetailedItemLevelInfo(itemInfo)",
        type = "function",
    },
    GetFirstTriggeredSpellForItem = {
        params = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemQuality",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "spellID",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "spellID = C_Item.GetFirstTriggeredSpellForItem(itemID, itemQuality)",
        type = "function",
    },
    GetItemChildInfo = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                name = "slotID",
                nilable = true,
                type = "luaIndex",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "result",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.GetItemChildInfo(itemInfo, slotID)",
        type = "function",
    },
    GetItemClassInfo = {
        params = {
            {
                name = "itemClassID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.GetItemClassInfo(itemClassID)",
        type = "function",
    },
    GetItemConversionOutputIcon = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "icon",
                nilable = true,
                type = "fileID",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "icon = C_Item.GetItemConversionOutputIcon(itemLoc)",
        type = "function",
    },
    GetItemCooldown = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "startTimeSeconds",
                nilable = false,
                type = "number",
            },
            {
                name = "durationSeconds",
                nilable = false,
                type = "number",
            },
            {
                name = "enableCooldownTimer",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "startTimeSeconds, durationSeconds, enableCooldownTimer = C_Item.GetItemCooldown(itemInfo)",
        type = "function",
    },
    GetItemCount = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                default = false,
                name = "includeBank",
                nilable = false,
                type = "bool",
            },
            {
                default = false,
                name = "includeUses",
                nilable = false,
                type = "bool",
            },
            {
                default = false,
                name = "includeReagentBank",
                nilable = false,
                type = "bool",
            },
            {
                default = false,
                name = "includeAccountBank",
                nilable = false,
                type = "bool",
            },
        },
        returns = {
            {
                name = "count",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "count = C_Item.GetItemCount(itemInfo, includeBank, includeUses, includeReagentBank, includeAccountBank)",
        type = "function",
    },
    GetItemCreationContext = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "creationContext",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemID, creationContext = C_Item.GetItemCreationContext(itemInfo)",
        type = "function",
    },
    GetItemFamily = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.GetItemFamily(itemInfo)",
        type = "function",
    },
    GetItemGUID = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemGUID = C_Item.GetItemGUID(itemLocation)",
        type = "function",
    },
    GetItemGem = {
        mayReturnNothing = true,
        params = {
            {
                name = "hyperlink",
                nilable = false,
                type = "cstring",
            },
            {
                name = "index",
                nilable = false,
                type = "luaIndex",
            },
        },
        returns = {
            {
                name = "gemName",
                nilable = false,
                type = "string",
            },
            {
                name = "gemLink",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "gemName, gemLink = C_Item.GetItemGem(hyperlink, index)",
        type = "function",
    },
    GetItemGemID = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                name = "index",
                nilable = false,
                type = "luaIndex",
            },
        },
        returns = {
            {
                name = "gemID",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "gemID = C_Item.GetItemGemID(itemInfo, index)",
        type = "function",
    },
    GetItemID = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemID = C_Item.GetItemID(itemLocation)",
        type = "function",
    },
    GetItemIDByGUID = {
        params = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "itemID",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemID = C_Item.GetItemIDByGUID(itemGUID)",
        type = "function",
    },
    GetItemIDForItemInfo = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemID = C_Item.GetItemIDForItemInfo(itemInfo)",
        type = "function",
    },
    GetItemIcon = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "icon",
                nilable = true,
                type = "fileID",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "icon = C_Item.GetItemIcon(itemLocation)",
        type = "function",
    },
    GetItemIconByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "icon",
                nilable = true,
                type = "fileID",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "icon = C_Item.GetItemIconByID(itemInfo)",
        type = "function",
    },
    GetItemInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemLink",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemQuality",
                nilable = false,
                type = "ItemQuality",
            },
            {
                name = "itemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "itemMinLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "itemType",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemSubType",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemStackCount",
                nilable = false,
                type = "number",
            },
            {
                name = "itemEquipLoc",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemTexture",
                nilable = false,
                type = "fileID",
            },
            {
                name = "sellPrice",
                nilable = false,
                type = "number",
            },
            {
                name = "classID",
                nilable = false,
                type = "number",
            },
            {
                name = "subclassID",
                nilable = false,
                type = "number",
            },
            {
                name = "bindType",
                nilable = false,
                type = "number",
            },
            {
                name = "expansionID",
                nilable = false,
                type = "number",
            },
            {
                name = "setID",
                nilable = true,
                type = "number",
            },
            {
                name = "isCraftingReagent",
                nilable = false,
                type = "bool",
            },
            {
                name = "itemDescription",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemName, itemLink, itemQuality, itemLevel, itemMinLevel, itemType, itemSubType, itemStackCount, itemEquipLoc, itemTexture, sellPrice, classID, subclassID, bindType, expansionID, setID, isCraftingReagent, itemDescription = C_Item.GetItemInfo(itemInfo)",
        type = "function",
    },
    GetItemInfoInstant = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemType",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemSubType",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemEquipLoc",
                nilable = false,
                type = "cstring",
            },
            {
                name = "icon",
                nilable = false,
                type = "fileID",
            },
            {
                name = "classID",
                nilable = false,
                type = "number",
            },
            {
                name = "subClassID",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemID, itemType, itemSubType, itemEquipLoc, icon, classID, subClassID = C_Item.GetItemInfoInstant(itemInfo)",
        type = "function",
    },
    GetItemInventorySlotInfo = {
        params = {
            {
                name = "inventorySlot",
                nilable = false,
                type = "InventoryType",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.GetItemInventorySlotInfo(inventorySlot)",
        type = "function",
    },
    GetItemInventorySlotKey = {
        params = {
            {
                name = "inventorySlot",
                nilable = false,
                type = "InventoryType",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.GetItemInventorySlotKey(inventorySlot)",
        type = "function",
    },
    GetItemInventoryType = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "inventoryType",
                nilable = true,
                type = "InventoryType",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "inventoryType = C_Item.GetItemInventoryType(itemLocation)",
        type = "function",
    },
    GetItemInventoryTypeByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "inventoryType",
                nilable = true,
                type = "InventoryType",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "inventoryType = C_Item.GetItemInventoryTypeByID(itemInfo)",
        type = "function",
    },
    GetItemLearnTransmogSet = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "setID",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "setID = C_Item.GetItemLearnTransmogSet(itemInfo)",
        type = "function",
    },
    GetItemLink = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "itemLink",
                nilable = true,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemLink = C_Item.GetItemLink(itemLocation)",
        type = "function",
    },
    GetItemLinkByGUID = {
        params = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "itemLink",
                nilable = true,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemLink = C_Item.GetItemLinkByGUID(itemGUID)",
        type = "function",
    },
    GetItemLocation = {
        params = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = true,
                type = "ItemLocation",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemLocation = C_Item.GetItemLocation(itemGUID)",
        type = "function",
    },
    GetItemMaxStackSize = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "stackSize",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "stackSize = C_Item.GetItemMaxStackSize(itemLocation)",
        type = "function",
    },
    GetItemMaxStackSizeByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "stackSize",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "stackSize = C_Item.GetItemMaxStackSizeByID(itemInfo)",
        type = "function",
    },
    GetItemName = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "itemName",
                nilable = true,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemName = C_Item.GetItemName(itemLocation)",
        type = "function",
    },
    GetItemNameByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemName",
                nilable = true,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemName = C_Item.GetItemNameByID(itemInfo)",
        type = "function",
    },
    GetItemNumAddedSockets = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "socketCount",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "socketCount = C_Item.GetItemNumAddedSockets(itemInfo)",
        type = "function",
    },
    GetItemNumSockets = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "socketCount",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "socketCount = C_Item.GetItemNumSockets(itemInfo)",
        type = "function",
    },
    GetItemQuality = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "itemQuality",
                nilable = true,
                type = "ItemQuality",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemQuality = C_Item.GetItemQuality(itemLocation)",
        type = "function",
    },
    GetItemQualityByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemQuality",
                nilable = true,
                type = "ItemQuality",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemQuality = C_Item.GetItemQualityByID(itemInfo)",
        type = "function",
    },
    GetItemQualityColor = {
        params = {
            {
                name = "quality",
                nilable = false,
                type = "ItemQuality",
            },
        },
        returns = {
            {
                name = "colorRGBR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorRGBG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorRGBB",
                nilable = false,
                type = "number",
            },
            {
                name = "qualityString",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "colorRGBR, colorRGBG, colorRGBB, qualityString = C_Item.GetItemQualityColor(quality)",
        type = "function",
    },
    GetItemSetInfo = {
        params = {
            {
                name = "setID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "cstring",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.GetItemSetInfo(setID)",
        type = "function",
    },
    GetItemSpecInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "specTable",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "specTable = C_Item.GetItemSpecInfo(itemInfo)",
        type = "function",
    },
    GetItemSpell = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "spellName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "spellName, spellID = C_Item.GetItemSpell(itemInfo)",
        type = "function",
    },
    GetItemStatDelta = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemLink1",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemLink2",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "statTable",
                nilable = false,
                type = "LuaValueVariant",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "statTable = C_Item.GetItemStatDelta(itemLink1, itemLink2)",
        type = "function",
    },
    GetItemStats = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemLink",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "statTable",
                nilable = false,
                type = "LuaValueVariant",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "statTable = C_Item.GetItemStats(itemLink)",
        type = "function",
    },
    GetItemSubClassInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemClassID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemSubClassID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "subClassName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "subClassUsesInvType",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "subClassName, subClassUsesInvType = C_Item.GetItemSubClassInfo(itemClassID, itemSubClassID)",
        type = "function",
    },
    GetItemUniqueness = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "limitCategory",
                nilable = false,
                type = "number",
            },
            {
                name = "limitMax",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "limitCategory, limitMax = C_Item.GetItemUniqueness(itemInfo)",
        type = "function",
    },
    GetItemUniquenessByID = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isUnique",
                nilable = false,
                type = "bool",
            },
            {
                name = "limitCategoryName",
                nilable = true,
                type = "cstring",
            },
            {
                name = "limitCategoryCount",
                nilable = true,
                type = "number",
            },
            {
                name = "limitCategoryID",
                nilable = true,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isUnique, limitCategoryName, limitCategoryCount, limitCategoryID = C_Item.GetItemUniquenessByID(itemInfo)",
        type = "function",
    },
    GetItemUpgradeInfo = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "itemUpgradeInfo",
                nilable = true,
                type = "ItemUpgradeInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemUpgradeInfo = C_Item.GetItemUpgradeInfo(itemInfo)",
        type = "function",
    },
    GetLimitedCurrencyItemInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "name",
                nilable = false,
                type = "cstring",
            },
            {
                name = "icon",
                nilable = false,
                type = "fileID",
            },
            {
                name = "quantity",
                nilable = false,
                type = "number",
            },
            {
                name = "maxQuantity",
                nilable = false,
                type = "number",
            },
            {
                name = "totalEarned",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "name, icon, quantity, maxQuantity, totalEarned = C_Item.GetLimitedCurrencyItemInfo(itemInfo)",
        type = "function",
    },
    GetSetBonusesForSpecializationByItemID = {
        mayReturnNothing = true,
        params = {
            {
                name = "specID",
                nilable = false,
                type = "number",
            },
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "itemSetSpellIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "itemSetSpellIDs = C_Item.GetSetBonusesForSpecializationByItemID(specID, itemID)",
        type = "function",
    },
    GetStackCount = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "stackCount",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "stackCount = C_Item.GetStackCount(itemLocation)",
        type = "function",
    },
    ITEM_CHANGED = {
        cppName = "ItemChanged",
        literalName = "ITEM_CHANGED",
        payload = {
            {
                name = "previousHyperlink",
                nilable = false,
                type = "string",
            },
            {
                name = "newHyperlink",
                nilable = false,
                type = "string",
            },
        },
        synchronous = true,
        type = "event",
    },
    ITEM_CONVERSION_DATA_READY = {
        cppName = "ItemConversionDataReady",
        literalName = "ITEM_CONVERSION_DATA_READY",
        payload = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        synchronous = true,
        type = "event",
    },
    ITEM_COUNT_CHANGED = {
        cppName = "ItemCountChanged",
        literalName = "ITEM_COUNT_CHANGED",
        payload = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
        },
        synchronous = false,
        type = "event",
    },
    ITEM_DATA_LOAD_RESULT = {
        cppName = "ItemDataLoadResult",
        literalName = "ITEM_DATA_LOAD_RESULT",
        payload = {
            {
                name = "itemID",
                nilable = false,
                type = "number",
            },
            {
                name = "success",
                nilable = false,
                type = "bool",
            },
        },
        synchronous = true,
        type = "event",
    },
    IsAnimaItemByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isAnimaItem",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isAnimaItem = C_Item.IsAnimaItemByID(itemInfo)",
        type = "function",
    },
    IsArtifactPowerItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsArtifactPowerItem(itemInfo)",
        type = "function",
    },
    IsBound = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isBound",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isBound = C_Item.IsBound(itemLocation)",
        type = "function",
    },
    IsBoundToAccountUntilEquip = {
        desc = "You can use IsItemBindToAccountUntilEquip instead if the item is not in your inventory",
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isBoundToAccountUntilEquip",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isBoundToAccountUntilEquip = C_Item.IsBoundToAccountUntilEquip(itemLocation)",
        type = "function",
    },
    IsConsumableItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsConsumableItem(itemInfo)",
        type = "function",
    },
    IsCorruptedItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = true,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsCorruptedItem(itemInfo)",
        type = "function",
    },
    IsCosmeticItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = true,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsCosmeticItem(itemInfo)",
        type = "function",
    },
    IsCurioItem = {
        desc = "Returns whether the item is a consumable curio that can be applied to a delves companion.",
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = true,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsCurioItem(itemInfo)",
        type = "function",
    },
    IsCurrentItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsCurrentItem(itemInfo)",
        type = "function",
    },
    IsDecorItem = {
        desc = "Returns whether the item is a consumable decor item.",
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isDecor",
                nilable = true,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isDecor = C_Item.IsDecorItem(itemInfo)",
        type = "function",
    },
    IsDressableItemByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isDressableItem",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isDressableItem = C_Item.IsDressableItemByID(itemInfo)",
        type = "function",
    },
    IsEquippableItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsEquippableItem(itemInfo)",
        type = "function",
    },
    IsEquippedItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsEquippedItem(itemInfo)",
        type = "function",
    },
    IsEquippedItemType = {
        params = {
            {
                name = "type",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsEquippedItemType(type)",
        type = "function",
    },
    IsHarmfulItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsHarmfulItem(itemInfo)",
        type = "function",
    },
    IsHelpfulItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsHelpfulItem(itemInfo)",
        type = "function",
    },
    IsItemBindToAccount = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isItemBindToAccount",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isItemBindToAccount = C_Item.IsItemBindToAccount(itemInfo)",
        type = "function",
    },
    IsItemBindToAccountUntilEquip = {
        desc = "You can use IsBoundToAccountUntilEquip instead if the item exists in your inventory",
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isItemBindToAccountUntilEquip",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isItemBindToAccountUntilEquip = C_Item.IsItemBindToAccountUntilEquip(itemInfo)",
        type = "function",
    },
    IsItemConduit = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isConduit",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isConduit = C_Item.IsItemConduit(itemLoc)",
        type = "function",
    },
    IsItemConvertibleAndValidForPlayer = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isItemConvertibleAndValidForPlayer",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isItemConvertibleAndValidForPlayer = C_Item.IsItemConvertibleAndValidForPlayer(itemLoc)",
        type = "function",
    },
    IsItemCorrupted = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isCorrupted",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isCorrupted = C_Item.IsItemCorrupted(itemLoc)",
        type = "function",
    },
    IsItemCorruptionRelated = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isCorruptionRelated",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isCorruptionRelated = C_Item.IsItemCorruptionRelated(itemLoc)",
        type = "function",
    },
    IsItemCorruptionResistant = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLoc",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isCorruptionResistant",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isCorruptionResistant = C_Item.IsItemCorruptionResistant(itemLoc)",
        type = "function",
    },
    IsItemDataCached = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isCached",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isCached = C_Item.IsItemDataCached(itemLocation)",
        type = "function",
    },
    IsItemDataCachedByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isCached",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isCached = C_Item.IsItemDataCachedByID(itemInfo)",
        type = "function",
    },
    IsItemGUIDInInventory = {
        params = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {
            {
                name = "valid",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "valid = C_Item.IsItemGUIDInInventory(itemGUID)",
        type = "function",
    },
    IsItemInRange = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                name = "targetToken",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {
            {
                name = "result",
                nilable = true,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsItemInRange(itemInfo, targetToken)",
        type = "function",
    },
    IsItemKeystoneByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isKeystone",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isKeystone = C_Item.IsItemKeystoneByID(itemInfo)",
        type = "function",
    },
    IsItemSpecificToPlayerClass = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "isItemSpecificToPlayerClass",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isItemSpecificToPlayerClass = C_Item.IsItemSpecificToPlayerClass(itemInfo)",
        type = "function",
    },
    IsLocked = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {
            {
                name = "isLocked",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isLocked = C_Item.IsLocked(itemLocation)",
        type = "function",
    },
    IsRelicItem = {
        desc = "Returns whether the item is a consumable relic  that can be applied to an artifact weapon.",
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = true,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.IsRelicItem(itemInfo)",
        type = "function",
    },
    IsUsableItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "usable",
                nilable = false,
                type = "bool",
            },
            {
                name = "noMana",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "usable, noMana = C_Item.IsUsableItem(itemInfo)",
        type = "function",
    },
    ItemHasRange = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = C_Item.ItemHasRange(itemInfo)",
        type = "function",
    },
    ItemInfoResult = {
        fields = {
            {
                name = "itemName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemLink",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemQuality",
                nilable = false,
                type = "ItemQuality",
            },
            {
                name = "itemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "itemMinLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "itemType",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemSubType",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemStackCount",
                nilable = false,
                type = "number",
            },
            {
                name = "itemEquipLoc",
                nilable = false,
                type = "cstring",
            },
            {
                name = "itemTexture",
                nilable = false,
                type = "fileID",
            },
            {
                name = "sellPrice",
                nilable = false,
                type = "number",
            },
            {
                name = "classID",
                nilable = false,
                type = "number",
            },
            {
                name = "subclassID",
                nilable = false,
                type = "number",
            },
            {
                name = "bindType",
                nilable = false,
                type = "number",
            },
            {
                name = "expansionID",
                nilable = false,
                type = "number",
            },
            {
                name = "setID",
                nilable = true,
                type = "number",
            },
            {
                name = "isCraftingReagent",
                nilable = false,
                type = "bool",
            },
            {
                name = "itemDescription",
                nilable = false,
                type = "cstring",
            },
        },
        type = "structure",
    },
    ItemUpgradeInfo = {
        fields = {
            {
                name = "currentLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "maxLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "maxItemLevel",
                nilable = false,
                type = "number",
            },
            {
                name = "trackString",
                nilable = true,
                type = "cstring",
            },
            {
                name = "trackStringID",
                nilable = true,
                type = "number",
            },
        },
        type = "structure",
    },
    LockItem = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.LockItem(itemLocation)",
        type = "function",
    },
    LockItemByGUID = {
        params = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.LockItemByGUID(itemGUID)",
        type = "function",
    },
    MERCHANT_CONFIRM_TRADE_TIMER_REMOVAL = {
        cppName = "MerchantConfirmTradeTimerRemoval",
        literalName = "MERCHANT_CONFIRM_TRADE_TIMER_REMOVAL",
        payload = {
            {
                name = "itemLink",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    PickupItem = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.PickupItem(itemInfo)",
        type = "function",
    },
    REPLACE_ENCHANT = {
        cppName = "ReplaceEnchant",
        literalName = "REPLACE_ENCHANT",
        payload = {
            {
                name = "existingStr",
                nilable = false,
                type = "cstring",
            },
            {
                name = "replacementStr",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    REPLACE_TRADESKILL_ENCHANT = {
        cppName = "ReplaceTradeskillEnchant",
        literalName = "REPLACE_TRADESKILL_ENCHANT",
        payload = {
            {
                name = "existing",
                nilable = false,
                type = "cstring",
            },
            {
                name = "replacement",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    ReplaceEnchant = {
        params = {},
        returns = {},
        signature = "C_Item.ReplaceEnchant()",
        type = "function",
    },
    ReplaceTradeEnchant = {
        params = {},
        returns = {},
        signature = "C_Item.ReplaceTradeEnchant()",
        type = "function",
    },
    ReplaceTradeskillEnchant = {
        params = {},
        returns = {},
        signature = "C_Item.ReplaceTradeskillEnchant()",
        type = "function",
    },
    RequestLoadItemData = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.RequestLoadItemData(itemLocation)",
        type = "function",
    },
    RequestLoadItemDataByID = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.RequestLoadItemDataByID(itemInfo)",
        type = "function",
    },
    TRADE_REPLACE_ENCHANT = {
        cppName = "TradeReplaceEnchant",
        literalName = "TRADE_REPLACE_ENCHANT",
        payload = {
            {
                name = "existing",
                nilable = false,
                type = "cstring",
            },
            {
                name = "replacement",
                nilable = false,
                type = "cstring",
            },
        },
        synchronous = true,
        type = "event",
    },
    USE_BIND_CONFIRM = {
        cppName = "UseBindConfirm",
        literalName = "USE_BIND_CONFIRM",
        payload = {},
        synchronous = true,
        type = "event",
    },
    USE_NO_REFUND_CONFIRM = {
        cppName = "UseNoRefundConfirm",
        literalName = "USE_NO_REFUND_CONFIRM",
        payload = {},
        synchronous = true,
        type = "event",
    },
    UnlockItem = {
        params = {
            {
                mixin = "ItemLocationMixin",
                name = "itemLocation",
                nilable = false,
                type = "ItemLocation",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.UnlockItem(itemLocation)",
        type = "function",
    },
    UnlockItemByGUID = {
        params = {
            {
                name = "itemGUID",
                nilable = false,
                type = "WOWGUID",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.UnlockItemByGUID(itemGUID)",
        type = "function",
    },
    UseItemByName = {
        params = {
            {
                name = "itemInfo",
                nilable = false,
                type = "ItemInfo",
            },
            {
                name = "target",
                nilable = true,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_Item.UseItemByName(itemInfo, target)",
        type = "function",
    },
    WEAPON_ENCHANT_CHANGED = {
        cppName = "WeaponEnchantChanged",
        literalName = "WEAPON_ENCHANT_CHANGED",
        payload = {},
        synchronous = false,
        type = "event",
    },
})
