-- Forge_APIRef-C_CooldownViewer: per-namespace API data for C_CooldownViewer.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/CooldownViewerDocumentation.lua.
-- Generated 2026-05-06 13:02:26Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_CooldownViewer", {
    COOLDOWN_VIEWER_DATA_LOADED = {
        cppName = "CooldownViewerDataLoaded",
        literalName = "COOLDOWN_VIEWER_DATA_LOADED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    COOLDOWN_VIEWER_SPELL_OVERRIDE_UPDATED = {
        cppName = "CooldownViewerSpellOverrideUpdated",
        literalName = "COOLDOWN_VIEWER_SPELL_OVERRIDE_UPDATED",
        payload = {
            {
                name = "baseSpellID",
                nilable = false,
                type = "number",
            },
            {
                name = "overrideSpellID",
                nilable = true,
                type = "number",
            },
        },
        synchronous = true,
        type = "event",
    },
    COOLDOWN_VIEWER_TABLE_HOTFIXED = {
        cppName = "CooldownViewerTableHotfixed",
        literalName = "COOLDOWN_VIEWER_TABLE_HOTFIXED",
        payload = {},
        synchronous = true,
        type = "event",
    },
    CooldownViewerCooldown = {
        fields = {
            {
                name = "cooldownID",
                nilable = false,
                type = "number",
            },
            {
                name = "spellID",
                nilable = false,
                type = "number",
            },
            {
                name = "overrideSpellID",
                nilable = true,
                type = "number",
            },
            {
                name = "overrideTooltipSpellID",
                nilable = true,
                type = "number",
            },
            {
                innerType = "number",
                name = "linkedSpellIDs",
                nilable = false,
                type = "table",
            },
            {
                name = "selfAura",
                nilable = false,
                type = "bool",
            },
            {
                name = "hasAura",
                nilable = false,
                type = "bool",
            },
            {
                name = "charges",
                nilable = false,
                type = "bool",
            },
            {
                name = "isKnown",
                nilable = false,
                type = "bool",
            },
            {
                name = "flags",
                nilable = false,
                type = "CooldownSetSpellFlags",
            },
            {
                name = "category",
                nilable = false,
                type = "CooldownViewerCategory",
            },
        },
        type = "structure",
    },
    GetCooldownViewerCategorySet = {
        params = {
            {
                name = "category",
                nilable = false,
                type = "CooldownViewerCategory",
            },
            {
                default = false,
                name = "allowUnlearned",
                nilable = false,
                type = "bool",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "cooldownIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "cooldownIDs = C_CooldownViewer.GetCooldownViewerCategorySet(category, allowUnlearned)",
        type = "function",
    },
    GetCooldownViewerCooldownInfo = {
        mayReturnNothing = true,
        params = {
            {
                name = "cooldownID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "cooldownInfo",
                nilable = false,
                type = "CooldownViewerCooldown",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "cooldownInfo = C_CooldownViewer.GetCooldownViewerCooldownInfo(cooldownID)",
        type = "function",
    },
    GetLayoutData = {
        params = {},
        returns = {
            {
                name = "data",
                nilable = false,
                type = "cstring",
            },
        },
        signature = "data = C_CooldownViewer.GetLayoutData()",
        type = "function",
    },
    GetValidAlertTypes = {
        params = {
            {
                name = "cooldownID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "CooldownViewerAlertEventType",
                name = "validAlertTypes",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "validAlertTypes = C_CooldownViewer.GetValidAlertTypes(cooldownID)",
        type = "function",
    },
    IsCooldownViewerAvailable = {
        params = {},
        returns = {
            {
                name = "isAvailable",
                nilable = false,
                type = "bool",
            },
            {
                name = "failureReason",
                nilable = false,
                type = "string",
            },
        },
        signature = "isAvailable, failureReason = C_CooldownViewer.IsCooldownViewerAvailable()",
        type = "function",
    },
    SetLayoutData = {
        params = {
            {
                name = "data",
                nilable = false,
                type = "cstring",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_CooldownViewer.SetLayoutData(data)",
        type = "function",
    },
})
