-- Forge_APIRef-C_QuestLine: per-namespace API data for C_QuestLine.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/QuestLineInfoDocumentation.lua.
-- Generated 2026-05-06 13:02:29Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_QuestLine", {
    GetAvailableQuestLines = {
        params = {
            {
                name = "uiMapID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "QuestLineInfo",
                name = "questLines",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "questLines = C_QuestLine.GetAvailableQuestLines(uiMapID)",
        type = "function",
    },
    GetForceVisibleQuests = {
        params = {
            {
                name = "uiMapID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "questIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "questIDs = C_QuestLine.GetForceVisibleQuests(uiMapID)",
        type = "function",
    },
    GetQuestLineInfo = {
        params = {
            {
                name = "questID",
                nilable = false,
                type = "number",
            },
            {
                name = "uiMapID",
                nilable = true,
                type = "number",
            },
            {
                default = false,
                name = "displayableOnly",
                nilable = false,
                type = "bool",
            },
        },
        returns = {
            {
                name = "questLineInfo",
                nilable = true,
                type = "QuestLineInfo",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "questLineInfo = C_QuestLine.GetQuestLineInfo(questID, uiMapID, displayableOnly)",
        type = "function",
    },
    GetQuestLineQuests = {
        params = {
            {
                name = "questLineID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                innerType = "number",
                name = "questIDs",
                nilable = false,
                type = "table",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "questIDs = C_QuestLine.GetQuestLineQuests(questLineID)",
        type = "function",
    },
    IsComplete = {
        params = {
            {
                name = "questLineID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "isComplete",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "isComplete = C_QuestLine.IsComplete(questLineID)",
        type = "function",
    },
    QuestLineFloorLocation = {
        maxValue = 2,
        minValue = 0,
        numValues = 3,
        type = "enum",
        values = {
            {
                name = "Above",
                value = 0,
            },
            {
                name = "Below",
                value = 1,
            },
            {
                name = "Same",
                value = 2,
            },
        },
    },
    QuestLineIgnoresAccountCompletedFiltering = {
        params = {
            {
                name = "uiMapID",
                nilable = false,
                type = "number",
            },
            {
                name = "questLineID",
                nilable = false,
                type = "number",
            },
        },
        returns = {
            {
                name = "questLineIgnoresAccountCompletedFiltering",
                nilable = false,
                type = "bool",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "questLineIgnoresAccountCompletedFiltering = C_QuestLine.QuestLineIgnoresAccountCompletedFiltering(uiMapID, questLineID)",
        type = "function",
    },
    QuestLineInfo = {
        fields = {
            {
                name = "questLineName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "questName",
                nilable = false,
                type = "cstring",
            },
            {
                name = "questLineID",
                nilable = false,
                type = "number",
            },
            {
                name = "questID",
                nilable = false,
                type = "number",
            },
            {
                name = "x",
                nilable = false,
                type = "number",
            },
            {
                name = "y",
                nilable = false,
                type = "number",
            },
            {
                name = "isHidden",
                nilable = false,
                type = "bool",
            },
            {
                name = "isLegendary",
                nilable = false,
                type = "bool",
            },
            {
                name = "isLocalStory",
                nilable = false,
                type = "bool",
            },
            {
                name = "isDaily",
                nilable = false,
                type = "bool",
            },
            {
                name = "isCampaign",
                nilable = false,
                type = "bool",
            },
            {
                name = "isImportant",
                nilable = false,
                type = "bool",
            },
            {
                name = "isAccountCompleted",
                nilable = false,
                type = "bool",
            },
            {
                name = "isCombatAllyQuest",
                nilable = false,
                type = "bool",
            },
            {
                name = "isMeta",
                nilable = false,
                type = "bool",
            },
            {
                name = "inProgress",
                nilable = false,
                type = "bool",
            },
            {
                name = "isQuestStart",
                nilable = false,
                type = "bool",
            },
            {
                name = "floorLocation",
                nilable = false,
                type = "QuestLineFloorLocation",
            },
            {
                name = "startMapID",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
    RequestQuestLinesForMap = {
        params = {
            {
                name = "uiMapID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "C_QuestLine.RequestQuestLinesForMap(uiMapID)",
        type = "function",
    },
})
