-- Forge_APIRef-C_WorldSafeLocsUIInternal: per-namespace API data for C_WorldSafeLocsUIInternal.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/WorldSafeLocsUIInternalDocumentation.lua.
-- Generated 2026-05-06 13:02:32Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("C_WorldSafeLocsUIInternal", {
    GetWorldSafeLocs = {
        params = {},
        returns = {
            {
                innerType = "WorldSafeLocInfo",
                name = "worldSafeLocs",
                nilable = false,
                type = "table",
            },
        },
        signature = "worldSafeLocs = C_WorldSafeLocsUIInternal.GetWorldSafeLocs()",
        type = "function",
    },
    WorldSafeLocInfo = {
        fields = {
            {
                name = "name",
                nilable = false,
                type = "string",
            },
            {
                name = "continent",
                nilable = false,
                type = "number",
            },
            {
                mixin = "Vector3DMixin",
                name = "loc",
                nilable = false,
                type = "vector3",
            },
            {
                name = "facing",
                nilable = false,
                type = "number",
            },
        },
        type = "structure",
    },
})
