-- Forge_APIRef-GARRISON_TYPEConstants: per-namespace API data for GARRISON_TYPEConstants.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/GARRISON_TYPEConstantsDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("GARRISON_TYPEConstants", {
    GarrisonType = {
        maxValue = 111,
        minValue = 2,
        numValues = 4,
        type = "enum",
        values = {
            {
                name = "Type_6_0_Garrison",
                value = 2,
            },
            {
                name = "Type_7_0_Garrison",
                value = 3,
            },
            {
                name = "Type_8_0_Garrison",
                value = 9,
            },
            {
                name = "Type_9_0_Garrison",
                value = 111,
            },
        },
    },
})
