-- Forge_APIRef-LuaDurationObjectAPI: per-namespace API data for LuaDurationObjectAPI.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/LuaDurationObjectAPIDocumentation.lua.
-- Generated 2026-05-06 13:02:28Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("LuaDurationObjectAPI", {
    Assign = {
        desc = "Copies another duration object and assigns it to this one.",
        params = {
            {
                name = "other",
                nilable = false,
                type = "LuaDurationObject",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "LuaDurationObjectAPI.Assign(other)",
        type = "function",
    },
    Copy = {
        desc = "Returns a copy of this duration object.",
        params = {},
        returns = {
            {
                name = "copy",
                nilable = false,
                type = "LuaDurationObject",
            },
        },
        signature = "copy = LuaDurationObjectAPI.Copy()",
        type = "function",
    },
    EvaluateElapsedDuration = {
        desc = "Calculates the elapsed duration in seconds and evaluates it against a supplied curve.",
        params = {
            {
                name = "curve",
                nilable = false,
                type = "LuaCurveObjectBase",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "LuaCurveEvaluatedResult",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = LuaDurationObjectAPI.EvaluateElapsedDuration(curve, modifier)",
        type = "function",
    },
    EvaluateElapsedPercent = {
        desc = "Calculates the elapsed duration as a percentage value and evaluates it against a supplied curve.",
        params = {
            {
                name = "curve",
                nilable = false,
                type = "LuaCurveObjectBase",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "LuaCurveEvaluatedResult",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = LuaDurationObjectAPI.EvaluateElapsedPercent(curve, modifier)",
        type = "function",
    },
    EvaluateRemainingDuration = {
        desc = "Calculates the remaining duration in seconds and evaluates it against a supplied curve.",
        params = {
            {
                name = "curve",
                nilable = false,
                type = "LuaCurveObjectBase",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "LuaCurveEvaluatedResult",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = LuaDurationObjectAPI.EvaluateRemainingDuration(curve, modifier)",
        type = "function",
    },
    EvaluateRemainingPercent = {
        desc = "Calculates the remaining duration as a percentage value and evaluates it against a supplied curve.",
        params = {
            {
                name = "curve",
                nilable = false,
                type = "LuaCurveObjectBase",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "LuaCurveEvaluatedResult",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = LuaDurationObjectAPI.EvaluateRemainingPercent(curve, modifier)",
        type = "function",
    },
    EvaluateTotalDuration = {
        desc = "Calculates the total duration in seconds and evaluates it against a supplied curve.",
        params = {
            {
                name = "curve",
                nilable = false,
                type = "LuaCurveObjectBase",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "result",
                nilable = false,
                type = "LuaCurveEvaluatedResult",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "result = LuaDurationObjectAPI.EvaluateTotalDuration(curve, modifier)",
        type = "function",
    },
    FormatElapsedDuration = {
        desc = "Formats the elapsed duration of this object to a string.",
        params = {
            {
                name = "formatter",
                nilable = false,
                type = "NumericFormatter",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "formatted",
                nilable = false,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "formatted = LuaDurationObjectAPI.FormatElapsedDuration(formatter, modifier)",
        type = "function",
    },
    FormatRemainingDuration = {
        desc = "Formats the remaining duration of this object to a string.",
        params = {
            {
                name = "formatter",
                nilable = false,
                type = "NumericFormatter",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "formatted",
                nilable = false,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "formatted = LuaDurationObjectAPI.FormatRemainingDuration(formatter, modifier)",
        type = "function",
    },
    FormatTotalDuration = {
        desc = "Formats the total duration of this object to a string.",
        params = {
            {
                name = "formatter",
                nilable = false,
                type = "NumericFormatter",
            },
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "formatted",
                nilable = false,
                type = "string",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "formatted = LuaDurationObjectAPI.FormatTotalDuration(formatter, modifier)",
        type = "function",
    },
    GetClockTime = {
        desc = "Returns the current time of the clock source used by this object.",
        params = {},
        returns = {
            {
                name = "clockTime",
                nilable = false,
                type = "FrameTime",
            },
        },
        signature = "clockTime = LuaDurationObjectAPI.GetClockTime()",
        type = "function",
    },
    GetElapsedDuration = {
        desc = "Calculates the elapsed duration of the stored time span.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "elapsedDuration",
                nilable = false,
                type = "DurationSeconds",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "elapsedDuration = LuaDurationObjectAPI.GetElapsedDuration(modifier)",
        type = "function",
    },
    GetElapsedPercent = {
        desc = "Calculates the elapsed duration as a percentage value.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "elapsedPercent",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "elapsedPercent = LuaDurationObjectAPI.GetElapsedPercent(modifier)",
        type = "function",
    },
    GetEndTime = {
        desc = "Calculates the end time of the stored time span.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "endTime",
                nilable = false,
                type = "FrameTime",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "endTime = LuaDurationObjectAPI.GetEndTime(modifier)",
        type = "function",
    },
    GetModRate = {
        desc = "Returns the divisor used to convert a duration from real time to base time.",
        params = {},
        returns = {
            {
                name = "modRate",
                nilable = false,
                type = "number",
            },
        },
        signature = "modRate = LuaDurationObjectAPI.GetModRate()",
        type = "function",
    },
    GetRemainingDuration = {
        desc = "Calculates the remaining duration of the stored time span.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "remainingDuration",
                nilable = false,
                type = "DurationSeconds",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "remainingDuration = LuaDurationObjectAPI.GetRemainingDuration(modifier)",
        type = "function",
    },
    GetRemainingPercent = {
        desc = "Calculates the remaining duration as a percentage value.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "remainingPercent",
                nilable = false,
                type = "number",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "remainingPercent = LuaDurationObjectAPI.GetRemainingPercent(modifier)",
        type = "function",
    },
    GetStartTime = {
        desc = "Calculates the start time of the stored time span.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "startTime",
                nilable = false,
                type = "FrameTime",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "startTime = LuaDurationObjectAPI.GetStartTime(modifier)",
        type = "function",
    },
    GetTotalDuration = {
        desc = "Calculates the total duration of the stored time span.",
        params = {
            {
                default = "RealTime",
                name = "modifier",
                nilable = false,
                type = "DurationTimeModifier",
            },
        },
        returns = {
            {
                name = "totalDuration",
                nilable = false,
                type = "DurationSeconds",
            },
        },
        secretArguments = "AllowedWhenUntainted",
        signature = "totalDuration = LuaDurationObjectAPI.GetTotalDuration(modifier)",
        type = "function",
    },
    HasSecretValues = {
        desc = "Returns true if the duration has been configured with any secret values.",
        params = {},
        returns = {
            {
                name = "hasSecretValues",
                nilable = false,
                type = "bool",
            },
        },
        signature = "hasSecretValues = LuaDurationObjectAPI.HasSecretValues()",
        type = "function",
    },
    IsZero = {
        desc = "Returns true if the duration object is measuring a zero duration time span.",
        params = {},
        returns = {
            {
                name = "isZero",
                nilable = false,
                type = "bool",
            },
        },
        signature = "isZero = LuaDurationObjectAPI.IsZero()",
        type = "function",
    },
    Reset = {
        desc = "Resets the duration object to represent a zero duration time span.",
        params = {},
        returns = {},
        signature = "LuaDurationObjectAPI.Reset()",
        type = "function",
    },
    SetTimeFromEnd = {
        desc = "Configures the duration object to represent an end time and a duration.",
        params = {
            {
                name = "endTime",
                nilable = false,
                type = "FrameTime",
            },
            {
                name = "duration",
                nilable = false,
                type = "DurationSeconds",
            },
            {
                default = 1,
                name = "modRate",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "LuaDurationObjectAPI.SetTimeFromEnd(endTime, duration, modRate)",
        type = "function",
    },
    SetTimeFromStart = {
        desc = "Configures the duration object to represent a start time and a duration.",
        params = {
            {
                name = "startTime",
                nilable = false,
                type = "FrameTime",
            },
            {
                name = "duration",
                nilable = false,
                type = "DurationSeconds",
            },
            {
                default = 1,
                name = "modRate",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "LuaDurationObjectAPI.SetTimeFromStart(startTime, duration, modRate)",
        type = "function",
    },
    SetTimeSpan = {
        desc = "Configures the duration object to represent a fixed start and end time span. If the end time is earlier than the start time, the duration will clamp to zero.",
        params = {
            {
                name = "startTime",
                nilable = false,
                type = "FrameTime",
            },
            {
                name = "endTime",
                nilable = false,
                type = "FrameTime",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "LuaDurationObjectAPI.SetTimeSpan(startTime, endTime)",
        type = "function",
    },
    SetToDefaults = {
        desc = "Resets all state on the duration, and clears the secret values flag.",
        params = {},
        returns = {},
        signature = "LuaDurationObjectAPI.SetToDefaults()",
        type = "function",
    },
})
