-- Forge_APIRef-FrameAPIUnitPositionFrame: per-namespace API data for FrameAPIUnitPositionFrame.
--
-- Auto-generated by Forge_APIRef/.dev/bake.py from
-- Blizzard_APIDocumentationGenerated/FrameAPIUnitPositionFrameDocumentation.lua.
-- Generated 2026-05-06 13:02:27Z.
--
-- DO NOT EDIT BY HAND. Re-run bake.py to refresh from the upstream
-- mirror at github.com/Gethe/wow-ui-source.

if not ForgeAPIRef or not ForgeAPIRef.Register then
    return
end

ForgeAPIRef:Register("FrameAPIUnitPositionFrame", {
    AddUnit = {
        params = {
            {
                name = "unitTokenString",
                nilable = false,
                type = "cstring",
            },
            {
                name = "asset",
                nilable = false,
                type = "TextureAssetDisk",
            },
            {
                name = "width",
                nilable = true,
                type = "uiUnit",
            },
            {
                name = "height",
                nilable = true,
                type = "uiUnit",
            },
            {
                name = "r",
                nilable = true,
                type = "number",
            },
            {
                name = "g",
                nilable = true,
                type = "number",
            },
            {
                name = "b",
                nilable = true,
                type = "number",
            },
            {
                name = "a",
                nilable = true,
                type = "number",
            },
            {
                name = "sublayer",
                nilable = true,
                type = "number",
            },
            {
                name = "showFacing",
                nilable = true,
                type = "bool",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPIUnitPositionFrame.AddUnit(unitTokenString, asset, width, height, r, g, b, a, sublayer, showFacing)",
        type = "function",
    },
    ClearUnits = {
        params = {},
        returns = {},
        signature = "FrameAPIUnitPositionFrame.ClearUnits()",
        type = "function",
    },
    FinalizeUnits = {
        params = {},
        returns = {},
        signature = "FrameAPIUnitPositionFrame.FinalizeUnits()",
        type = "function",
    },
    GetMouseOverUnits = {
        params = {},
        returns = {
            {
                name = "units",
                nilable = false,
                type = "UnitTokenType",
            },
        },
        signature = "units = FrameAPIUnitPositionFrame.GetMouseOverUnits()",
        type = "function",
    },
    GetPlayerPingScale = {
        params = {},
        returns = {
            {
                name = "scale",
                nilable = false,
                type = "number",
            },
        },
        signature = "scale = FrameAPIUnitPositionFrame.GetPlayerPingScale()",
        type = "function",
    },
    GetUiMapID = {
        params = {},
        returns = {
            {
                name = "mapID",
                nilable = false,
                type = "number",
            },
        },
        signature = "mapID = FrameAPIUnitPositionFrame.GetUiMapID()",
        type = "function",
    },
    SetPlayerPingScale = {
        params = {
            {
                name = "scale",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPIUnitPositionFrame.SetPlayerPingScale(scale)",
        type = "function",
    },
    SetPlayerPingTexture = {
        params = {
            {
                name = "textureType",
                nilable = false,
                type = "PingTextureType",
            },
            {
                name = "asset",
                nilable = false,
                type = "FileAsset",
            },
            {
                default = 0,
                name = "width",
                nilable = false,
                type = "uiUnit",
            },
            {
                default = 0,
                name = "height",
                nilable = false,
                type = "uiUnit",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPIUnitPositionFrame.SetPlayerPingTexture(textureType, asset, width, height)",
        type = "function",
    },
    SetUiMapID = {
        params = {
            {
                name = "mapID",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPIUnitPositionFrame.SetUiMapID(mapID)",
        type = "function",
    },
    SetUnitColor = {
        params = {
            {
                name = "unit",
                nilable = false,
                type = "UnitTokenType",
            },
            {
                name = "colorR",
                nilable = false,
                type = "number",
            },
            {
                name = "colorG",
                nilable = false,
                type = "number",
            },
            {
                name = "colorB",
                nilable = false,
                type = "number",
            },
            {
                name = "colorA",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPIUnitPositionFrame.SetUnitColor(unit, colorR, colorG, colorB, colorA)",
        type = "function",
    },
    StartPlayerPing = {
        params = {
            {
                default = 0,
                name = "duration",
                nilable = false,
                type = "number",
            },
            {
                default = 0,
                name = "fadeDuration",
                nilable = false,
                type = "number",
            },
        },
        returns = {},
        secretArguments = "AllowedWhenUntainted",
        signature = "FrameAPIUnitPositionFrame.StartPlayerPing(duration, fadeDuration)",
        type = "function",
    },
    StopPlayerPing = {
        params = {},
        returns = {},
        signature = "FrameAPIUnitPositionFrame.StopPlayerPing()",
        type = "function",
    },
})
